docs: add table creation from file with table metadata
seedcase-project/seedcase-sprout pull request #105
Opened 2024-01-17 15:07 UTC by signekb

## Description

- This PR adds feature of uploading and downloading table metadata (as described in #99 and #100) in the user flow diagrams and user flow post.

## Related Issues

Closes #101

See also Issues #99 and #100.

## Reviewer Focus

Reviewers should focus on the newly included steps in the diagrams and whether it makes sense to place them there in the user flow.

## Checklist

- [X] Add upload table metadata to user flow diagram (and update png)
- [ ] Add upload of table metadata to user flow post
- [ ] Update relevant subpart user flow diagram with added upload steps

- [ ] Add download of table metadata to user flow diagram (and update png)
- [ ] Add download of table metadata to user flow post
- [ ] Update relevant subpart user flow diagram with added download steps

For all PRs that are not general documentation

- [ ] Tests accompany or reflect changes to the code
- [ ] Tests ran and passed locally
- [ ] Ran the linter and formatter
- [ ] Build has passed locally
- [ ] Relevant documentation has been updated

For general documentation:

- [ ] Spell-check
    - [ ] US
    - [ ] UK
- [ ] Did the page(s) preview correctly on your machine without breaking
- [ ] New category words (keywords) (if any) added to the code snippet file

2024-01-18 11:58 UTC, philter87 approved these changes, later dismissed

2024-01-23 14:53 UTC, philter87 approved these changes, later dismissed

2024-01-23 14:53 UTC, philter87 commented on docs/design/images/user-flow-table-created-continue-to-upload.png
Why would the user download the metadata?

2024-01-24 08:26 UTC, signekb commented on docs/design/images/user-flow-table-created-continue-to-upload.png
See #99

2024-02-02 15:48 UTC, lwjohnst86 requested changes
Small typo, otherwise it looks great! I'll apply the suggestion, approve, then merge.

2024-02-02 15:48 UTC, lwjohnst86 commented on docs/design/user-flow.qmd
> +After a table's metadata has been created, the next step is to define the columsn within the table. Column metadata includes:
```suggestion
After a table's metadata has been created, the next step is to define the columns within the table. Column metadata includes:
```

2024-02-02 15:48 UTC, lwjohnst86 submitted a review, later dismissed

2024-02-02 15:49 UTC, lwjohnst86 approved these changes

2024-02-02 15:49 UTC, merged