Feat/file upload page
seedcase-project/seedcase-sprout pull request #110
Opened 2024-01-22 13:07 UTC by philter87

## Description

- This PR adds a page to upload a csv file

## Related Issues

Closes #78 

## Testing

- [X] Yes
- [ ] No, not needed (give a reason below)
- [ ] No, I need help writing them

## Reviewer Focus

The file_upload.py file is the most essential. It loads the template 'file-upload.html'.
I have created a folder called views instead of views.py

## Checklist
For all PRs that are not general documentation

- [X] Tests accompany or reflect changes to the code
- [X] Tests ran and passed locally
- [X] Ran the linter and formatter
- [X] Build has passed locally
- [X] Relevant documentation has been updated

2024-01-24 17:07 UTC, signekb commented
@philter87 when the file is uploaded, should the original file name be saved to the db? There's a field for it in the TableMetadata model

2024-01-25 09:07 UTC, signekb commented on app/tests/tests_views.py
> +        # html should contain "TestTable"
Should be "Table Name"

2024-01-26 14:56 UTC, signekb reviewed
Nice! I have some questions (who is surprised). We'll discuss them on Monday, where I'll update my comments with the answers. 

When I try to upload a .csv file, it still fails with the overlay, saying "Unable to extract headers". I think this might be bc it's a semicolon separated csv (also tried with a tab separated csv - also failed). 
EDIT: This is handled in another PR. #123

2024-01-26 14:56 UTC, signekb commented on app/templates/file-drop-zone.html
> +<script>
Maybe we can go over what happens in this script part on Monday :)

2024-01-26 14:56 UTC, signekb commented on app/templates/file-upload.html
> +  <dialog class="modal active" id="dialog">
Should/can the dialog close when the user starts to upload a new file? It seems like the dialog is open until you click "OK"

2024-01-26 14:56 UTC, signekb commented on app/tests/db_test_utils.py
> +        data_type_id=1,
```suggestion
        data_type=1,
```
Is it possible to just set this ForeignKey as an int?

2024-01-26 14:56 UTC, signekb commented on app/tests/tests_models.py
> +        column_count = ColumnMetadata.objects.count()
Add that columns for that table specific is deleted (by adding `table_id` here) and not just all columns? 

(not sure the suggestion is correct)


```suggestion
        column_count = ColumnMetadata.objects.filter(table_id=1).count()
```

2024-01-26 14:56 UTC, signekb commented on app/tests/tests_models.py
> +        table_count = TableMetadata.objects.count()
Add that we count whether that specific table exist and not just how many tables exists?

(not sure the suggestion is correct - this would also return `True` if table exists and not count)

```suggestion
        table_count = TableMetadata.objects.filter(table_id=1).exists()
```

2024-01-26 14:56 UTC, signekb commented on app/views/__init__.py
Not sure why this is in this file? :)

2024-01-26 14:56 UTC, signekb commented on app/tests/tests_views.py
> +        # html should contain "TestTable"
...or the other way around. Define table_name on L12 as TestTable (I think I prefer this - then we use the same name as in the other tests). I have added this as a suggestion above

2024-01-26 14:56 UTC, signekb commented on app/tests/tests_views.py
> +        table_name = "Table Name"
```suggestion
        table_name = "TestTable"
```

2024-01-26 14:56 UTC, signekb commented on app/tests/tests_views.py
> +    def test_render_file_upload_view_and_verify_that_table_is_loaded(self):
```suggestion
    def test_render_file_upload_view_and_verify_that_table_metadata_is_loaded(self):
```
Added "metadata"

2024-01-26 14:56 UTC, signekb commented on app/tests/tests_views.py
> +        table_name = "Table Name"
```suggestion
        table_name = "TestTable"
```

2024-01-26 14:56 UTC, signekb commented on app/tests/tests_views.py
> +        file = SimpleUploadedFile("file.csv", b"first_name,second_name,age")
What's the b in `b"[...]"` doing?

2024-01-26 14:56 UTC, signekb commented on app/tests/tests_views.py
> +        create_table("Table Name").save()
```suggestion
        create_table("TestTable").save()
```

2024-01-26 14:56 UTC, signekb commented on app/tests/tests_views.py
> +        create_table("Table Name").save()
above, e.g., in L24-25, you have first created the table name variable and then used it. Maybe align so the creation of the table is identical in the tests? I don't have a preference to either method :)

2024-01-26 14:56 UTC, signekb commented on app/tests/tests_views.py
> +        file = SimpleUploadedFile("file-with-bad-headers.csv", b"no valid headers")
Is the headers not valid here bc there's spaces? Or why are they not valid?

2024-01-26 14:56 UTC, signekb commented on app/views/file_upload.py
> +    # A more complicated function needs to be added
Do you have any considerations on what a "more complicated function" should include already?

2024-01-26 14:56 UTC, signekb commented on app/views/file_upload.py
> +        return "The file is missing!"
When will this happen? I doesn't seem to be possible to click "Extract" without a file?

2024-01-26 14:56 UTC, signekb commented on app/views/file_upload.py
> +    if upload_error:
```suggestion
    if upload_error is not None:
```

2024-01-26 20:37 UTC, lwjohnst86 requested changes

2024-01-26 20:37 UTC, lwjohnst86 commented on app/views/file_upload.py
> +def file_upload(request, table_id):
I've been going through and adding docstrings and type hints, just so I can also understand what this does. But I'm a bit confused about where the `table_id` comes from?

2024-01-26 20:37 UTC, lwjohnst86 commented on app/views/file_upload.py
> +    if request.method == "GET":
You mention that there is a POST request, but I only see a GET request. Does it come from somewhere else?

2024-01-26 20:37 UTC, lwjohnst86 commented on app/views/file_upload.py
> +    return redirect("/edit-table-columns/" + str(table_id))
The way I understand the function is that the other `return` statements return an `HttpResponse`object, but this return is a `HttpResponseRedirect` right? Is there a way to write the code to be more predictable? If we can follow philosophies of more strict functional programming (predictable inputs and outputs), that would make the code easier to reason about and understand. Plus the return type hint will be easier to set, then it can be ` -> HttpResponse:`.

2024-01-26 20:37 UTC, lwjohnst86 commented on app/views/file_upload.py
> +        return "Unsupported file format: ." + uploaded_file.name.split(".")[-1]
```suggestion
    if not uploaded_file.name.endswith(".csv"):
        raise StopUpload(True)
```

Same as above. Unless there is a really strong reason to use `return` instead.

2024-01-26 20:37 UTC, lwjohnst86 commented on app/views/file_upload.py
> +        return "The file is missing!"
```suggestion
        raise StopUpload(connection_reset=True)
```

Use a `raise` rather than `return` (same as below). `connection_reset=True` says to stop the upload and restart the connection.

2024-01-26 20:39 UTC, lwjohnst86 commented
Oops, forgot to write a bit more. It would help a lot if the PRs were a bit small 🥺 🙏🏻 🙇🏻 Maybe split future PRs into code vs html?

Could we name `utils` to something more meaningful? Like `uploading`, so that `csv` and other future folders for extensions could be within it?

2024-01-29 09:35 UTC, signekb commented on app/templates/file-drop-zone.html
> +         onclick="event.stopPropagation()">
It makes sure that the click event doesn't hit the dropzone that opens the file directory pop-up

2024-01-29 09:36 UTC, signekb commented on app/templates/file-drop-zone.html
> +    <div hidden id="drag_zone_with_file" class="file-upload-info-box"
Box with file name and info is hidden before we have chosen a file to upload

2024-01-29 09:39 UTC, signekb commented on app/templates/file-drop-zone.html
> +    <div hidden id="drag_zone_with_file" class="file-upload-info-box"
@philter87 will look into using dropzone.dev for this instead. Hopefully, this will simplify the code a bit (and it's pretty).

2024-01-29 09:54 UTC, signekb commented on app/templates/file-drop-zone.html
> +<script>
this might be removed with the use of dropzone.dev

2024-01-29 09:55 UTC, signekb commented on app/tests/db_test_utils.py
> +        data_type_id=1,
Yes, it is.

2024-01-29 09:56 UTC, signekb commented on app/views/__init__.py
they should be moved out :)

2024-01-29 09:57 UTC, signekb commented on app/tests/tests_views.py
> +        file = SimpleUploadedFile("file-with-bad-headers.csv", b"no valid headers")
Because the validator checks that there's more than one column. Here, there's only one.

2024-01-29 09:57 UTC, philter87 commented on app/views/file_upload.py
> +    # A more complicated function needs to be added
This is done in another issue #123

2024-01-29 10:32 UTC, philter87 commented on app/views/file_upload.py
> +        return "The file is missing!"
You are right. The code that disables the button when there are not files was created later

2024-01-29 10:33 UTC, philter87 commented on app/views/file_upload.py
> +    column_names = uploaded_file.readline().decode("utf-8").split(",")
Yes, exactly. That is the "complicated function", I want to put here, which might be the pandas.read_csv

2024-01-29 10:34 UTC, philter87 commented on app/views/file_upload.py
> +def file_upload(request, table_id):
Yes, I see why that is confusing. table_id is defined in the url pattern: 
![image](https://github.com/seedcase-project/seedcase-sprout/assets/5868902/654f1872-d7eb-4476-84c2-82c542837978)

2024-01-29 10:38 UTC, philter87 commented on app/views/file_upload.py
> +    if request.method == "GET":
Yes, I can make this a bit clearer. The get-method is the simplest to process, so I want to return quickly (to avoid too much nesting). The rest of the function is assumed to be handling "POST" requests, but I will change it a bit since it is unclear

2024-01-29 10:39 UTC, philter87 commented on app/views/file_upload.py
> +    return redirect("/edit-table-columns/" + str(table_id))
I will need to think about this one. In my head, it is the obvious think to do, but if it is unclear then I need to iterate a bit on it

2024-01-29 10:41 UTC, philter87 commented on app/views/file_upload.py
> +        return "Unsupported file format: ." + uploaded_file.name.split(".")[-1]
I need to return a error message to the user, but doing this by rasing an error is a great idea

2024-01-29 10:47 UTC, philter87 commented on app/views/file_upload.py
> +        return "The file is missing!"
I think the StopUpload exception is required when you create a custom FileUploadHandler. I am not doing that, but it might be a create way to propagate the error up

2024-01-29 10:49 UTC, philter87 commented
> Oops, forgot to write a bit more. It would help a lot if the PRs were a bit small 🥺 🙏🏻 🙇🏻 Maybe split future PRs into code vs html?
> 
> Could we name `utils` to something more meaningful? Like `uploading`, so that `csv` and other future folders for extensions could be within it?

Yes, I am sorry about the size of the pull request. This is even after I tried to make it smaller, but I will promise not to do it again

2024-02-01 09:17 UTC, merged

2024-02-01 09:18 UTC, signekb commented
@philter87 @K-Beicher and I decided to merge this so we can start putting the pieces from other PRs together with this. We will raise issues if there's something that should be optimised somehow.