Docs/write-up-data-types-as-documentation
seedcase-project/seedcase-sprout pull request #116
Opened 2024-01-24 12:36 UTC by K-Beicher

documentation on which data types should be available when a user sets up a table upload template

2024-01-24 14:52 UTC, signekb requested changes
Very nice! I have added some suggestions. 

**A little tip**: If you use the option to "Format document" in VSCode, it will automatically format the entire document - e.g., add spacing after headers and add a blank line in the bottom of the document. 

Right click in the `md` or `qmd` file and this menu will appear (or use the shortcut shown in the screenshot below):
![image](https://github.com/seedcase-project/seedcase-sprout/assets/40836345/cbc3c9f6-8ed6-4e6c-8ea7-7123b3d5a7a3)

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +Raw text without any form of manipulation should be one of the primary types of data that Seedcase Sprout will store.  The precise name will vary depending on the database system, it may be referred
```suggestion
Raw text without any form of manipulation is one of the primary types of data Seedcase Sprout is able to store. The precise name varies depending on the database system, and it may be referred to as `Char`, `Varchar`, `nVarchar`, or `Text`. In most systems, more than one variation will be in use, all dependent on what data is expected. 

All variations of `Char` will have an option of limiting the number of characters that it is possible to store. This was especially crucial when disk space was at a premium and can still be used as a blunt form of validation of data being saved to a table. For instance, if the field is limited to 2 characters, you can't save the full name of a US state.
```

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +We will be using the Varchar without a limit at this point in time as Text is not a standard SQL type at present.
Not sure what you mean here? Is there a list of "standard SQL types" somewhere that we can link to?
From the table below, it seems like you have chosen that this data type should be "text" in the user interfaces. Is this sentence trying to explain that it will, in practise, be a `varchar` behind the scenes?

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +
```suggestion

<!-- TODO Add hyperlink to documentation when it's done -->

```

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +| Time  | The time value will be stored as hh:mm:ss.  Please see our documentation on the Seedcase website for further information.|
```suggestion
| Time  | The time value will be stored as `hh:mm:ss`. Please see our documentation on the Seedcase website for further information.|
```

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +# Data types in use in Seedcase Sprout
```suggestion
# Data Types in Use in Seedcase Sprout
```
Title casing <3

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +## Main data types
```suggestion
## Main Data Types
```

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +There are several options when it comes to dealing with storing numbers in a database. The most basic is the Integer, which stores whole numbers (both positive and negative). This data type is typica
```suggestion
There are several options when it comes to dealing with storing numbers in a database. The most basic is `Integer`, which stores whole, i.e., non-decimal, numbers (both positive and negative). This data type is typically used where a decimal number doesn't make sense (e.g., when you are counting people, you can't have half a person). Often though, it is important to be able to record a decimal number, which will allow for greater precision. Decimals are often used when storing, for instance, measurements or lab results. 

The choice of number format will also in some instances allow for the database to enforce data quality, by rejecting data at upload if it doesn't conform to type. E.g., if height is stored as integers in cm, a reading in meters like 1.69 won't be allowed.
```

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +We will be offering two options for number formats for now, the Integer for whole numbers and double precision (or float), for decimal numbers.
```suggestion
We offer two options for number formats, the `integer` for whole numbers and `double precision` (or `float`), for decimal numbers.
```
Are double precision and float synonyms?

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +| Whole number   | Also known as Integer. This is a number field which will only allow whole numbers to be stored. Pick this option if you want to store whole numbers (like postcode, number of people
```suggestion
| Whole number   | Also known as `integer`. This is a number field which will only allow whole numbers to be stored. Pick this option if you want to store whole numbers (like postcode, number of people in a household, or height in cm). Please see our documentation on the Seedcase website for further information. |
```
Will we call it "whole number" instead of "integer"?

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +| Decimal number | Also known as Float or Double Precision. This is a number field which will store decimal numbers. Pick this option if you want to store things like lab results, or height in meters
```suggestion
| Decimal number | Also known as `float` or `double precision`. This number field will store decimal numbers. Pick this option if you want to store things like lab results, or height in meters. You should look at Whole number if you want to store things like postcodes. Please see our documentation on the Seedcase website for further information. |
```

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +
```suggestion

<!-- TODO Add hyperlink to documentation when it's done -->

```

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +There are many ways for recording a date and/or time in a database system, the most common would be date, time, and datetime. There is also a choice to be made with regards to time zones and whether
```suggestion
Date and/or time can be stored in many ways in a database system. The most common are `date`, `time`, and `datetime`. There is also a choice to be made with regards to time zones and whether or not a system should be able to deal with data coming from around the world. We do not expect Seedcase to be used across time zones, so we have made the choice to not handle time zones.
```

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +| Date  | The date value will be stored as yyyy-mm-dd, should you need to store time alongside the date this can either be done separately (Time) or in the same field, which would mean that you need
```suggestion
| Date  | The date value will be stored as `yyyy-mm-dd`. Should you need to store time alongside the date this can either be done separately (`time`) or in the same field (`date and time`). Please see our documentation on the Seedcase website for further information. |
```

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +| Date and Time  |  Also known as DateTime or Timestamp. The value will be stored as yyyy-mm-dd hh:mm:ss. If you only need to store a date then look at the Date data type, likewise if you need to onl
```suggestion
| Date and Time  | Also known as `datetime` or `timestamp`. The value will be stored as yyyy-mm-dd hh:mm:ss. If you only need to store a date then look at the Date data type, likewise if you need to only store a time then look at the data type Time.  Please see our documentation on the Seedcase website for further information.|
```

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +
```suggestion

<!-- TODO Add hyperlink to documentation when it's done -->

```

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +
```suggestion

<!-- TODO Add hyperlink to documentation when it's done -->

```

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +### Text
```suggestion
### Text

```

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +### Numbers
```suggestion
### Numbers

```

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +### Date and Time
```suggestion
### Date and Time

```

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +### True/False, Yes/No, Boolean
```suggestion
### True/False, Yes/No, Boolean

```

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +A standard data type in any system is the option of a boolean value, which can represent a set of either/or options. This could be yes/no or true/false, the values stored in the system will typically
```suggestion
A standard data type in any system is the option of a boolean value, which can represent a set of either/or options. This could be yes/no or true/false. The values stored in the system will typically be 0 and 1 (or -1 and 0) and the interpretation of these is up to the individual data user.
```
```suggestion
A standard data type in any system is the option of a boolean value, which can represent a set of either/or options. This could be yes/no or true/false, the values stored in the system will typically be 0 and 1 (or -1 and 0), the interpretation of these is up to the individual data user.
```

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +A standard data type in any system is the option of a boolean value, which can represent a set of either/or options. This could be yes/no or true/false, the values stored in the system will typically
Not sure what you mean with the notion of the interpretation being "up to the individual data user". Can you elaborate? :)

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +| True/False  | Also known as Yes/No or Boolean. This is the option to pick if you have data that falls into the either/or category, it will normally be stored as 0/1. Should you need to store the ac
```suggestion
| True/False  | Also known as `yes/no` or `boolean`. This is the option to pick if you have data that falls into the either/or category. It will normally be stored as 0/1. Should you need to store the actual words of 'Yes' and 'No', you should look at the data type `text`. Please see our documentation on the Seedcase website for further information. |
```

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +| True/False  | Also known as Yes/No or Boolean. This is the option to pick if you have data that falls into the either/or category, it will normally be stored as 0/1. Should you need to store the ac
```suggestion
| True/False  | Also known as Yes/No or Boolean. This is the option to pick if you have data that falls into the either/or category, it will normally be stored as 0/1 or True/False. Should you need to store the actual words of 'Yes' and 'No' then you should look at the data type Text. Please see our documentation on the Seedcase website for further information. |
```

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +### JSON
```suggestion
### JSON

```

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +### JSON
Are we including JSON as well? I thought we weren't?

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +JSON is a language for organizing and sharing data between computers. It is easy for both humans and computers to read, making it a popular choice for exchanging information on the internet. Many dat
```suggestion
JSON is a language for organizing and sharing data between computers. It is easy for both humans and computers to read, making it a popular choice for exchanging information on the internet. Many database systems offers a `JSON` data type which will to some extent check that the text being uploaded is formatted in the correct way. This will offer a user a way of doing data quality control during upload to the database, minimising problems later on.
```

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +| JSON | This is a specialised data type which will check that the JSON data is correctly formatted on upload. If you do not wish to have such a check carried out then chose Text as the data type, ev
```suggestion
| JSON | This is a specialised data type which will check that the JSON data is correctly formatted on upload. If you do not wish to have such a check carried out then choose `text` as the data type, even if you are uploading JSON data. Please see our documentation on the Seedcase website for further information. |
```

2024-01-24 14:52 UTC, signekb commented on docs/design/data-types.qmd
> +| JSON | This is a specialised data type which will check that the JSON data is correctly formatted on upload. If you do not wish to have such a check carried out then chose Text as the data type, ev
```suggestion
| JSON | This is a specialised data type which will check that the JSON data is correctly formatted on upload. If you do not wish to have such a check carried out then chose Text as the data type, even if you are uploading JSON data. Please see our documentation on the Seedcase website for further information. |

<!-- TODO Add hyperlink to documentation when it's done -->

```

2024-01-25 08:13 UTC, K-Beicher commented on docs/design/data-types.qmd
> +We will be using the Varchar without a limit at this point in time as Text is not a standard SQL type at present.
I think we can just cut the sentence after point in time.

2024-01-25 08:16 UTC, K-Beicher commented on docs/design/data-types.qmd
> +| Whole number   | Also known as Integer. This is a number field which will only allow whole numbers to be stored. Pick this option if you want to store whole numbers (like postcode, number of people
This is the text the user will see in Sprout.  I suspect they will understand Whole Number better than Integer, but I may be wrong.  I'm not sure that we should have ` in the text that is used in Sprout, will it render correctly in there?

2024-01-25 08:17 UTC, K-Beicher commented on docs/design/data-types.qmd
> +| Decimal number | Also known as Float or Double Precision. This is a number field which will store decimal numbers. Pick this option if you want to store things like lab results, or height in meters
So this is the text I wrote for Philip to put into Sprout, will `` render correctly in there?

2024-01-25 08:17 UTC, K-Beicher commented on docs/design/data-types.qmd
> +| Date  | The date value will be stored as yyyy-mm-dd, should you need to store time alongside the date this can either be done separately (Time) or in the same field, which would mean that you need
Will the `` render correctly in Sprout?

2024-01-25 08:19 UTC, K-Beicher commented on docs/design/data-types.qmd
> +A standard data type in any system is the option of a boolean value, which can represent a set of either/or options. This could be yes/no or true/false, the values stored in the system will typically
whether they use it as yes/no or true/false or missing/present.  I'm sure that we can find a better way to phrase it.

2024-01-26 09:52 UTC, signekb reviewed
Nice! Just one suggestion :)

2024-01-26 09:52 UTC, signekb commented on docs/design/data-types.qmd
> +We will be using the Varchar without a limit for Seedcase Sprout, in the application this will be called a Text field even though it is the name of a different data type.
```suggestion
We will be using `Varchar` without a limit for Seedcase Sprout. In the application this will be called a `Text` field.
```

2024-01-30 16:14 UTC, signekb submitted a review, later dismissed

2024-01-30 19:45 UTC, philter87 reviewed
Maybe we should postpone the JSON thing

2024-01-30 19:45 UTC, philter87 commented on docs/design/data-types.qmd
> +| JSON | This is a specialised data type which will check that the JSON data is correctly formatted on upload. If you do not wish to have such a check carried out then chose Text as the data type, ev
Currently, I am writing the function that derives the column types in a CSV file. I was trying to do JSON, but I realized that I have never seen json in csv column, and I even doubt that it is possible (well... maybe with semicolon as delimiter, but I think the csv parser will get confused)

I think we should postpone this. It might make more sense later, when we will support other upload formats

2024-02-01 09:11 UTC, philter87 approved these changes, later dismissed

2024-02-01 16:27 UTC, lwjohnst86 requested changes
Just adding some edits and revisions, not changing the content. I'll accept these and push up some further edits and small rearranging before approving and merging.

2024-02-01 17:57 UTC, lwjohnst86 approved these changes

2024-02-01 17:57 UTC, merged