Feat/review column data
seedcase-project/seedcase-sprout pull request #149
Opened 2024-02-09 12:46 UTC by K-Beicher

## Description

- This PR adds the view of the column meta data for Sprout.  It is bare bones for now, as @signekb and @philter87 are waiting for the code to work from.

## Related Issues

Closes #113 

See also Issues #...

## Testing

- [x] Yes
- [ ] No, not needed (give a reason below)
- [ ] No, I need help writing them

## Reviewer Focus

This PR requires an in-depth review.

First time adding to Django so would appreciate if everything is checked to see if code is placed in the correct files.

## Checklist

For all PRs that are not general documentation

- [ ] Tests accompany or reflect changes to the code
- [x] Tests ran and passed locally
- [ ] Ran the linter and formatter
- [x] Build has passed locally
- [ ] Relevant documentation has been updated

2024-02-26 11:13 UTC, philter87 approved these changes, later dismissed
Well done! Looks good!

2024-02-27 07:42 UTC, K-Beicher commented on sprout/forms.py
> +class ColumnDataTypeForm(ModelForm):
Done to the best of my ability, was there an init file somewhere that should also be sorted out?

2024-02-27 07:44 UTC, K-Beicher commented on sprout/tests/tests_views.py
> +        """Test that there is an error thrown when data entered is invalid."""
I should clearly learn more about what status codes do!  I've removed it.

2024-02-27 08:30 UTC, philter87 commented on sprout/tests/tests_views.py
> +        """Test that there is an error thrown when data entered is invalid."""
Yes, me too :) I never figured our why a redirect in one case gives 302 and in another gives 200

2024-02-28 10:36 UTC, philter87 commented
Okay, something unexpected happended. I stacked my PR "feat/upload-file-to-persistent-storage" on top of this one and then it automatically merged it into this branch (because it was no longer blocked by main-branch restrictions). So now this PR is huge. Sorry

2024-02-28 10:46 UTC, philter87 submitted a review, later dismissed

2024-02-28 12:15 UTC, signekb reviewed
Really nice work! Just have some suggestions and a couple of questions 👍

2024-02-28 12:15 UTC, signekb commented on sprout/tests/tests_views.py
> +        self.assertEqual(response.status_code, 200)
Should status_code be 200 both in this and the prior test (`test_column_review_view_get`)?

2024-02-28 12:15 UTC, signekb commented on sprout/tests/tests_models_file_metadata.py
> +        # And we change that the table is not deleted
```suggestion
        # And we check that the table has not been deleted
```

2024-02-28 12:15 UTC, signekb commented on sprout/tests/tests_models_file_metadata.py
not really reviewing this one here, since it's from @philter87's PR

2024-02-28 12:15 UTC, signekb commented on sprout/tests/tests_forms.py
> +class ColumnMetadataFormTest(TestCase):
Maybe we should separate the tests for forms so the script isn't so long? Into `tests_forms_columnmetadata` and `tests_forms_tablemetadata`?

2024-02-28 12:15 UTC, signekb commented on sprout/tests/tests_forms.py
> +    def test_form_instance_not_valid(self):
```suggestion
    def test_form_invalid_when_no_data(self):
```

2024-02-28 12:15 UTC, signekb commented on sprout/tests/tests_forms.py
> +    def test_form_validation_valid_data(self):
```suggestion
    def test_form_valid_data(self):
```

2024-02-28 12:15 UTC, signekb commented on sprout/tests/tests_forms.py
> +    def test_form_validation_invalid_data(self):
```suggestion
    def test_form_invalid_data(self):
```

2024-02-28 12:15 UTC, signekb commented on sprout/views/column_review.py
> +
```suggestion
        request: _description_
        table_name: _description_
        
```
Remove ` (_type_)` from docstrings in general :)

2024-02-28 12:15 UTC, signekb commented on sprout/views/column_review.py
> +            print([form.errors for form in forms])
Maybe remove this `print` statement?  This will just be printed to the terminal, right? And not really shown anywhere else?
Maybe it's a leftover from testing?

2024-02-28 12:15 UTC, signekb commented on sprout/templates/column-review.html
> +        <td style="overflow: hidden;">{{ form.data_type }}</td>
It seems that there's an option to select `----` in the dropdown. Can this be removed?

![image](https://github.com/seedcase-project/seedcase-sprout/assets/40836345/0c41e408-6deb-4dfa-8b3f-a1133cc011b3)

2024-02-28 12:20 UTC, K-Beicher commented on sprout/forms.py
> +    class Meta:  # noqa: D106
I'm honestly not sure, over to @lwjohnst86

2024-02-28 12:25 UTC, K-Beicher commented on sprout/templates/column-review.html
> +      {% for form in forms %}
I tried so many versions in order for it to write edits back that I'm honestly not sure.  I stopped once I had a version that worked in the way it is supposed to.  Happy to experiment

2024-02-28 12:26 UTC, K-Beicher commented on sprout/templates/column-review.html
> +        <td style="overflow: hidden;">{{ form.data_type }}</td>
I'm honestly not sure, I can try.

2024-02-28 12:30 UTC, K-Beicher commented on sprout/tests/tests_forms.py
> +class ColumnMetadataFormTest(TestCase):
good idea

2024-02-28 12:36 UTC, K-Beicher commented on sprout/templates/column-review.html
> +        <th>Name</th>
Yes - I would like to wait with the change from ID to original name, as I suspect it's going to be a bit of a job to add a non-editable field to a table where everything else can be edited...

2024-02-28 12:39 UTC, K-Beicher commented on sprout/templates/column-review.html
> +        <input type="hidden" name="{{ form.prefix }}-id" value="{{ form.instance.id }}">
The bit I finally got ChatGPT to enter in order for the data to be saved correctly back to each individual row.  The first two days it saved the data from the last row into each row for a given table.

2024-02-28 12:53 UTC, lwjohnst86 requested changes
Some small changes, and mostly agree with @signekb comments.

2024-02-28 12:53 UTC, lwjohnst86 commented on sprout/forms.py
> +    class Meta:  # noqa: D106
We haven't decided yet. We decided not to use docstrings for tests.

2024-02-28 12:53 UTC, lwjohnst86 commented on sprout/tests/tests_forms.py
> +    def setUp(self):
```suggestion
    def setup(self):
```

2024-02-28 12:53 UTC, lwjohnst86 commented on sprout/views/column_review.py
> +"""File with column_review view."""
Yes agreed. I think we can remove them from Ruff linter.

2024-02-28 12:53 UTC, lwjohnst86 commented on sprout/views/column_review.py
> +    The table can be edited and the result written back to the db
```suggestion
    The table can be edited and the result written back to the database.
```

2024-02-28 14:04 UTC, K-Beicher commented on sprout/models/column_data_type.py
> +    def __str__(self):  # noqa: D105
Will do

2024-02-29 08:05 UTC, K-Beicher commented on sprout/templates/column-review.html
> +        <td style="overflow: hidden;">{{ form.data_type }}</td>
I've added a bug issue to Sprout on this

2024-02-29 08:08 UTC, K-Beicher commented on sprout/views/column_review.py
> +            return redirect(reverse("column-review", args=[table_id]))
I've added it as an issue

2024-02-29 13:44 UTC, lwjohnst86 approved these changes
🎉

2024-02-29 13:44 UTC, merged

2024-02-29 13:47 UTC, signekb commented on sprout/forms.py
> +    class Meta:  # noqa: D106
@lwjohnst86 So a docstring should be added here?