feat: read csv file with polars
seedcase-project/seedcase-sprout pull request #154
Opened 2024-02-12 10:18 UTC by philter87

## Description

The third attempt to read and derive csv column types. I have implemented a method 'read_csv_file' which builds upon "polars.read_csv". The polars.read_csv is missing a few features, which I have implemented:
- A series with only 0 and 1 should be converted to a boolean series.
- A series with boolean-ish values ("Yes", "No") should be converted to a boolean series
- The polars.read_csv is unable to parse some CSV dialects, so the csv content is converted to a certain dialect before it is passed to polars.read_csv. This could possibly

- This PR adds a feature to read csv file and derive columns

## Related Issues

Closes #123

## Testing

- [X] Yes
- [ ] No, not needed (give a reason below)
- [ ] No, I need help writing them

## Reviewer Focus
This PR requires an in-depth review.

- Should we support the boolean-ish values like "Yes" and "No"? Or should I remove it?
- polars.read_csv is unable to parse certain date formats automatically: e.g. "12. Jan 2024". Is this okay?
- The memory consumption is high, because we need to convert to a different CSV format and keep the converted format in memory. Alternative is to store in a temporary file and then delete afterwards

## Checklist

For all PRs that are not general documentation

- [X] Tests accompany or reflect changes to the code
- [X] Tests ran and passed locally
- [X] Ran the linter and formatter
- [X] Build has passed locally
- [X] Relevant documentation has been updated

2024-02-14 20:41 UTC, lwjohnst86 requested changes
Looks great! Just some small suggested changes, mostly formatting and things to look into in the future. But wonderful 🎉 🥳

2024-02-14 20:41 UTC, lwjohnst86 commented on app/tests/tests_csv_reader.py
> +"""File with tests for csv_read_file()."""
```suggestion
"""File with tests for `csv_read_file()`."""
```

2024-02-14 20:41 UTC, lwjohnst86 commented on app/tests/tests_csv_reader.py
> +        NOTICE: d3 (ex: '27. Oct 1987') is not recognized as date
Yea, I think we'll have to figure out how to solve that problem, because there are dozens of ways people enter date data and we should be able to parse that.

2024-02-14 20:41 UTC, lwjohnst86 commented on app/tests/tests_csv_reader.py
> +        """A method test expected_types in a DataFrame object.
```suggestion
        """A method test `expected_types` in a DataFrame object.
```

2024-02-15 08:42 UTC, philter87 commented on app/csv_reader.py
> +def read_csv_file(csv_file: TextIO, row_number: int = 1000) -> DataFrame:
This will mainly be a problem when we need to validate or parse the entire file, but there are other solutions. Either we will divide the file in chunks or we can create a temporary file to store the data (instead of in-memory)

2024-02-15 08:54 UTC, philter87 commented on app/csv_reader.py
> +    for column in df.columns:
Valid point! Very observant!

And this was my initial implementation (provided by chatgpt), but I thought the implementation with selectors is less readable (even though it is short):

df = df.select([_convert_to_booleans(df[col]) for col in df.columns])

What do you think @signekb @K-Beicher?

2024-02-15 09:02 UTC, philter87 commented on app/csv_reader.py
> +    for column in df.columns:
Nevermind, I will just implement it with selectors

2024-02-15 09:20 UTC, philter87 commented on app/tests/tests_csv_reader.py
> +        NOTICE: d3 (ex: '27. Oct 1987') is not recognized as date
Should I try to fix in this PR?

2024-02-16 12:13 UTC, signekb requested changes
Looks good! Mainly have some suggestions/edits for docstrings :)

2024-02-16 12:13 UTC, signekb commented on app/csv_reader.py
> +def _convert_to_booleans_if_possible(series: Series) -> Series:
Is it necessary to actually convert the column to booleans when we only want to extract the column metadata and not load the file itself at this point?

2024-02-16 12:29 UTC, philter87 commented on app/csv_reader.py
> +        csv_content = csv_content + ";".join(line) + "\n"
In this context I prioritized readability, but yes the code is not very efficient. And the memory consumption is an even bigger problem

2024-02-16 12:42 UTC, philter87 commented on app/csv_reader.py
> +def _convert_to_booleans_if_possible(series: Series) -> Series:
My plan is to use the dtypes on the returned DataFrame to create the ColumnMetaData objects, but I could have just returned a dictionary of the column-to-type mapping instead of the DataFrame.

Furthermore, I hope that read_csv_file will be used for validation (and etc) as well, but lets see if it is possible.

2024-02-16 13:20 UTC, signekb commented on app/csv_reader.py
> +def _convert_to_booleans_if_possible(series: Series) -> Series:
Ahhhh, I see! Lets just keep it then :)

2024-02-16 13:23 UTC, signekb commented on app/csv_reader.py
Oh, sorry! The types shouldn't be added. I made this edit before my docstring deep dive yesterday and forgot to delete them again. Sorry!
Same for L77 and L96+97

2024-02-16 18:14 UTC, lwjohnst86 approved these changes
Wooohooo!! 🎉

2024-02-16 18:15 UTC, merged

2024-02-16 19:05 UTC, lwjohnst86 commented on app/csv_reader.py
> +        csv_content = csv_content + ";".join(line) + "\n"
I also tend to avoid using loops for similar reasons @signekb. One solution could be to detect the dialect and change the `separator` argument in the `read_csv()` to use the dialect there, rather than change the whole file itself. I also found the `scan_csv()` which might be useful for these purposes.

2024-02-19 10:42 UTC, philter87 commented on app/csv_reader.py
> +        csv_content = csv_content + ";".join(line) + "\n"
I also tried, but failed because there is more to a dialect. You can read more in the issue you created: #187