Feat/column data type polars types
seedcase-project/seedcase-sprout pull request #185
Opened 2024-02-16 14:35 UTC by philter87

## Description

- This PR adds polars_types to ColumnDataType. We need a mapping between the polars types and "Sprout" types as we use polars.read_csv to find the data types of the CSV columns. I am creating this small PR to avoid a big PR. 
- The method 'ColumnDataType.get_from_series()' returns a ColumnDataType based on the series.dtype

## Related Issues

See also Issues #184

## Testing

- [X] Yes
- [ ] No, not needed (give a reason below)
- [ ] No, I need help writing them

## Reviewer Focus
This PR only needs a quick review.

## Checklist

For all PRs that are not general documentation

- [X] Tests accompany or reflect changes to the code
- [X] Tests ran and passed locally
- [X] Ran the linter and formatter
- [X] Build has passed locally
- [X] Relevant documentation has been updated

2024-02-20 02:53 UTC, lwjohnst86 requested changes
Love it! 😁  I only have a small suggestion to the text, since it seems like an incomplete sentence, but I wasn't sure.

2024-02-20 02:53 UTC, lwjohnst86 commented on app/models/column_data_type.py
> +            series: The polars.Series to find ColumnDataType from
```suggestion
            series: The polars.Series to find the  ColumnDataType from
```

2024-02-22 06:55 UTC, K-Beicher approved these changes, later dismissed
Not that I'm understanding everything, but it looks good from what I can see.

2024-02-23 13:00 UTC, K-Beicher submitted a review, later dismissed
Looks good

2024-02-26 15:53 UTC, lwjohnst86 approved these changes
Neat!! Only thing I wonder about, though it is low priority, is the use of the for loop (still intuitively don't love them), the use of `@staticmethod`. But otherwise, great!

2024-02-27 09:36 UTC, K-Beicher approved these changes
Cool

2024-02-27 09:36 UTC, merged

2024-02-27 09:52 UTC, signekb approved these changes
Nice 👍