Feat/file download example
seedcase-project/seedcase-sprout pull request #200
Opened 2024-02-26 12:58 UTC by philter87

## Description

Simple example of how to download a file

- This PR adds the possible to download a file for a given table

## Related Issues

Closes #...

See also Issues #160 

## Testing

- [ ] Yes
- [X] No, not needed (give a reason below)
- [ ] No, I need help writing them

This is just an example of how to download files from the server

## Reviewer Focus

This PR only needs a quick review.
This PR requires an in-depth review.

## Checklist

For all PRs that are not general documentation

- [ ] Tests accompany or reflect changes to the code
- [ ] Tests ran and passed locally
- [ ] Ran the linter and formatter
- [ ] Build has passed locally
- [ ] Relevant documentation has been updated

For general documentation:

- [ ] Spell-check
    - [ ] US
    - [ ] UK
- [ ] Did the page(s) preview correctly on your machine without breaking
- [ ] New category words (keywords) (if any) added to the code snippet file

2024-03-05 08:15 UTC, K-Beicher submitted a review, later dismissed
Looks good

2024-03-07 09:47 UTC, lwjohnst86 requested changes
Only a small edit fix. Very neat! Not sure if we should provide a way to download files, but being able to view what files are stored might be useful, so I am fine keeping this as is for now. How might they get to this page though?

2024-03-07 09:47 UTC, lwjohnst86 commented on sprout/templates/table-files.html
> +  <p>Here you can view and download the files relevant for a certain table.</p>
```suggestion
  <p>Here you can view and download the files relevant for this table.</p>
```

2024-03-07 09:47 UTC, lwjohnst86 commented on sprout/tests/tests_views_table_files.py
> +        file.name = "file.csv"
any particular reason this uses the `.` in the name? Or you are setting the `name` property of `file` to be `file.csv`?

2024-03-07 09:47 UTC, lwjohnst86 commented on sprout/views/table_files.py
> +    print(file_metadata.server_file_path)
Should this print statement be here?

2024-03-07 10:20 UTC, philter87 commented on sprout/views/table_files.py
> +    print(file_metadata.server_file_path)
No, thanks :)

2024-03-07 10:22 UTC, philter87 commented on sprout/tests/tests_views_table_files.py
> +        file.name = "file.csv"
It is the file name, and I am expected a file name with an extension. Is it wrong to assume an extension to a file? In the upload view, I am also enforcing a ".csv" extension

2024-03-07 11:22 UTC, philter87 commented
> Only a small edit fix. Very neat! Not sure if we should provide a way to download files, but being able to view what files are stored might be useful, so I am fine keeping this as is for now. How might they get to this page though?

I thought it could be part of 2.1 (figma view 2.1) or the expanded view (figma view 2.2)

And the idea was also to illustrate a simple version of seedcase, where people "just" share CSVs (and maybe validated parquet files with the potential of converting to CSVs on the fly). 

But it seems we are heading towards storing the data in a database, and then the download part is less useful.

2024-03-10 19:17 UTC, lwjohnst86 commented on sprout/tests/tests_views_table_files.py
> +        file.name = "file.csv"
No, not at all. I didn't understand what the `.` did in the `file.name`, but I understand now ☺️

2024-03-10 19:17 UTC, merged