DRAFT feat: read_csv uses file path and ColumnMetaData created
seedcase-project/seedcase-sprout pull request #207
Opened 2024-02-28 19:41 UTC by philter87

## Description

- This PR {removes/adds/fixes/replaces} the {feature/bug/issue/documentation/tests}.
- These changes are done because of ... {reasons for change/why you're doing it}.

## Related Issues

Closes #...

See also Issues #...

## Testing

- [ ] Yes
- [ ] No, not needed (give a reason below)
- [ ] No, I need help writing them

## Reviewer Focus

This PR only needs a quick review.
This PR requires an in-depth review.

## Checklist

For all PRs that are not general documentation

- [ ] Tests accompany or reflect changes to the code
- [ ] Tests ran and passed locally
- [ ] Ran the linter and formatter
- [ ] Build has passed locally
- [ ] Relevant documentation has been updated

For general documentation:

- [ ] Spell-check
    - [ ] US
    - [ ] UK
- [ ] Did the page(s) preview correctly on your machine without breaking
- [ ] New category words (keywords) (if any) added to the code snippet file

2024-03-01 10:04 UTC, signekb reviewed
Nice! 
When I run it locally, it get the error `django.db.utils.OperationalError: table sprout_filemetadata has no column named created_by_id` after I upload a test.csv?

2024-03-01 14:14 UTC, signekb commented on sprout/tests/tests_views.py
Makes sense. I'll make a PR with that 👍

2024-03-05 08:18 UTC, K-Beicher approved these changes, later dismissed
Looks like it's been tidied.

Just curious, why has it changed the csv_reader.py from a tidy version to a less tidy one?

2024-03-05 08:38 UTC, philter87 commented
> Looks like it's been tidied.
> 
> Just curious, why has it changed the csv_reader.py from a tidy version to a less tidy one?

I am not sure I understand, so now I might say a lot of random things. The polars.read_csv only understands certain CSV formats, so I am trying to transform to a suitable format. 

The transformation was done with a for-loop before, but now it is done in a "polars-way". I think this is faster

I also changed from a file object to using file paths. File objects might require a lot of memory (if everything is moved to memory), so it is better to use disk space

2024-03-05 08:38 UTC, philter87 commented
> Nice! When I run it locally, it get the error `django.db.utils.OperationalError: table sprout_filemetadata has no column named created_by_id` after I upload a test.csv?

It should work now

2024-03-06 14:51 UTC, lwjohnst86 requested changes
I like the polars-way change! Only a small change.

2024-03-06 14:51 UTC, lwjohnst86 commented on sprout/csv_reader.py
> +    df.write_csv(cleaned_path)
Niiiiccceee, love it!

2024-03-06 14:51 UTC, lwjohnst86 commented on sprout/views/file_upload.py
> +        raise StopUpload("Unable to extract column types. No rows where found")
```suggestion
        raise StopUpload("Unable to extract column types. No rows were found.")
```

2024-03-06 15:09 UTC, philter87 reviewed
Spelling mistake fixed

2024-03-07 09:21 UTC, lwjohnst86 approved these changes

2024-03-07 09:23 UTC, merged