feat: create review list view
seedcase-project/seedcase-sprout pull request #235
Opened 2024-03-05 13:11 UTC by K-Beicher

## Description

- This PR {removes/adds/fixes/replaces} the {feature/bug/issue/documentation/tests}.
- These changes are done because of ... {reasons for change/why you're doing it}.

## Related Issues

Closes #...

See also Issues #...

## Testing

- [ ] Yes
- [ ] No, not needed (give a reason below)
- [ ] No, I need help writing them

## Reviewer Focus

This PR only needs a quick review.
This PR requires an in-depth review.

## Checklist

For all PRs that are not general documentation

- [ ] Tests accompany or reflect changes to the code
- [ ] Tests ran and passed locally
- [ ] Ran the linter and formatter
- [ ] Build has passed locally
- [ ] Relevant documentation has been updated

For general documentation:

- [ ] Spell-check
    - [ ] US
    - [ ] UK
- [ ] Did the page(s) preview correctly on your machine without breaking
- [ ] New category words (keywords) (if any) added to the code snippet file

2024-03-11 09:58 UTC, K-Beicher commented
@lwjohnst86, @philter87 am I right in thinking that because this is branched off another branch it won't run tests and doesn't require reviews until the first branch is merged in?

2024-03-11 10:13 UTC, lwjohnst86 commented
@K-Beicher that's correct 😁

2024-03-11 12:22 UTC, philter87 requested changes
Nice!

I just added a picture for the next one reviewing:
![image](https://github.com/seedcase-project/seedcase-sprout/assets/5868902/ff0f3302-32de-4bd0-8943-9dc38a972650)

2024-03-11 12:22 UTC, philter87 commented on sprout/urls.py
> +        name="column-review-list",
I think ")" is missing in `path(...)`. Maybe you forgot to commit some code

2024-03-13 07:24 UTC, philter87 approved these changes

2024-03-13 07:24 UTC, merged