Feat/user flow: Diagrams and post on user flow in Sprout
seedcase-project/seedcase-sprout pull request #27
Opened 2023-12-18 08:14 UTC by signekb

Please review the user flow post and the accompanying diagrams. 
These have been created based on the event storming sessions in W43 as well as talks with @K-Beicher  and @henrik-goul. 

This is meant as a first draft of concretising Sprout and what this part of Seedcase will cover, so I'm looking very much forward to your reviews :) 

Note: I have diverged from our branch strategy (GitHub Flow) by making this branch based on another feature branch, `feat/sprout-v1-diagrams`, (I made the sequence diagrams on) in an attempt to keep this PR simpler for faster reviews 🌷

2023-12-18 08:26 UTC, K-Beicher commented on docs/design/images/user-flow-2-validation-schema-completeness.puml
> +    and s:System shows UI with schema for user to edit,
s: is that a typo of wayward code?

2023-12-18 09:26 UTC, signekb commented
Something we could/maybe should add to this is which user roles that can do what?

2023-12-18 11:35 UTC, lwjohnst86 requested changes
Really great job you two on mapping this out! I've left several comments and suggested changes. I think it describes the flow very well!!! :clinking_glasses: :raised_hands: :tada:

2023-12-18 11:35 UTC, lwjohnst86 commented on docs/design/user-flow.qmd
> +|schema |table | column-name | description | data-type | is-nullable | title (optional)
I changed this table to use more descriptive names, `snake_case` for variables, and backticks for formatting.

2023-12-18 11:35 UTC, lwjohnst86 commented on docs/design/user-flow.qmd
> +When the user is satisfied with their adaptions, they click "Save and Submit Schema". The schema will then go through the validation check, "Schema Completeness" again and if the validation is succes
```suggestion
When the user is satisfied with their adaptions, they click "Save and Submit Schema". The schema will then go through the validation check, "Schema Completeness" again and if the validation is successful, Sprout will confirm: "New Schema Added Successfully".
```

2023-12-18 11:35 UTC, lwjohnst86 commented on docs/design/user-flow.qmd
> +After these steps, Sprout will initialise the data upload. This initialisation includes a validation check, *Schema and Data Match*, as seen in the dragram below. At this step,Sprout checks whether t
```suggestion
After these steps, Sprout will initialise the data upload. This initialisation includes a validation check, *Schema and Data Match*, as seen in the diagram below. At this step, Sprout checks whether the data and schema match. If this validation fails, Sprout will show "Validation Failed" along with error messages where the system detects that the data does not match the schema. 
```

2023-12-18 11:35 UTC, lwjohnst86 commented on docs/design/user-flow.qmd
> +The aim here is to show the users as meaningful and helpful error messages as possible. These messages should enable the user to go to their raw data and edit them to attempt to fix the errors. This
```suggestion
The aim here is to show the users error messages that are as meaningful and helpful as possible. These messages should enable the user to go to their raw data and edit them to attempt to fix the errors. This step is, naturally, outside of Sprout (therefore, marked in blue in the diagram below). The user will then click "Upload Edited/New Version of File" and Sprout will show a user interface, where the user can add the new version of the file. When the user has selected the file and clicks "Upload File", the validation check runs again. 
```

2023-12-18 11:35 UTC, lwjohnst86 commented on docs/design/user-flow.qmd
> +:::
```suggestion
<!-- TODO: Update full user flow diagram to include all the other diagrams after review -->
```

2023-12-18 11:35 UTC, lwjohnst86 commented on docs/design/images/user-flow-1-schema-creation.puml
I'm not sure I understand the numbering of these files. Are they necessary/relevant? The names are all different, so the number doesn't seem necessary.

2023-12-18 11:35 UTC, lwjohnst86 commented on docs/design/images/user-flow-1-schema-creation.puml
> +case (V2: Create Schema from\nExisting Schema)
```suggestion
case (Create Schema from\nExisting Schema)
```

Adding version number isn't necessary at this point, that is for us to decide during iterations. Plus, "V2" word will quickly go out of date (since we will be likely using a SemVar style of versioning (`##.##.##`).

2023-12-18 11:35 UTC, lwjohnst86 commented on docs/design/images/user-flow-1-schema-creation.puml
> +case (V3+: Create Schema Manually)
```suggestion
case (Create Schema Manually)
```

2023-12-18 11:35 UTC, lwjohnst86 commented on docs/design/images/user-flow-1-schema-creation.puml
I'm also not sure I understand the colour filling choices. Why are some filled in and others aren't? If they are for things we will build sooner than later, like my previous comments, let's not go that route since the design docs are to show "what we will build and how it will look", not "what is our next plan"... since maintaining docs that are "next plan" will be ... a lot of work. Assume all design docs are (evolving) blueprints (not a roadmap).

2023-12-18 11:35 UTC, lwjohnst86 commented on docs/design/images/user-flow-1-schema-creation.puml
> +'Data vs file: File indicates only a single file (e.g., csv) can be uploaded at a time. Is that what we want?
```suggestion
```

Moving this comment out to here. Good question... I don't see why we couldn't upload multiple files that are each scanned and create multiple schemas from them. Maybe for now we assume multiple (without explicitly saying it here?).

2023-12-18 11:35 UTC, lwjohnst86 commented on docs/design/images/user-flow-1-schema-creation.puml
> +'That could be very annoying for researchers with one file per participant (per visit)
```suggestion
```

2023-12-18 11:35 UTC, lwjohnst86 commented on docs/design/images/user-flow-1-schema-creation.puml
> +  headers and definitions*;
What's the `*` for?

2023-12-18 11:35 UTC, lwjohnst86 commented on docs/design/images/user-flow-2-validation-schema-completeness.puml
> +    if (V2: System asks user if they want to save only or submit) then (V2: Save only)
```suggestion
    if (System asks user if they want to save only or submit) then (Save only)
```

2023-12-18 11:35 UTC, lwjohnst86 commented on docs/design/images/user-flow-2-validation-schema-completeness.puml
> +    - data type (dropdown?)
```suggestion
    - data type (dropdown)
```

2023-12-18 11:35 UTC, lwjohnst86 commented on docs/design/images/user-flow-2-validation-schema-completeness.puml
> +    - data type (dropdown?)
```suggestion
    - data type (dropdown)
```

2023-12-18 11:35 UTC, lwjohnst86 commented on docs/design/images/user-flow-2-validation-schema-completeness.puml
> +    including:
```suggestion
    :System shows UI with schema for 
    user to edit, including: 
```

2023-12-18 11:35 UTC, lwjohnst86 commented on docs/design/images/user-flow-2-validation-schema-completeness.puml
> +    including:
```suggestion
    and shows UI with schema for 
    user to edit, including: 
```

2023-12-18 11:35 UTC, lwjohnst86 commented on docs/design/images/user-flow-2-validation-schema-completeness.puml
> +    System goes back to VALIDATION CHECK: Schema Completeness;
Ah, that's what you were frustrated with... Yea, that's weird... there's got to be a way to fix that. Could it end at "Restart with uploading validation check?"

2023-12-18 11:35 UTC, lwjohnst86 commented on docs/design/images/user-flow-3-schema-created-continue-to-upload.puml
> +#palegreen:Systems confirms: "New Schema added Successfully";
```suggestion
#palegreen:System confirms: "New Schema added Successfully";
```

2023-12-18 11:35 UTC, lwjohnst86 commented on docs/design/images/user-flow-4-prepare-to-upload-using-existing-schema.puml
> +'That could be very annoying for researchers with one file per participant (per visit)
```suggestion
```
See comment above about this.

2023-12-18 11:35 UTC, lwjohnst86 commented on docs/design/images/user-flow-5-data-upload.puml
> +while (\nVALIDATION CHECK: Schema and data match\nSystem checks if data and schema matches\n) is (Validation failed)
```suggestion
:System initialises data upload;
while (\nVALIDATION CHECK: Check if Schema and data match\n) is (Validation failed)
```

2023-12-18 11:35 UTC, lwjohnst86 commented on docs/design/images/user-flow-5-data-upload.puml
> +:Systems shows "Upload failed" along\nwith description on where data and\nschema do not match;
```suggestion
:Systems shows "Upload Failed" along\nwith description on where data and\nschema do not match;
```

2023-12-18 11:58 UTC, signekb commented on docs/design/user-flow.qmd
> +|schema |table | column-name | description | data-type | is-nullable | title (optional)
Alrighty! So our naming convention is kebab-case for file names and snake_case for variables?

2023-12-18 12:03 UTC, K-Beicher commented on docs/design/images/user-flow-1-schema-creation.puml
The numbers denotes the flow of the files, otherwise they won't come in the correct order.  

The colour filling is a work in progress, we decided to include the V2 stuff just to make sure that we don't have people going 'but there are two things we could do here'. We could probably do a version where we just have what we are building this time, but keep these for the overall overview.

2023-12-18 12:06 UTC, K-Beicher commented on docs/design/images/user-flow-1-schema-creation.puml
> +'Data vs file: File indicates only a single file (e.g., csv) can be uploaded at a time. Is that what we want?
I don't think I've ever seen a system which allowed for multiple files to be uploaded at the same time if they require the level of validation that we suggest will take place.  Also, can you imagine the hassle of attaching several files just to have to do it again because one of them failed.  We may want to add this as a discussion item to one of our meetings.

2023-12-18 12:07 UTC, K-Beicher commented on docs/design/images/user-flow-1-schema-creation.puml
> +  headers and definitions*;
There is a footnote in the full overview which explains what the 'definitions' cover.  The footnote should be brought over, we are aware of this.

2023-12-18 12:09 UTC, K-Beicher commented on docs/design/images/user-flow-2-validation-schema-completeness.puml
> +    System goes back to VALIDATION CHECK: Schema Completeness;
We've posted it to the Forums on plantUML, we'll see if anyone gets back to us, otherwise that is an option.

2023-12-18 13:13 UTC, signekb commented on docs/design/user-flow.qmd
> +:::
Duly noted. I'll remove it here and add it to the PR

2023-12-18 13:27 UTC, signekb commented on docs/design/images/user-flow-1-schema-creation.puml
@lwjohnst86 The numbering isn't strictly necessary, but it is the order they are presented in the post. It was just to make it easier for me and my tired brain to add them at the right places. I can remove the numbering. 
Yes, we implemented white backgrounds for V2 implementations to make it clear(er) (to you too) that we do not think this should be a part of the initial version of Sprout that we will aim to build during the next iteration.

2023-12-18 13:28 UTC, signekb commented on docs/design/images/user-flow-1-schema-creation.puml
> +'Data vs file: File indicates only a single file (e.g., csv) can be uploaded at a time. Is that what we want?
I'll create an issue on it 👍

2023-12-18 13:41 UTC, signekb commented on docs/design/images/user-flow-2-validation-schema-completeness.puml
> +    and s:System shows UI with schema for user to edit,
Typo. Thanks!

2023-12-18 14:22 UTC, signekb commented on docs/design/images/user-flow-1-schema-creation.puml
> +  headers and definitions*;
I have moved the footnote so it's in the diagram as well.

2023-12-18 14:25 UTC, signekb commented on docs/design/images/user-flow-1-schema-creation.puml
I'll remove the numbering of the files and the later version colouring :+1:

2023-12-19 12:39 UTC, K-Beicher commented on docs/design/images/user-flow-5-data-upload.puml
> +#palegreen:System displays confirmation: "Upload Successful";
We should probably have a couple of boxes more here.  One to say that the system displays back to the user the number of rows it intends to write to the database, with an option to abort if the number isn't what they expected and another with upload successful.

So something like this between the last two lines of code:
while (System displays the number of \nsuccessfully validated rows \nto the user for agreement) is (No)
:User clicks "Cancel Upload";
end
end while (Yes);

2023-12-19 13:18 UTC, signekb commented on docs/design/images/user-flow-2-validation-schema-completeness.puml
> +    System goes back to VALIDATION CHECK: Schema Completeness;
We've got a response, with a not so pretty but better, workaround. I have implemented that now 🎉

2023-12-21 07:45 UTC, signekb commented
@lwjohnst86 I believe that I have implemented the changes you suggested, but because I did it through VS Code, it seems like GitHub hasn't "recorded" it?

2024-01-03 12:27 UTC, lwjohnst86 approved these changes

2024-01-03 12:27 UTC, lwjohnst86 commented on docs/design/user-flow.qmd
> +This document describes the user flow of Sprout. The user flow is split into five diagrams that go through the flow in more detail. At the end of the post, you can see the user flow of Sprout in its
```suggestion
This document describes the user flow of Sprout. The user flow is split into five diagrams that go through the flow in more detail. At the end of the document, you can see the user flow of Sprout in its entirety.
```

2024-01-03 12:27 UTC, lwjohnst86 commented on docs/design/user-flow.qmd
> +: Example of schema named `data resource` with one table `table_1` with user information
```suggestion
: Example of schema named `data resource` with one table `table_1` with user information.
```

2024-01-03 12:27 UTC, lwjohnst86 commented on docs/design/user-flow.qmd
> +![](images/user-flow-schema-creation.png)
```suggestion
![Diagram of the flow that occurs when a new schema is created.](images/user-flow-schema-creation.png)
```

2024-01-03 12:27 UTC, lwjohnst86 commented on docs/design/user-flow.qmd
> +![](images/user-flow-schema-created-continue-to-upload.png)
```suggestion
![Diagram describing the next steps given after creating the schema and passing the validation steps.](images/user-flow-schema-created-continue-to-upload.png)
```

2024-01-03 12:27 UTC, lwjohnst86 commented on docs/design/user-flow.qmd
> +![](images/user-flow-prepare-to-upload-using-existing-schema.png)
```suggestion
![Diagram showing the steps taken for uploading data when using an existing schema.](images/user-flow-prepare-to-upload-using-existing-schema.png)
```

2024-01-03 12:27 UTC, lwjohnst86 commented on docs/design/user-flow.qmd
> +![](images/user-flow-data-upload.png)
```suggestion
![Diagram showing the steps that occur after validation and final data upload from a Data Contributor.](images/user-flow-data-upload.png)
```

2024-01-03 12:27 UTC, lwjohnst86 commented on docs/design/user-flow.qmd
> +![](images/user-flow.png)
```suggestion
![Diagram showing the full flow from user inputting data into it finally being stored in the database.](images/user-flow.png)
```

2024-01-03 12:28 UTC, lwjohnst86 commented
Looks fabulous!

2024-01-03 12:28 UTC, merged