Feat/existing table view
seedcase-project/seedcase-sprout pull request #300
Opened 2024-03-18 13:26 UTC by signekb

## Description

- This PR {removes/adds/fixes/replaces} the {feature/bug/issue/documentation/tests}.
- These changes are done because of ... {reasons for change/why you're doing it}.

## Related Issues

Closes #162

See also Issues #...

## Testing

- [ ] Yes
- [ ] No, not needed (give a reason below)
- [ ] No, I need help writing them

## Reviewer Focus

This PR requires an in-depth review.

## Checklist

For all PRs that are not general documentation

- [ ] Tests accompany or reflect changes to the code
- [ ] Tests ran and passed locally
- [ ] Ran the linter and formatter
- [ ] Build has passed locally
- [ ] Relevant documentation has been updated

For general documentation:

- [ ] Spell-check
    - [ ] US
    - [ ] UK
- [ ] Did the page(s) preview correctly on your machine without breaking
- [ ] New category words (keywords) (if any) added to the code snippet file

2024-03-20 14:12 UTC, signekb commented
@lwjohnst86 How do I update the active deployment? It's outdated? :)

2024-03-20 14:37 UTC, lwjohnst86 commented
@signekb it seems to have built now. Or is it outdated still?

2024-03-21 07:47 UTC, signekb commented
@lwjohnst86 Ah, maybe I was just too impatient

2024-03-25 12:46 UTC, philter87 reviewed
Great work! 
Only one 'big' thing. I was confused about 'view-existing-tables.html'

2024-03-25 12:46 UTC, philter87 commented on sprout/templates/project-id-metadata-view.html
> +<style>
Nice! I assumed that styles had to be in a different file (but that was just silly of me). I will need to redo some templates

2024-03-25 12:46 UTC, philter87 commented on sprout/templates/project-id-metadata-view.html
> +  .selectable:hover {
Nice with the hover effect!

2024-03-25 12:46 UTC, philter87 commented on sprout/templates/project-id-metadata-view.html
> +    <button type="submit" name="button_edit"><i>edit</i>Edit Metadata</button>
Potentially you could add the disabled attribute to the buttons based on the query parameter
```
<nav class="right-align">
  <button {% if not request.GET.selected_metadata_id %}disabled{% endif %} type="submit" name="button_create"><i>add</i>Create Metadata</button>
  <button {% if not request.GET.selected_metadata_id %}disabled{% endif %} type="submit" name="button_edit"><i>edit</i>Edit Metadata</button>
  <button type="submit" name="button_upload"><i>upload</i>Upload Data</button>
</nav>
```

![image](https://github.com/seedcase-project/seedcase-sprout/assets/5868902/1ce73b1c-245c-40e0-ac0b-6c1ff63c2de6)

But the dialog gives a bit more information. 

What do you think @lwjohnst86

2024-03-25 12:46 UTC, philter87 commented on sprout/templates/view-existing-tables.html
Should this file be deleted? Maybe a result of a rename or is it a different version you want to preserve?

2024-03-26 11:30 UTC, philter87 approved these changes, later dismissed
Looks good now :)

2024-03-26 13:07 UTC, signekb commented on sprout/templates/project-id-metadata-view.html
> +    <button type="submit" name="button_edit"><i>edit</i>Edit Metadata</button>
I actually like your version better, @philter87. I'll change it 👍

2024-03-26 14:22 UTC, philter87 approved these changes, later dismissed

2024-03-26 15:19 UTC, signekb commented
I'm done editing now, I promise 😁

2024-03-26 17:53 UTC, lwjohnst86 requested changes

2024-03-26 17:53 UTC, lwjohnst86 commented on sprout/static/css/style.css
> +}
Keep CSS styling within it's own sheet.

2024-03-26 17:53 UTC, lwjohnst86 commented on sprout/templates/project-id-metadata-view.html
> +    <div class="table-header">
Hmm, what was the reason to use `div` rather than `table` HTML tag? This feels more complicated. Plus my formatter/linter is complaining of an unexpected closing div, but I can't debug it.

2024-03-26 17:53 UTC, lwjohnst86 commented on sprout/templates/project-id-metadata-view.html
> +      <a style="display:block" href="{% url 'project-id-metadata-view' %}">
Neat way of doing this. Though the big disadvantage here is that whenever you select a new row, the page has to be rendered to a whole other page because it is a redirect. Let's keep everything within this page and not move to other pages.

2024-03-26 17:53 UTC, lwjohnst86 commented on sprout/templates/project-id-metadata-view.html
> +              class="table-row selectable{% if request.GET.selected_metadata_id|add:'0' == metadata.id %} selected{% endif %}"
Using the `table` HTML you can use CSS to highlight on hover, rather than using `div` classes for this. Unless you have really strong reasons for using `div` rather than `table`, could you switch to `table`? It will be easier to style if it is a `table` element.

2024-03-26 17:53 UTC, lwjohnst86 commented on sprout/templates/project-id-metadata-view.html
> +      name="button_upload"><i>upload</i>Upload Data</button>
I'd prefer that redirect happens here, not on the Django side (see how I did it in #293). So it would be an `a` element with `href` to other pages. The less we have to send to Django for small things like this, the less traffic between server and client there has to be. 

Of course, these would only be clickable after selecting a page so will need some JavaScript.

2024-03-27 12:17 UTC, signekb commented on sprout/templates/project-id-metadata-view.html
> +<style>
@philter87 Luke prefers to keep style in a separate file, so I'll change it here instead

2024-03-27 14:54 UTC, signekb commented on sprout/templates/project-id-metadata-view.html
> +    <div class="table-header">
I ran into some issues when I added the expand feature showing the column metadata. But I'll just change it again and see if I can figure out the way to expand using the `table` tag.

2024-03-27 14:55 UTC, signekb commented on sprout/templates/project-id-metadata-view.html
> +      <a style="display:block" href="{% url 'project-id-metadata-view' %}">
I changed i now, but use quite a lot of js. I can probably be optimised.

2024-03-27 14:56 UTC, signekb commented on sprout/templates/project-id-metadata-view.html
> +              class="table-row selectable{% if request.GET.selected_metadata_id|add:'0' == metadata.id %} selected{% endif %}"
I have changed it back to `table`

2024-03-27 14:56 UTC, signekb commented on sprout/templates/project-id-metadata-view.html
> +      name="button_upload"><i>upload</i>Upload Data</button>
As described in another comment above, I have changed it now and use js, but I think that the js code could/should be optimised

2024-04-02 08:33 UTC, signekb commented
@philter87 and I have now reviewed the code together and simplified the scripts. 
Note two changes in particular:
1. It is now not possible to deselect a row when it has been selected (we discussed this, and it might not be necessary to deselect a row after all)
2. We have removed four tests that check that the redirects when the different buttons have been clicked. This is not possible anymore with the js solution.

2024-04-02 09:19 UTC, lwjohnst86 approved these changes
Super nice and clean! Great job!

2024-04-02 09:19 UTC, merged