feat: Preview data sample is added
seedcase-project/seedcase-sprout pull request #332
Opened 2024-03-25 12:16 UTC by philter87

## Description

- This PR adds a feature. Shows up to 5 unique values for a column (see picture below for an example)

![image](https://github.com/seedcase-project/seedcase-sprout/assets/5868902/842e8257-e068-41f9-bdbc-283da1b6909c)

## Related Issues

Closes #316 

## Testing

- [X] Yes
- [ ] No, not needed (give a reason below)
- [ ] No, I need help writing them

## Reviewer Focus
This PR only needs a quick review.

## Checklist

For all PRs that are not general documentation

- [X] Tests accompany or reflect changes to the code
- [X] Tests ran and passed locally
- [X] Ran the linter and formatter
- [X] Build has passed locally
- [X] Relevant documentation has been updated

2024-03-25 15:35 UTC, signekb commented
@philter87 From the screenshot you shared, I see that HEALTHCARE_EXPENSES shows five unique values and the text says `<5 unique values`. Should this be `<=5 unique values`?

2024-03-26 08:54 UTC, signekb requested changes
Very nice! 🎉  I have added my preferred wording for the text above the data sample as well as added that one column in the test has more than 5 unique values.

2024-03-26 08:54 UTC, signekb commented on sprout/templates/column-review.html
> +              <p style="color: grey; font-size: 0.75rem; font-weight: bold; margin-bottom: 5px">Preview (<=5 unique values):</p>
```suggestion
              <p style="color: grey; font-size: 0.75rem; font-weight: bold; margin-bottom: 5px">Preview (showing up to 5 unique values):</p>
```

2024-03-26 08:54 UTC, signekb commented on sprout/tests/tests_views_column_review.py
> +        file = io.BytesIO(b"TestColumn,Letter\n1,A\n2,B\n3,C\n4,C")
```suggestion
        file = io.BytesIO(b"TestColumn,Letter\n1,A\n2,B\n3,C\n4,C\n5,C\n6,C")
```
Might be nice to include that one of the test columns include more than 5 unique values.

2024-03-26 08:54 UTC, signekb commented on sprout/tests/tests_views_column_review.py
> +        self.assertEqual([1, 2, 3, 4], sample["TestColumn"])
```suggestion
        self.assertEqual([1, 2, 3, 4, 5], sample["TestColumn"])
```

2024-03-26 09:28 UTC, signekb approved these changes, later dismissed
Very nice 🎉

2024-03-26 10:40 UTC, lwjohnst86 submitted a review, later dismissed

2024-03-26 10:53 UTC, lwjohnst86 approved these changes
🎉

2024-03-26 10:53 UTC, merged