refactor: 🏗️ Update C4 container diagram
seedcase-project/seedcase-sprout pull request #405
Opened 2024-04-22 16:17 UTC by lwjohnst86

## Description

- This PR finally updates the C4 model diagrams to help give more clarity on some things that have been confusing/incompletely documented lately.

## Related Issues

Closes #8

2024-04-23 07:26 UTC, philter87 commented
Looks good! but maybe I need some clarification on what a "database" is in the drawings. There seems to be multiple databases user metadata, project metadata and then databases for the actual data for each project. 

Is that separate database servers or just "areas" inside the database?

2024-04-23 07:30 UTC, lwjohnst86 commented
@philter87 great question. I didn't really know how to call it. Maybe "Table" or "Space" or something else? I know that Django stores everything in the SQLite by default, but what word would best describe where data is stored for specific information? Ideas?

2024-04-23 08:29 UTC, signekb approved these changes
Very nice and green 🟢  
It might be nice with a post describing these and how they are related?

2024-04-23 08:29 UTC, signekb commented on docs/design/images/component-management.puml
> +    Component(user_update, "Update user details")
```suggestion
    Component(user_update, "Update user")
```

2024-04-23 08:29 UTC, signekb commented on docs/design/images/component-management.puml
> +    Component(user_delete, "Delete user details")
```suggestion
    Component(user_delete, "Delete user")
```

2024-04-23 08:29 UTC, signekb commented on docs/design/images/component-ui.puml
> +  Component(page_metadata_list, "List all data tables", $descr="Show all tables that contain data in the project")
Only tables that contain data? Not all created metadata (i.e., the `metadata-id-view` page)?

2024-04-23 08:29 UTC, signekb commented on docs/design/images/component-ui.puml
> +  Component(page_data_update, "Add data to existing data", $descr="Adding new or updating existing data in a project")
```suggestion
  Component(page_data_update, "Add data to existing data", $descr="Add new or update existing data in the project")
```
To fit tense in the other components.

2024-04-23 08:29 UTC, signekb commented on docs/design/images/component-ui.puml
> +  Component(page_data_qc, "Data quality control details page", $descr="Reports on basic quality and validation of data")
Does that include a log over prior reports? Like a report for every attempted data upload?

2024-04-23 08:29 UTC, signekb commented on docs/design/images/component-ui.puml
> +  Component(page_data_update, "Add data to existing data", $descr="Adding new or updating existing data in a project")
In what ways will we allow users to "update existing data"?

2024-04-23 08:29 UTC, signekb commented on docs/design/images/component-ui.puml
> +  Component(page_user_admin, "User admin page", $descr="Management of users with the project")
```suggestion
  Component(page_user_admin, "User admin page", $descr="Manage users within the project")
```
To fit tense in the other components

2024-04-23 08:29 UTC, signekb commented on docs/design/images/component-management.puml
> +  Container_Boundary(users, "User Management") {
```suggestion
  Container_Boundary(users, "User management") {
```
To fit casing in other boundary containers

2024-04-23 08:29 UTC, signekb commented on docs/design/images/component-ui.puml
>  Container_Boundary(ui, "Web Interface") {
```suggestion
Container_Boundary(ui, "Web interface") {
```

2024-04-23 08:29 UTC, signekb commented on docs/design/images/container.puml
> +Person(user_contributor, "Data Contributor")
```suggestion
Person(user_contributor, "Data contributor")
```

2024-04-23 08:29 UTC, signekb commented on docs/design/images/container.puml
> +  Container(ui, "Web Interface", "HTML, CSS, JavaScript")
```suggestion
  Container(ui, "Web interface", "HTML, CSS, JavaScript")
```

2024-04-23 08:29 UTC, signekb commented on docs/design/images/container.puml
> +  Container(projects, "Project Management", "Python, Django, SQLite",  $descr="Create projects, manage existing ones")
```suggestion
  Container(projects, "Project management", "Python, Django, SQLite",  $descr="Create projects, manage existing ones")
```
Also PostgreSQL?

2024-04-23 08:29 UTC, signekb commented on docs/design/images/container.puml
> +  Container(data, "Data Management", "Python, Django", $descr="Run checks, process data, send to database")
```suggestion
  Container(data, "Data management", "Python, Django", $descr="Run checks, process data, send to database")
```

2024-04-23 08:29 UTC, signekb commented on docs/design/images/container.puml
> +  Container(login, "User Login", "Python, Django")
```suggestion
  Container(login, "User login", "Python, Django")
```

2024-04-23 08:29 UTC, signekb commented on docs/design/images/container.puml
> +  Container(users, "User Management", "Python, Django, SQLite", $descr="Assign roles, add or remove users")
```suggestion
  Container(users, "User management", "Python, Django, SQLite", $descr="Assign roles, add or remove users")
```
Also PostgreSQL?

2024-04-23 08:29 UTC, signekb commented on docs/design/images/container.puml
> +  ContainerDb(database_data, "Relational Database for Data", "Postgres/SQLite")
```suggestion
  ContainerDb(database_data, "Relational database for data", "Postgres/SQLite")
```

2024-04-23 08:29 UTC, signekb commented on docs/design/images/container.puml
> +  ContainerDb(database_metadata, "Relational Database for Metadata", "SQLite")
```suggestion
  ContainerDb(database_metadata, "Relational database for metadata", "SQLite")
```
Also PostgreSQL?

2024-04-23 08:29 UTC, signekb commented on docs/design/images/container.puml
> +  ContainerDb(file_storage, "File Storage for Raw Data", "Filesystem")
```suggestion
  ContainerDb(file_storage, "File storage for raw data", "Filesystem")
```

2024-04-23 08:29 UTC, signekb commented on docs/design/images/context.puml
> +Person(user_owner, "Project owner", "Creator and owner of a project within Sprout")
How do these user roles fit in with the ones described in the [users](https://github.com/seedcase-project/seedcase-sprout/blob/main/docs/design/users.qmd) post? Are they the same with different names or?
- User Access Administrators = Project admin?
- Data Management Administrators = Project owner?

2024-04-23 08:29 UTC, signekb commented on docs/design/images/context.puml
> +Person(user_admin, "Project admin", "Manage users, assess problems with data, and preparing for new data")
```suggestion
Person(user_admin, "Project admin", "Manages users, assesses problems with data, and prepares for new data")
```

2024-04-23 08:29 UTC, signekb commented on docs/design/images/context.puml
> +Person(user_owner, "Project owner", "Creator and owner of a project within Sprout")
```suggestion
Person(user_owner, "Project owner", "Creates and owns a project within Sprout")
```

2024-04-23 08:29 UTC, signekb requested changes
Very nice and green 🟢  
It might be nice with a post describing these and how they are related?

2024-04-23 12:18 UTC, philter87 commented
> @philter87 great question. I didn't really know how to call it. Maybe "Table" or "Space" or something else? I know that Django stores everything in the SQLite by default, but what word would best describe where data is stored for specific information? Ideas?

Yeah, that is tricky. Maybe database is okay for now

2024-04-23 13:22 UTC, lwjohnst86 commented on docs/design/images/component-backend.puml
> +BiRel(management, changelog, "Auto-generated")
OOo that was not intentional, good catch 🎉

2024-04-23 13:33 UTC, lwjohnst86 commented on docs/design/images/context.puml
> +Person(user_owner, "Project owner", "Creator and owner of a project within Sprout")
These roles are being updated since they are outdated after our conversations in the past about a month ago. I will likely do that soon or I think @K-Beicher is doing it too.

2024-04-23 13:44 UTC, lwjohnst86 commented
@signekb I will add a connected document to also list the diagrams 🦾 will finish it later today

2024-04-24 09:11 UTC, lwjohnst86 commented
@signekb I wrote up a document that inserts the diagrams and describes them a bit

2024-04-24 11:13 UTC, signekb commented on docs/design/images/context.puml
> +Person(user_owner, "Project owner", "Creator and owner of a project within Sprout")
Oh, okay. So the new names will be "project owner" and "project admin"?

2024-04-24 11:43 UTC, signekb requested changes
Very nice with the post! 
I have added some suggestions :)

2024-04-24 11:43 UTC, signekb commented on docs/design/c4-models.qmd
> +Components (which has three diagrams).
```suggestion
Components (which includes three diagrams).
```

2024-04-24 11:43 UTC, signekb commented on docs/design/c4-models.qmd
> +don't need. Below is the diagrams for the Context, Containers, and
Do we want to capitalise the c's in **C**ontext, **C**ontainers, **C**omponents every time they are written?

2024-04-24 11:43 UTC, signekb commented on docs/design/c4-models.qmd
> +The Context model is mainly used to show the users and any external
```suggestion
The Context model shows the users and any external
```

2024-04-24 11:43 UTC, signekb commented on docs/design/c4-models.qmd
> +systems that interact with Sprout.
```suggestion
systems that interact with Sprout. This includes the three user roles *data contributor*, *project admin* and *project owner* described in the [users](users.qmd) post.
```

2024-04-24 11:43 UTC, signekb commented on docs/design/c4-models.qmd
> +The Container model is used to show larger parts of a system, what they
```suggestion
The Container model shows the larger parts of the system, what they
```

2024-04-24 11:43 UTC, signekb commented on docs/design/c4-models.qmd
> +are responsible for and how they interact with each other. It also shows
```suggestion
are responsible for, and how they interact with each other. It also shows
```

2024-04-24 11:43 UTC, signekb commented on docs/design/c4-models.qmd
> +technology choices for each Container.
```suggestion
the technology choices for each Container.
```

2024-04-24 11:43 UTC, signekb commented on docs/design/c4-models.qmd
> +The Context model is mainly used to show the users and any external
Why are they called *models* here, *levels of abstraction* in the intro, and elsewhere just *diagrams*? Can this be aligned or are you referring to different things?

2024-04-24 11:43 UTC, signekb commented on docs/design/c4-models.qmd
> +the Components: the user interface, the server or internal management,
```suggestion
the Components: the user interface, management,
```
To align with how it's referred to below

2024-04-24 11:43 UTC, signekb commented on docs/design/c4-models.qmd
> +### Databases
```suggestion
### Databases and storage
```

2024-04-24 11:43 UTC, signekb commented on docs/design/images/component-management.puml
> +Container(ui, "Web interface")
```suggestion
Container(ui, "User interface")
```
At least that what it's called in the post :)

2024-04-24 11:43 UTC, signekb commented on docs/design/images/component-ui.puml
> +Container_Boundary(ui, "Web interface") {
```suggestion
Container_Boundary(ui, "User interface") {
```

2024-04-24 11:43 UTC, signekb commented on docs/design/images/container.puml
> +  Container(ui, "Web interface", "HTML, CSS, JavaScript")
```suggestion
  Container(ui, "User interface", "HTML, CSS, JavaScript")
```

2024-04-24 11:43 UTC, signekb commented on docs/design/c4-models.qmd
> +Containers.](images/component-ui.png)
```suggestion
### User interface

This diagram shows the pages of the user interface in the user interface container. In addition, it shows which user roles that can access them. Outside the container is the authentication container and the downstream management container. The authentication container is needed to authenticate users and their access. 

![C4 Component diagram showing the parts that make up the user interface
Containers.](images/component-ui.png)
```

Add what the downstream management container is and what it does (bc I'm not sure :).)

2024-04-24 11:43 UTC, signekb commented on docs/design/c4-models.qmd
> +Containers.](images/component-ui.png)
Ah! It's just the management components described below? Then maybe remove "downstream" from the name, so it's referred to with the same name both places :)

2024-04-24 11:43 UTC, signekb commented on docs/design/c4-models.qmd
> +Containers.](images/component-ui.png)
And adding short descriptions of the two remaining component diagrams would really help with easing the understanding of them :)

2024-04-25 10:27 UTC, lwjohnst86 commented on docs/design/c4-models.qmd
> +don't need. Below is the diagrams for the Context, Containers, and
Hmm good question. Yea maybe we don't capitalize. The C4 website doesn't.

2024-04-25 10:27 UTC, lwjohnst86 commented on docs/design/c4-models.qmd
> +The Context model is mainly used to show the users and any external
Hmm, model is an abstract construct about a real world thing. A diagram is the literal thing it is on the page (the actual image). So you can have a diagram of a model. They aren't the same things. But I see here it should be actually called a diagram at this point.

2024-04-25 10:31 UTC, lwjohnst86 commented on docs/design/c4-models.qmd
> +don't need. Below is the diagrams for the Context, Containers, and
hmmm, they only capitalize it when combined with "diagram" ("Context diagram")

2024-04-29 16:43 UTC, merged