docs: update user description document
seedcase-project/seedcase-sprout pull request #409
Opened 2024-04-24 12:36 UTC by K-Beicher

## Description

- This PR updates the description of the users in Sprout.
- These changes are done because the current description was outdated.

## Related Issues

Closes #328 and closes #329

## Reviewer Focus

This PR requires an in-depth review.

## Checklist
For general documentation:

- [ ] Spell-check
    - [x] US
    - [ ] UK
- [x] Did the page(s) preview correctly on your machine without breaking
- [x] New category words (keywords) (if any) added to the code snippet file

2024-04-24 13:53 UTC, lwjohnst86 requested changes

2024-04-24 13:53 UTC, lwjohnst86 commented on docs/design/users.qmd
> +put into Sprout.
This text would fit better in another location, maybe `data-flow` (that I am soon to move over from the main design docs).

2024-04-24 13:53 UTC, lwjohnst86 commented on docs/design/users.qmd
> +| Action | Type of information | DMA | DC  | UAA | PA  |
We had discussed during one of the meetings that it would be three users: project owner, project admin, and data contributor. I have them partly described in the C4 models in #405

2024-04-25 07:07 UTC, K-Beicher commented on docs/design/users.qmd
> +| Action | Type of information | DMA | DC  | UAA | PA  |
I was thinking that it might be relevant to have a role that you could assign to an uploader, if they need to be able to help with user admin without having access to the data itself, but I'll take it out for now.

2024-04-25 07:10 UTC, K-Beicher commented on docs/design/users.qmd
> +put into Sprout.
Shall we keep it here for now, and then move it when the rest is moved?

2024-04-25 08:18 UTC, signekb reviewed
Very nice! I have some minor suggestions :)

2024-04-25 08:18 UTC, signekb commented on docs/design/users.qmd
> +between users and data. There are two types of data in Seedcase Sprout,
Wait, do we have three kinds? With user data?

2024-04-25 08:18 UTC, signekb commented on docs/design/users.qmd
> +between users and data. There are two types of data in Seedcase Sprout,
Or even four with project data? 
...maybe I'm getting ahead of myself

2024-04-25 08:18 UTC, signekb commented on docs/design/users.qmd
> +put into Sprout.
Very nice but also not directly related to users and descriptions of them. So maybe also move this out to another post?

2024-04-25 08:18 UTC, signekb commented on docs/design/users.qmd
> +Super User/Data Owner.
```suggestion
note that it is possible for an individual to have more than one role.
If they are to do everything we would expect them to have the role of
Project owner.

The table below shows the four actions (*create*, *read*, *update*, and *delete*), the types of data (*research data*, *metadata*, and *user data*) and which user types that are allowed to do which actions on which type of data.
```

2024-04-25 08:18 UTC, signekb commented on docs/design/users.qmd
> +<!--TODO Talk about the ? items-->
Good questions. What are your thoughts on this @lwjohnst86 ?

2024-04-25 08:18 UTC, signekb commented on docs/design/users.qmd
>  Data Management Administrators are responsible for the database itself
```suggestion
Data management administrators are responsible for the database itself
```

2024-04-25 08:18 UTC, signekb commented on docs/design/users.qmd
> +-   Log in and set up table structures.
```suggestion
-   Log in and set up the metadata structure.
```

2024-04-25 08:18 UTC, signekb commented on docs/design/users.qmd
> +-   Be on call for potential data issues that the people uploading data
```suggestion
-   Be on call for potential data issues that the Data contributors (described below)
```

2024-04-25 08:18 UTC, signekb commented on docs/design/users.qmd
> +collection centers and are researchers, technicians, or other research
technicians?

2024-04-25 08:18 UTC, signekb commented on docs/design/users.qmd
> +database of a specific Data Resource managed by Sprout.
```suggestion
database managed by Sprout.
```
Maybe it's fine to remove the mention of a "data resource" here? Otherwise it would be nice to include a link to the definition of what that is :)

2024-04-25 08:18 UTC, signekb commented on docs/design/users.qmd
> +defined by the Data Management Admin. In time it is expected that these
```suggestion
defined by the Data management administrator(s). These
```

2024-04-25 08:18 UTC, signekb commented on docs/design/users.qmd
> +users will also have potential access to forms where data can be entered
```suggestion
users will also have access to forms where data can be entered
```

2024-04-25 08:18 UTC, signekb commented on docs/design/users.qmd
> +data (eg. scans or images).
```suggestion
data (eg. scans or images) when these features are added to Sprout.
```
Or something like that?

2024-04-25 08:18 UTC, signekb commented on docs/design/users.qmd
> +    into pre-defined table structures set up by the DMA or SU.
```suggestion
    into pre-defined metadata (i.e., table structures) set up by the Data management administrator(s) or Project owner(s).
```

2024-04-25 08:18 UTC, signekb commented on docs/design/users.qmd
> +|        | User Data           |     |     | X   |
There's something about the ordering that doesn't make sense to me. Either have the one with least access first: DC, DMA, and then PO, or the one with access to everything first: PO, DMA, then DC :)

2024-04-25 08:18 UTC, signekb commented on docs/design/users.qmd
> +The Project Owner is the person who can do everything in the system.
```suggestion
The Project owner has access to everything in Sprout and can do all four actions to all types of data in Sprout. 
```

2024-04-25 08:18 UTC, signekb commented on docs/design/users.qmd
> +to all four action types for all three types of information. This will
```suggestion
Seedcase Sprout. This will
```

2024-04-25 08:18 UTC, signekb commented on docs/design/users.qmd
> +also be the person who in later versions of Seedcase will potentially
```suggestion
also be the person who in later versions of the Seedcase ecosystem will
```

2024-04-25 08:18 UTC, signekb commented on docs/design/users.qmd
> +| Action | Type of information | DMA | DC  | PO |
```suggestion
| Action | Type of data | DMA | DC  | PO | 
```

2024-04-25 08:18 UTC, signekb commented on docs/design/users.qmd
> +|        | User Data           |     |     | X   |
```suggestion
| Create | Research data       | X   | X   | X   |
|        | Metadata            | X   |     | X   | 
|        | User data           |     |     | X   | 
| Read   | Research data       | X   | ?   | X   | 
|        | Metadata            | ?   |     | X   | 
|        | User data           | X   |     | X   | 
| Update | Research data       | X   |     | X   | 
|        | Metadata            | X   |     | X   | 
|        | User data           |     |     | X   | 
| Delete | Research data       | ?   |     | X   | 
|        | Metadata            | ?   |     | X   | 
|        | User data           |     |     | X   | 
```

2024-04-26 07:19 UTC, K-Beicher commented on docs/design/users.qmd
> +Access Administrators) to be able to customize access for their own
Good point

2024-04-26 07:21 UTC, K-Beicher commented on docs/design/users.qmd
> +between users and data. There are two types of data in Seedcase Sprout,
I'll go with three for now

2024-04-26 07:22 UTC, K-Beicher commented on docs/design/users.qmd
> +option to create, update, and/or delete metadata and research data.
Yes, should we keep it here until further notice?

2024-04-26 07:28 UTC, K-Beicher commented on docs/design/users.qmd
> +collection centers and are researchers, technicians, or other research
Don't think this was mine originally, so over to @lwjohnst86 to see if there is another term to use here?

2024-05-23 10:15 UTC, lwjohnst86 approved these changes
I made a decent amount of changes and reorganization, now approve it and will merge 😁

2024-05-23 10:15 UTC, merged

2024-05-27 10:53 UTC, signekb commented
@lwjohnst86 In general, when making a lot of changes and reorganising things, wouldn't it make sense to ask for a review again before merging? :)

2024-05-27 11:12 UTC, lwjohnst86 commented
@signekb definitely, though in this case I intentionally didn't want anyone to spend anymore time on it, since it had already been reviewed a few times, isn't the focus right now, and we'll be coming back to these docs anyway soon enough ☺️

2024-05-27 11:13 UTC, lwjohnst86 commented
I should have written that when I merged it in, that probably would have helped!

2024-05-27 11:39 UTC, signekb commented
Ah, makes sense. Yes, that would have helped :)