Move authentication, authorisation and login to Sprout
seedcase-project/seedcase-sprout pull request #467
Opened 2024-06-24 07:34 UTC by martonvago

## Description

- This PR moves all authentication, authorisation and login sections to Sprout.
- Concrete login details are moved to Runtime view (they were mostly there already anyway).
- More general discussions about our authentication/authorisation strategies are moved to the Security page that I made. I'm happy to move them somewhere else though!

## Related Issues
Goes hand in hand with https://github.com/seedcase-project/design/pull/107

Closes https://github.com/seedcase-project/design/issues/86

## Reviewer Focus

This PR only needs a quick review.

## Checklist

For general documentation:

- [x] Spell-check
    - [ ] US
    - [ ] UK
- [x] Did the page(s) preview correctly on your machine without breaking
- [x] New category words (keywords) (if any) added to the code snippet file

2024-06-24 08:11 UTC, martonvago commented on docs/design/security.qmd
> +### Database-level User Roles
This section and the permissions section overlap with the User Roles page (in Sprout). I've just seen this and my read is that the User Roles page is like a Sprout-specific refinement of the more general roles and permissions. As we discussed moving these general bits to Sprout, I'll leave them on this page for now, and if anyone has strong views about whether we should delete them or merge them into the Sprout-specific bits, I'll do that.

2024-06-24 11:58 UTC, lwjohnst86 requested changes
Wonderful 🎉 🌮

2024-06-24 11:58 UTC, lwjohnst86 commented on docs/design/security.qmd
> +### Database-level User Roles
This section definitely makes more sense in Sprout rather than here. Could you move it over?

2024-06-24 11:58 UTC, lwjohnst86 commented on docs/design/security.qmd
> +
```suggestion
```

Many parts of this section would work better in their respective software docs. Most of these permissions are already listed in Sprout, and the others will very likely be updated/refined when we get to them

2024-06-24 12:02 UTC, martonvago commented on docs/design/security.qmd
> +### Database-level User Roles
Terribly stupid question, but isn't this Sprout?

2024-06-28 13:47 UTC, lwjohnst86 commented on docs/design/security.qmd
> +### Database-level User Roles
wow, I'm dumb 😆 I was so used to seeing the design repo I didn't notice this 🤦🏻

2024-06-28 13:47 UTC, lwjohnst86 commented on docs/design/security.qmd
> +
Ignore this 😆

2024-06-28 13:47 UTC, lwjohnst86 approved these changes, later dismissed

2024-06-28 13:48 UTC, lwjohnst86 approved these changes

2024-06-28 13:49 UTC, merged