Docs/update sprout readme
seedcase-project/seedcase-sprout pull request #474
Opened 2024-06-25 11:55 UTC by K-Beicher

## Description

- This PR a bit more to the readme file for the Sprout app.
- These changes are done because we need more information about what Sprout is on the Github website.

## Related Issues

Closes #28 

## Reviewer Focus

This PR only needs a quick review.

There isn't much text to review. It would be good to get an opinion on whether to keep the installation sections below, or if those should move somewhere else.

## Checklist

For general documentation:

- [x] Spell-check
    - [ ] US
    - [ ] UK
- [x] Did the page(s) preview correctly on your machine without breaking
- [x] New category words (keywords) (if any) added to the code snippet file

2024-06-25 16:18 UTC, lwjohnst86 requested changes
Looks like a good start! Yes, installation instructions (for development and eventually actual installing to use) should be in the README (or at least link to a full set of instructions).

2024-06-25 16:18 UTC, lwjohnst86 commented on README.md
> +Sprout is the backbone of the Seedcase family, this is where data is uploaded, described and stored based on a relational database design. Sprout is also the application which contains the user admin
```suggestion
Sprout is the backbone of the Seedcase family, this is where data is uploaded, described and stored based on a relational database design. Sprout is also the application which contains the user administration part of Seedcase (although this may change at a later date).
```

2024-06-25 16:18 UTC, lwjohnst86 commented on README.md
> +Seedcase Sprout is designed to receive data files and guide the user through adding meta data to the research data that the user of Seedcase would like to store in a responsible way.
```suggestion
Seedcase Sprout is designed to receive data files and guide the user through adding metadata to the research data that the user of Seedcase would like to store in a responsible way.
```

2024-06-25 16:18 UTC, lwjohnst86 commented on README.md
> +Check out our [app](https://seedcase-sprout.fly.dev/) where you can upload a csv file with data and experience how to add metadata.
```suggestion
Check out a [demo](https://seedcase-sprout.fly.dev/) of Sprout, where you can upload a csv file with data and experience how to add metadata.
```

2024-06-27 08:07 UTC, signekb reviewed
Just have these two minor suggestions for now. I'll come back to look at the content :)

2024-06-27 14:35 UTC, lwjohnst86 requested changes
Made a few edits to @signekb suggestions, otherwise 🎉

2024-06-28 12:35 UTC, signekb approved these changes

2024-06-28 13:40 UTC, lwjohnst86 approved these changes

2024-06-28 13:40 UTC, merged