feat: :sparkles: add frictionless-style sample data and metadata
seedcase-project/seedcase-sprout pull request #530
Opened 2024-07-24 13:16 UTC by martonvago

## Description

This adds metadata for `patients.csv` using the frictionless standard. See the Notes section of [this comment](https://github.com/seedcase-project/seedcase-sprout/issues/512#issuecomment-2245427197) for some more context.

I put this in `persistent_storage`, imagining that we would eventually want a folder structure where data projects live in separate folders in some sort of secure storage space, with each project folder containing one `datapackage.json` metadata file and any number of data files. But I'm not super sure where to actually put the project folders.

We also have a very sensible rule to gitignore data in `persistent_storage`, which I overruled in this case to add the sample data. I'm also very open to any other ideas about how we should do this.

I haven't yet removed the old sample data, as it's still used by the database in `app`. I thought we could remove it when we switch over to the new sample data.

Closes #511 

## Reviewer Focus

This PR needs more of an in-depth review. Focus on the structure of the metadata and the folder structure.

## Checklist

- [x] Added or updated tests
- [x] Tests passed locally
- [x] Linted and formatted code
- [x] Build passed locally
- [x] Updated documentation

2024-07-24 13:22 UTC, martonvago commented on persistent_storage/projects/sample-project/datapackage.json
This corresponds to a frictionless `Package` object. I generated it using the frictionless cli and then added custom properties.

Correspondence between our Django models and classes in frictionless:
  - `Tables` = `Resource` + custom properties `is_draft`, `created_at`, `created_by`, `modified_at`, `modified_by`, `last_data_upload`, `data_rows`, `files`
  - `Files` = the objects listed under the `files` property above
  - `Columns` = `Field`+ custom property `machine_readable_name`
  - `DataType` = `type` property on `Field`

2024-07-29 20:07 UTC, lwjohnst86 requested changes
Very nice!! This is a good starting point, and we can move our models to align with frictionless

2024-07-29 20:07 UTC, lwjohnst86 commented on persistent_storage/projects/sample-project/datapackage.json
Very nice. As per the naming doc on project files, this would go under `projects/0/` rather than `sample-project`. Or more likely, if we align with frictionless data, it would be `package/0/`.

Since we will be starting all regular projects at and above 1, we can use 0 as our example/sample.

2024-07-29 20:07 UTC, lwjohnst86 commented on persistent_storage/projects/sample-project/patients.csv
Following the naming guide, this would go under `projects/0/data/1/raw/<timestamp>-<uuid>.<extension>.gzip`. Or if we align with frictionless, it would be `packages/0/resources/1/`.

2024-07-31 12:28 UTC, martonvago commented
I also removed custom properties, as discussed.

2024-08-05 14:32 UTC, lwjohnst86 approved these changes

2024-08-05 14:33 UTC, merged