docs: :memo: major rewrite of the naming scheme to match frictionless
seedcase-project/seedcase-sprout pull request #546
Opened 2024-08-05 20:09 UTC by lwjohnst86

## Description

These changes are done to start converting over to frictionless standard language, since we decided to use frictionless standard. This also really simplifies things. I also rearranged to have a function name section and an app URL section, since they look a bit differently.

## Reviewer Focus

This PR needs a bit of an in-depth review.

2024-08-06 08:12 UTC, signekb reviewed
Very nice. I think this is getting a lot clearer. I do have some questions though - especially about how we want to store raw data.

2024-08-06 08:12 UTC, signekb commented on docs/design/naming.qmd
> +`packages/<id>/resources/<id>/add`
So how we differentiate between what we before called data and metadata isn't necessary anymore in the urls since it's only about data when we `add` and otherwise it's about the metadata?

2024-08-06 08:12 UTC, signekb commented on docs/design/naming.qmd
> +-   Types of folders: raw and resources.
But maybe Django has a way to handle this?

2024-08-06 13:33 UTC, lwjohnst86 commented on docs/design/naming.qmd
> +    we want to limit access viewing data in the raw files and database.
Yup! And it is also out of scope of Sprout.

2024-08-06 13:33 UTC, lwjohnst86 commented on docs/design/naming.qmd
> +`packages/<id>/resources/<id>/add`
I'm not sure I understand. What do we need to differentiate on?

2024-08-06 13:33 UTC, lwjohnst86 commented on docs/design/naming.qmd
> +-   Types of folders: raw and resources.
I will clarify this, the function names are for core, not the app. The app will likely store everything in a Postgres database.

2024-08-07 08:58 UTC, martonvago reviewed
Looks great and makes sense to me!

2024-08-08 12:05 UTC, signekb reviewed
Amazing! 🔥 This is super helpful - and useful! I have added some questions and suggestions.

2024-08-08 12:05 UTC, signekb commented on docs/design/naming.qmd
> +:   Compress all raw data files.
```suggestion
:   Compressed raw data files associated with a specific resource.
```
"Compress" makes it sound like an action and not a path :)

2024-08-08 12:05 UTC, signekb commented on docs/design/naming.qmd
> +`ROOT/packages/<id>/resources/<id>/data.parquet`
Will the file(s) actually be called "data" or is it a placeholder like <id>? Bc there might be multiple files associated with a resource, right? Or will the addition of a data file (a raw) be added to the one parquet file?
If a placeholder, should we then add `<>` around data?
```suggestion
`ROOT/packages/<id>/resources/<id>/<data>.parquet`
```

2024-08-08 12:05 UTC, signekb commented on docs/design/naming.qmd
> +`ROOT/packages/<id>/database.sqlite`
Same as above. Will it actually be called "database"? If we only have one db per project this is probably fine?

2024-08-09 09:16 UTC, lwjohnst86 commented on docs/design/naming.qmd
> +### Functions
I realize from the comments and also looking through both PRs that this doc is deviating from simply a naming scheme and more into a design. So I think I will split it up into two new PRs that describe the core functionality in one and the app URLs/pages in another.

2024-08-09 09:16 UTC, lwjohnst86 commented on docs/design/naming.qmd
> +`package_resources_list(package_id)`
Yes, that's intentional. Listing is many. But the way the URLs are structured, it implies many, unless a specific ID is given.

2024-08-09 09:16 UTC, lwjohnst86 commented on docs/design/naming.qmd
> +:   Add more data to a resource of a specific package.
No. But I'll try to expand on this in another PR, based on my comment above.

2024-08-09 09:16 UTC, lwjohnst86 commented on docs/design/naming.qmd
> +For the URL/app pages naming scheme, they follow a similar style to the
I'll split these out into other docs, so they are more of an explanation of the design, rather than a naming scheme.

2024-08-09 09:16 UTC, lwjohnst86 commented on docs/design/naming.qmd
> +    we want to limit access viewing data in the raw files and database.
If we provide the option to view data, we increase the risk that someone else can get the data. We have to think about more things, more security aspects, about permissions, about how they are given, about documentation to inform the user that data contributors can see the data too. So I'd rather avoid that and instead create better reporting summaries aimed at the admin. At the end of the day, the admin user will always be able to see the data anyway, so this isn't super important for us to spend so much time on.

2024-08-09 09:16 UTC, lwjohnst86 commented on docs/design/naming.qmd
> +`packages/<id>/resources/<id>/edit`
No, if they need to edit something, they can always re-upload the same person's IDs with the updated data values and it will update in the database.

2024-08-09 09:16 UTC, lwjohnst86 commented on docs/design/naming.qmd
> +:   Add data to a specific resource of a specific package.
I think we provide the full spec, give defaults if the user doesn't give them. There is no need for the user to dive into the frictionless spec or add additional fields that aren't standard (or ones that we might add to). Limit the choices the user has to make, so we can guide them toward an easier and smoother experience with structuring data.

2024-08-09 09:16 UTC, lwjohnst86 commented on docs/design/naming.qmd
>  will be stored in the Postgres database as the below file path and can
Ah, I see I missed updating some things, thanks for the catch!

2024-08-09 09:16 UTC, lwjohnst86 commented on docs/design/naming.qmd
>  be exported into actual files if desired.
I need to update this paragraph, I had missed it.

2024-08-09 09:16 UTC, lwjohnst86 commented on docs/design/naming.qmd
> +`ROOT/packages/<id>/resources/<id>/data.parquet`
It is not a placeholder. Each data resource will only have one data table. But there will be potentially many raw data files, which will be merged into one Parquet table. The name `data` is arbitrary, it could be anything, but let's just keep it simple 😛

2024-08-09 09:16 UTC, lwjohnst86 commented on docs/design/naming.qmd
> +`ROOT/packages/<id>/database.sqlite`
That's right! Only one database per package.

2024-08-09 10:53 UTC, signekb commented on docs/design/naming.qmd
> +### Functions
Sounds amazing 🎉

2024-08-09 10:54 UTC, signekb commented on docs/design/naming.qmd
> +    we want to limit access viewing data in the raw files and database.
Alright. Thanks for elaborating!

2024-08-09 10:55 UTC, signekb commented on docs/design/naming.qmd
> +:   Add more data to a resource of a specific package.
Amazing, thanks! As I understand it, from your comments in the two current PRs, we'll have multiple raw files per resource but only one parquet?

2024-08-09 10:59 UTC, signekb commented on docs/design/naming.qmd
> +    file), add (data in the package), list, and delete.
Ah, yes, I see! Just thought that it would be clearer to use the same actions for functions and URLs. But I see your point 👍

2024-08-09 11:00 UTC, signekb commented on docs/design/naming.qmd
> +:   Add data to a specific resource of a specific package.
That makes sense. Thanks for elaborating 💪

2024-08-09 11:02 UTC, signekb commented on docs/design/naming.qmd
> +`packages/<id>/resources/<id>/edit`
Ohhh, what if they have a dataset with multiple data files for the same individual then?

2024-08-09 15:41 UTC, lwjohnst86 commented on docs/design/naming.qmd
> +:   Add more data to a resource of a specific package.
See #553 to maybe answer your question ☺️

2024-08-09 15:41 UTC, lwjohnst86 commented on docs/design/naming.qmd
> +`packages/<id>/resources/<id>/edit`
I'm not sure I understand what you mean? Maybe you can ask the question over in the #554 PR about the outputs, and maybe give an example of what you mean.

2024-08-09 16:22 UTC, lwjohnst86 commented
Based on everyone's feedback and discussions, I've updated the naming scheme and split out more of the description and explanation of applying the naming scheme into their own files (see #554, #553, and #555)

2024-08-13 12:21 UTC, martonvago requested changes
Very nice!! ⭐

2024-08-13 12:21 UTC, martonvago commented on docs/design/naming.qmd
> +This document describes a general naming scheme style for Sprout that
```suggestion
This document describes a general naming scheme for Sprout that
```
Maybe "scheme" is enough?

2024-08-13 12:21 UTC, martonvago commented on docs/design/naming.qmd
> +"data resource" to "resource". We use words "property" or "properties"
```suggestion
"data resource" to "resource". We use the words "property" or "properties"
```

2024-08-13 12:21 UTC, martonvago commented on docs/design/naming.qmd
> +within the `datapackage.json` file that follows the Frictionless Data
```suggestion
to describe package and resource metadata contained
in the `datapackage.json` file that follows the Frictionless Data
```
Just avoiding an extra that-clause

2024-08-13 12:21 UTC, martonvago commented on docs/design/naming.qmd
> +| resource(s) | A single data file within a package. |
Would the (resource) properties be considered part of the resource here?

2024-08-13 12:21 UTC, martonvago commented on docs/design/naming.qmd
> +| JSON | The main way we pass and save information around. |
```suggestion
| JSON | The main way we save and pass information around. |
```
Reads better this way but conceptually the other way around is more accurate.

2024-08-13 12:21 UTC, martonvago commented on docs/design/naming.qmd
> +| copy | Copy a file from on location to another. |
```suggestion
| copy | Copy a file from one location to another. |
```

2024-08-14 10:26 UTC, lwjohnst86 commented on docs/design/naming.qmd
> +| resource(s) | A single data file within a package. |
```suggestion
| resource(s) | A single data file within a package, along with its properties. |
```

2024-08-14 11:25 UTC, signekb requested changes
Very nice 🎉

2024-08-14 11:25 UTC, signekb commented on docs/design/naming.qmd
> +applies to file paths, data objects, functions, URLs, API endpoints, and
```suggestion
applies to data objects, functions, URLs, API endpoints, and
```

2024-08-14 11:25 UTC, signekb commented on docs/design/naming.qmd
> +Data Package terminology, we simplify "data package" to "package" and
```suggestion
[Data Package](https://datapackage.org/) terminology, we simplify "data package" to "package" and
```

2024-08-14 11:25 UTC, signekb commented on docs/design/naming.qmd
> +in the `datapackage.json` file that follows the Frictionless Data
Add link to Frictionless Data?

2024-08-14 11:25 UTC, signekb commented on docs/design/naming.qmd
> +| resource(s) | A single data file within a package, along with its properties. |
Technically it can be thought of as a single data file (the parquet) or multiple data files (the raw file(s)), right?

2024-08-14 11:25 UTC, signekb commented on docs/design/naming.qmd
> +| template | A template file for specific objects, such as a template properties file. |
```suggestion
| template | A template file for specific objects, such as a template for a package or resource properties file. |
```

2024-08-14 11:25 UTC, signekb commented on docs/design/naming.qmd
> +| data | The data file within a resource. |
Meaning raw or db or parquet? Or all three? :)

2024-08-14 11:25 UTC, signekb commented on docs/design/naming.qmd
> +| JSON | The main way we save and pass information around. |
Does this only include properties or also other information?

2024-08-14 11:25 UTC, signekb commented on docs/design/naming.qmd
> +| Parquet | A columnar, efficient storage file format that we use to save a data resource. |
```suggestion
| Parquet | A columnar, efficient storage file format that we use to save data within a resource. |
```

2024-08-14 11:47 UTC, martonvago approved these changes, later dismissed

2024-08-14 16:15 UTC, lwjohnst86 commented on docs/design/naming.qmd
> +in the `datapackage.json` file that follows the Frictionless Data
Included the word Frictionless to the data package above.

2024-08-14 16:15 UTC, lwjohnst86 commented on docs/design/naming.qmd
> +| resource(s) | A single data file within a package, along with its properties. |
Umm, not sure what you mean about the second part, since you suggested adding the properties word here.

2024-08-14 16:15 UTC, lwjohnst86 commented on docs/design/naming.qmd
> +| resource(s) | A single data file within a package, along with its properties. |
```suggestion
| resource(s) | A single data file within a package, along with its properties and associated *raw* data files. |
```

2024-08-14 16:15 UTC, lwjohnst86 commented on docs/design/naming.qmd
> +| data | The data file within a resource. |
```suggestion
| data | The data file within a resource. Within Sprout, this includes the table in the database, the Parquet file, as well as raw files. |
```

2024-08-14 16:15 UTC, lwjohnst86 commented on docs/design/naming.qmd
> +| JSON | The main way we save and pass information around. |
```suggestion
| JSON | The main way we save and pass information around on the package's or resource's properties. |
```

2024-08-15 07:51 UTC, martonvago submitted a review, later dismissed

2024-08-16 12:14 UTC, K-Beicher reviewed
Seems good to me.

2024-08-16 12:25 UTC, merged