docs: :construction: init function flow for package_create()
seedcase-project/seedcase-sprout pull request #552
Opened 2024-08-09 14:27 UTC by signekb

## Description

I took a stab at creating a function flow for the function `package_create()`

## Reviewer Focus

This PR needs  an in-depth review. 

Things to keep in mind when reviewing: 

- There is a small overlap in functions in #549. I think this is OK? 
- I have added that the database.sql is created when the package is created - so users tables (user role definitions and user information on the admin/person who creates the package). Thoughts?

2024-08-09 17:30 UTC, lwjohnst86 requested changes
Great first draft!! I've added some comments, and you'll have to update some things based on the PRs I've made.

2024-08-12 13:16 UTC, signekb commented
Thanks for the feedback, @lwjohnst86 ! I have converted this back to a draft, so we can focus on your PRs before I incorporate the changes you suggested :)

2024-08-19 13:39 UTC, signekb commented on docs/design/images/core-python-functions/create-package-structure.puml
> +  cpd --> crd
Potential naming confusion with `create_resource_dir()` in `create_resource_structure()`
Alternatively, we just create the resources directory when the first resource is added?

2024-08-19 13:42 UTC, signekb commented on docs/design/images/core-python-functions/create-package-structure.puml
> +  gpi --> cni
Following @martonvago 's comment on Discord, this could be used for both new packages and new resources

2024-08-20 07:41 UTC, signekb commented on docs/design/images/core-python-functions/create-package-structure.puml
> +  vid --> gpi
Will package id's always be integers just like resources? If yes, maybe this function could be `get_ids()` or `get_existing_ids()` and be used for both packages and resources?

2024-08-20 09:52 UTC, signekb commented on docs/design/images/core-python-functions/create-package-structure.puml
> +  state "get_package_ids()" as gpi
```suggestion
  state "get_ids()" as gpi
```

2024-08-20 09:52 UTC, signekb commented on docs/design/images/core-python-functions/create-package-structure.puml
> +  vid --> gpi
We agreed on this at the update meeting today.

2024-08-20 09:58 UTC, signekb commented on docs/design/images/core-python-functions/create-package-structure.puml
> +skinparam StateFontName Fira Code
Can be removed once seedcase-project/seedcase-theme#48 has been merged

2024-08-20 15:41 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-package-structure.puml
> +  cpd --> crd
That's a good idea ☺️

2024-08-20 16:03 UTC, lwjohnst86 reviewed
I made some edits based on things being done in other PRs, plus to streamline/simplify things a bit. Let me know what you think!

2024-08-22 07:53 UTC, signekb reviewed
Nice, @lwjohnst86 ! This definitely simplifies it 🎉 
I do have some questions/suggestions though, see below.

2024-08-22 07:53 UTC, signekb commented on docs/design/images/core-python-functions/create-package-structure.puml
> +  cni --> cpp
Since this assumes that `path` is where packages are stored, is this essentially the same as `create_resource_path` in #591 and could be generalised as `create_id_path()´?

2024-08-22 07:53 UTC, signekb commented on docs/design/images/core-python-functions/create-package-structure.puml
> +  state as_list <<join>>
I think it would make more sense to me if the join would be: 
- Join 1: The readme path and readme string input
- Join 2: The properties path and the properties string input

2024-08-22 07:53 UTC, signekb commented on docs/design/images/core-python-functions/create-package-structure.puml
> +  state "create_properties_template()" as cpt
```suggestion
  state "create_package_properties_template()" as cpt
```

2024-08-22 07:53 UTC, signekb commented on docs/design/images/core-python-functions/create-package-structure.puml
> +  state "create_properties_path()" as cprop
This doesn't have to be `create_package_properties_path()` bc a properties path will always point to the `datapackage.json`, right? I.e., we don't need a `create_resource_properties_path()` as well?

2024-08-22 09:22 UTC, lwjohnst86 requested changes

2024-08-22 09:22 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-package-structure.puml
> +  cni --> cpp
Yes, love that idea!

2024-08-22 09:22 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-package-structure.puml
> +  state "create_properties_path()" as cprop
Yup, that's right, there's only one properties path.

2024-08-22 09:22 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-package-structure.puml
> +  state as_list <<join>>
That works fine with me ☺️

2024-08-22 11:41 UTC, signekb commented on docs/design/images/core-python-functions/create-package-structure.puml
> +  state "create_properties_path()" as cprop
@lwjohnst86 shouldn't this be after `create_dirs() just as `create_readme_path()`?

2024-08-22 15:20 UTC, signekb commented on docs/design/images/core-python-functions/create-package-structure.puml
> +  state "create_properties_path()" as cprop
Yes.

2024-08-22 15:20 UTC, merged