docs: :memo: description of core, external Python functions
seedcase-project/seedcase-sprout pull request #553
Opened 2024-08-09 15:02 UTC by lwjohnst86

## Description

Given all the feedback everyone gave with the other PRs, I decided to start a new one and split things into a doc dedicated to describing the functions. Hopefully this is better!! Looking forward to feedback!

I really tried to keep the function arguments simple and easy to test, hence why they all have path as one of the first arguments (easier to give a random location when testing, rather than a location that is highly coupled with other files).

2024-08-12 13:47 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +    Use `path_package()` to provide the correct `path` location. Outputs
```suggestion
    Use `path_resource()` to provide the correct `path` location. Outputs
```

Typo :)

2024-08-12 19:41 UTC, martonvago requested changes
Thanks, this is very comprehensive and systematically laid out!!

Just some minor comments and questions 😄

2024-08-12 19:41 UTC, martonvago commented on docs/design/python-functions.qmd
> +    or had an issue during the time when a user first is adding the file
```suggestion
    or had an issue during the time when a user first added the file
```

2024-08-12 19:41 UTC, martonvago commented on docs/design/python-functions.qmd
> +    list of files found to delete from. Will only delete one file. The
```suggestion
    to a resource. Use `path_resource_raw_files()` to select which file
    to delete from the list of files found. Will only delete one file. The
```

2024-08-12 19:41 UTC, martonvago commented on docs/design/python-functions.qmd
> +    would default to true so that the function obtains explicit
When would `ask` (here or elsewhere) be false? I'm just thinking that if we want confirmation from the user when e.g. submitting a web form then usually that check is done more on the front-end side, instead of letting it trickle down to the core / backend logic.

2024-08-12 19:41 UTC, martonvago commented on docs/design/python-functions.qmd
> +    would default to true so that the function obtains explicit
This is somewhat similar to the question above about checking for a `properties` object in the input.

2024-08-13 08:01 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +follows the Frictionless Data specification.
```suggestion
Several of the functions have an optional argument called `properties`.
The properties argument is a list of key-value pairs (as a JSON object) that describe the
package. This description stored in the `datapackage.json` file and
follows the Frictionless Data specification.
```

@martonvago is this better?

2024-08-13 09:08 UTC, martonvago commented on docs/design/python-functions.qmd
> +follows the Frictionless Data specification.
Nice 👍 !! Just a missing "is" in "This description <is> stored in the..."

2024-08-13 09:15 UTC, martonvago commented on docs/design/python-functions.qmd
> +    would default to true so that the function obtains explicit
My feeling would be to not have a `confirm` argument at this level at all, and instead let higher-level functions (in `app` or `cli`) handle the confirmation. But I also don't think it's super necessary to decide now and we can see what works when we implement it :)

2024-08-13 10:21 UTC, martonvago commented on docs/design/python-functions.qmd
> +    using the `properties` argument which must be a JSON object. If the
I'll have a think about this. By "download..process...convert" do you mean writing a dataclass that is conform to the standard?

But yeah, if the entire flow is just 1) get properties from user as JSON 2) use frictionless validator function to check that properties are well-formed 3) feed properties to frictionless constructor function (2 and 3 are actually probably the other way around in frictionless, but same result), then I concede that there is no point introducing complexity before we need it 😁

2024-08-13 11:26 UTC, martonvago submitted a review, later dismissed

2024-08-14 07:36 UTC, martonvago commented on docs/design/python-functions.qmd
> +    [Outputs](outputs.qmd) section. Use the `path_resource()` function
`path_resource` is defined below as `path_resource(package_id, resource_id)`, so it needs a `resource_id` as input. But here we have yet to determine what the new/next `id` will be (cf. https://github.com/seedcase-project/seedcase-sprout/pull/549). Do we not want a path to the resource**s** folder?

2024-08-14 08:30 UTC, signekb requested changes
Amazing work 🤩 I love this direction we're going now.
I have some suggestions and questions (also a couple of unfinished thoughts/notes to myself that I'll come back to)

2024-08-14 08:30 UTC, signekb commented on docs/design/python-functions.qmd
> +`delete_resource_raw_file(path, confirm)`
So this function only deletes the raw file and, therefore, leaves a discrepancy between what's in the raw folder and what's in the parquet file and in database?

2024-08-14 08:30 UTC, signekb commented on docs/design/python-functions.qmd
> +:   Delete all data and raw data of a specific resource. Use
```suggestion
:   Delete all data (parquet and in the database) and raw data of a specific resource. Use
```

2024-08-14 08:30 UTC, signekb commented on docs/design/python-functions.qmd
> +    associated metadata for the resource.
```suggestion
    associated properties/metadata for the resource.
```

2024-08-14 08:30 UTC, signekb commented on docs/design/python-functions.qmd
> +    use the `path_properties()` function to provide this path to
```suggestion
    The `path` argument is the location of the `datapackage.json` file.
    Use the `path_properties()` function to provide this path to
```

2024-08-14 08:30 UTC, signekb commented on docs/design/python-functions.qmd
> +`write_resource_properties(json_object, path)`
```suggestion
`write_resource_properties(properties, path)`
```
Right?

2024-08-14 08:30 UTC, signekb commented on docs/design/python-functions.qmd
> +`write_resource_to_table(data, path, properties)`
```suggestion
`write_resource_to_database(data, path, properties)`
```
A bit more specific, maybe? :) A table could also be thought of as a csv, for instance

2024-08-14 08:30 UTC, signekb commented on docs/design/python-functions.qmd
> +`create_properties_template()`
Does this include properties on the package level or resource level? Or both?

2024-08-14 10:23 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +    contains the full Frictionless Data specification, using `edit` is
I moved the link up to the top.

2024-08-14 10:23 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +what the function does, the path object would be different. Use the
Hmm, it might not be just us though.

2024-08-14 10:23 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +    location. This would be a list, showing very basic information that
Access isn't relevant in the core functions. Access is something we deal with in the web app. Anyone that can install Sprout can access anything they put into it.

2024-08-14 10:23 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +    each package). Use `path_sprout_root()` to provide the path to the
Hmm, probably? I think there are properties that allow that.

2024-08-14 10:23 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +    the package itself, not the resources within the package. Use
We can create a `view_properties()` function then.

2024-08-14 10:23 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +`create_package_structure(path)`
That's a level of organizing that isn't needed at this stage. Many of these documentation will be moved to the function docstrings they describe, so that the documentation can be generated automatically.

2024-08-14 10:23 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +`create_package_properties(path, properties)`
Yea, it's to keep the input/output consistent and predictable and easier to test. In the CLI and web app, there is only one function, but for the core functions we want to keep things simpler and smaller.

2024-08-14 10:23 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +    [Outputs](outputs.qmd) section. Use the `path_resource()` function
```suggestion
    [Outputs](outputs.qmd) section. Use the `path_resources()` function
```

2024-08-14 10:23 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +`create_resource_properties(path, data_path, properties)`
Yup!

2024-08-14 10:23 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +    If the `data_path` argument is not given, the `properties` argument
1. Yup! At least for creating the properties file anyway.
2. For core functions, there are no prompts because prompts assume interactivity and Python functions are rarely used interactively. There was some resolved discussions in the PR about using prompts.

2024-08-14 10:23 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +`copy_resource_data_to_raw(path, data_path)`
```suggestion
`write_resource_data_to_raw(path, data_path)`
```

2024-08-14 10:23 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +`copy_resource_data_to_raw(path, data_path)`
Great suggestion!

2024-08-14 10:23 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +:   TODO
```suggestion
`path_resources(package_id)`

:   TODO

`path_resource(package_id, resource_id)`

:   TODO
```

2024-08-14 10:23 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +`construct_resource_data(path, raw_path)`
I went back and forth on this. The problem with create is it implies making something new. But whenever new data is added to existing data, this function needs to be used to re-create/construct the Parquet data file. I couldn't think of a better action name. But I like the use of adding the parquet to the end to be clearer! Though, a disadvantage would be that if we use something other than parquet, we'd have to rename the function...

2024-08-14 10:23 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +    Outputs the path object of the created file.
Overwritten/created again ☺️

2024-08-14 10:23 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +`delete_resource_raw_file(path, confirm)`
That assumes they have been merged into those other files. I added this function specifically for those times when we are building the app/CLI and ask for user input, and they close the page or something happens and we have this left over file.

2024-08-14 10:23 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +:   TODO. Outputs a JSON object.
```suggestion
:   TODO. Outputs a JSON object.

## Observational unit level functions

Observational unit is the level of detail on the entity (e.g. human, animal, event) that the data was collected on. Example would be: A person in a research study who came to the clinic in May 2024 to have their blood collected and to fill out a survey.

`delete_participant_data()`

: TODO.
```

2024-08-14 10:23 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +## Path functions
Yup! I think once you review #557 it would answer your questions.

2024-08-14 10:23 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +`create_properties_template()`
The full Data Package spec would be created with this.

2024-08-14 11:57 UTC, signekb commented on docs/design/python-functions.qmd
> +`create_package_structure(path)`
Ah, nice!

2024-08-14 11:58 UTC, signekb commented on docs/design/python-functions.qmd
> +`create_package_properties(path, properties)`
Ahhhh, I see. 👍

2024-08-14 12:02 UTC, signekb commented on docs/design/python-functions.qmd
> +`create_properties_template()`
Soooo, both?

2024-08-14 14:30 UTC, signekb commented on docs/design/python-functions.qmd
> +`write_package_properties(json_object, path)`
```suggestion
`write_package_properties(properties, path)`
```
? :)

2024-08-14 15:21 UTC, signekb commented on docs/design/python-functions.qmd
> +    a path object.
```suggestion
    a list of two path objects: the resource path and the resource `<raw>` path.
```
At least according to #549

2024-08-14 16:02 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +`create_properties_template()`
Hmm, good point. Ok, added two specific functions for the package and resource.

2024-08-15 07:10 UTC, signekb commented on docs/design/python-functions.qmd
> +    the same). We don't provide access for users to directly edit the
Those questions have been answered in some of the other PRs that we are reviewing these days

2024-08-15 07:31 UTC, signekb commented on docs/design/python-functions.qmd
> +`construct_resource_data(path, raw_path)`
I see what you mean, but you could also think of it as making something new: the parquet file? An alternative could be `write_resource_parquet()`? 
In terms of using parquet in the naming: I don't think we have talked about using something else, so maybe its fine - and clearer - for now?

2024-08-15 07:32 UTC, martonvago submitted a review, later dismissed

2024-08-15 07:46 UTC, signekb commented on docs/design/python-functions.qmd
> +    a list of two path objects: the `resources/<id>/` path and the `resources/<id>/raw/` path.
Based on [this question](https://github.com/seedcase-project/seedcase-sprout/pull/549/files#r1717127632) - and just the PR #549 in general, I believe we should remove anything with file creation here, since this function only creates the folder structure:

```suggestion
`create_resource_structure(path)`

:   This is the first function to use to set up the structure for a data
    resource. It creates the paths for a new data resource in a specific (existing)
    package by creating folder setup as described in the
    [Outputs](outputs.qmd) section. Use the `path_resources()` function
    to provide the correct path location. It creates two paths:  the `resources/<id>/` 
    path and the `resources/<id>/raw/` path. The output is a list of these two path
    objects.
```

2024-08-15 07:48 UTC, signekb commented on docs/design/python-functions.qmd
> +`construct_resource_data(path, raw_path)`
What a minute. Now there's a function on L239 named "write_resource_to_parquet()", has it been there all along? :P

2024-08-15 07:52 UTC, signekb commented on docs/design/python-functions.qmd
> +`delete_participant_data()`
Could this be `delete_data_based_on_id()` instead? This is a bit more general and would then also cover e.g., non-human studies?

2024-08-15 09:37 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +`construct_resource_data(path, raw_path)`
Nice catch! That function was an old function before I realized that it wouldn't really work as I had originally been thinking. I'll remove it. Yea, I might have to think about this one a bit more, but for now I like the write function you suggested.

2024-08-15 09:37 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +    the path object of the created file.
```suggestion
```

2024-08-15 09:37 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +    Outputs the path object of the created file.
```suggestion
`write_resource_parquet(raw_files, path)`

:   This function takes the files provided by `raw_files` and merges them
    into a `data.parquet` file provided by `path`. Use
    `path_resource_data()` to provide the correct path location for
    `path` and `path_resources_raw_files()` for the `raw_files` argument.
    Outputs the path object of the created file.
```

2024-08-15 09:37 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +`delete_participant_data()`
Yea, I need to think about this more, so this is a WIP section.

2024-08-15 12:10 UTC, martonvago requested changes

2024-08-15 12:10 UTC, martonvago commented on docs/design/python-functions.qmd
> +    package by creating folder setup as described in the
```suggestion
    package by creating the folder setup described in the
```

2024-08-15 13:57 UTC, martonvago approved these changes, later dismissed

2024-08-15 15:02 UTC, signekb reviewed
Very nice! Mostly just language stuff (that you can ignore, if it doesn't matter at this point), but also some actual suggestions/questions.

2024-08-15 15:02 UTC, signekb commented on docs/design/python-functions.qmd
> +    The `path` argument is the location of the `datapackage.json` file.
```suggestion
:   Use to write the resource JSON object back to the `datapackage.json` file.
    This function validates whether the JSON object follows the Data Package resource specification.
    The `path` argument is the location of the `datapackage.json` file.
```
Or? :)

2024-08-15 15:02 UTC, signekb commented on docs/design/python-functions.qmd
> +    location for `path`. The `confirm` argument defaults to false so
```suggestion
    location for `path`. The `confirm` argument defaults to `false` so
```

2024-08-15 15:02 UTC, signekb commented on docs/design/python-functions.qmd
> +    that the function obtains explicit confirmation from the user and to
Again: False != explicit confirmation, orr?

2024-08-15 17:06 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +    Outputs a JSON object.
I want to avoid deducing anything as much as possible. If we decide to rename things, we've hard coded specific paths into the code that we would have to change. Which also increases the coupling between functions.

2024-08-15 17:06 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +    obtains explicit confirmation from the user and to prevent accidental deletion.
```suggestion
    This is done to prevent accidental deletion.
```

2024-08-15 17:06 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +    confirmation from the user and isn't used accidentally. Use `path_package()` function in the `path` to
```suggestion
    Use `path_package()` function in the `path` to
```

2024-08-15 17:06 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +    prevent accidental deletion. Outputs
```suggestion
    Outputs
```

2024-08-15 17:06 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +    ensures the correct table is created in the database. Outputs the
Exactly ☺️ Though, after the discussions, we might not use the database.

2024-08-16 07:03 UTC, signekb approved these changes

2024-08-16 07:59 UTC, merged