docs: :memo: Sprout's output files and structure
seedcase-project/seedcase-sprout pull request #554
Opened 2024-08-09 15:07 UTC by lwjohnst86

## Description

Based on everyone's feedback, I split things out and created a dedicated file for describing and explaining the output files created by Sprout. Looking forward to feedback!!

2024-08-12 16:26 UTC, martonvago requested changes
This is amazing and has really helped me clear up my understanding of what we are trying to achieve in terms of underlying, foundational structures!!

Many comments, but they are mostly language related 😁

2024-08-12 16:26 UTC, martonvago commented on docs/design/outputs.qmd
> +    as a data resource so can not be used by software following the
It's a bit ambiguous to me how the "following..." phrase fits in. Does it qualify "software" or the sentence as a whole?

2024-08-12 16:26 UTC, martonvago commented on docs/design/outputs.qmd
> +    resource, it is processed and stored as a
```suggestion
    resource, all resource data is processed and stored in
```

2024-08-12 16:26 UTC, martonvago commented on docs/design/outputs.qmd
> +    file as well as the table in the SQLite database is because of the
```suggestion
    file as well as a table in the SQLite database is the
```
to match "a Parquet file"

2024-08-12 16:26 UTC, martonvago commented on docs/design/outputs.qmd
> +    package occurs by providing the Parquet file, rather than the SQLite
```suggestion
    package is achieved by providing the Parquet file, rather than the SQLite
```

2024-08-12 16:26 UTC, martonvago commented on docs/design/outputs.qmd
> +    table of the database for different reasons, even though they are
```suggestion
    database. We use both the Parquet data file and the database
    table for different reasons, even though they contain
```

2024-08-13 11:34 UTC, martonvago approved these changes, later dismissed

2024-08-14 11:00 UTC, signekb requested changes
Suuuuper nice! I have some suggestions and questions :)

2024-08-14 11:00 UTC, signekb commented on docs/design/outputs.qmd
> +    the same data.
```suggestion
    database. In this way, we use both the Parquet data file and the database
    table for different reasons, even though they contain
    the same data.
```

2024-08-14 11:00 UTC, signekb requested changes
Suuuuper nice! I have some suggestions and questions :)

2024-08-14 16:34 UTC, lwjohnst86 commented on docs/design/outputs.qmd
> +form a Data Package (from the Frictionless Data standard). A data
Only when we formally refer to the website and specification, otherwise no.

2024-08-14 16:34 UTC, lwjohnst86 commented on docs/design/outputs.qmd
> +A data package is one or more files (called data resources) that contain
Yes, eventually when we've agreed with things here, we'll put things into a glossary.

2024-08-14 16:34 UTC, lwjohnst86 commented on docs/design/outputs.qmd
> +    server by an IT admin. An example default location for a local
```suggestion
    server. An example default location for a local
```

2024-08-14 16:34 UTC, lwjohnst86 commented on docs/design/outputs.qmd
> +    server by an IT admin. An example default location for a local
Hmm, no, since core or the CLI can still be installed or used on a server. I've slightly modified it though, since I understand what you are saying.

2024-08-14 16:34 UTC, lwjohnst86 commented on docs/design/outputs.qmd
> +    `<id>` (likely a number or some unique combination of characters).
Yea, just thinking about whether generating a random number might work better or be easier to assess. But for now, it is a number.

2024-08-14 16:34 UTC, lwjohnst86 commented on docs/design/outputs.qmd
> +    package, with each data resource in its own folder, e.g. `packages/1/resources/1/`.
```suggestion
    package, with each data resource in its own folder based on a number `<id>`, e.g. `packages/1/resources/1/`.
```

2024-08-14 16:34 UTC, lwjohnst86 commented on docs/design/outputs.qmd
> +    caused by any human error (aside from the choice of storage format).
Yup, that's right 😛 maybe a bit too cheeky haha I'll remove it.

2024-08-14 16:34 UTC, lwjohnst86 commented on docs/design/outputs.qmd
> +    caused by any human error (aside from the choice of storage format).
```suggestion
    caused by any human error.
```

2024-08-14 16:34 UTC, lwjohnst86 commented on docs/design/outputs.qmd
> +    where things went wrong if they did go wrong.
Yea, exactly. A user can look directly at the data if they install it locally/have full control of a servers files via a terminal.

2024-08-14 16:34 UTC, lwjohnst86 commented on docs/design/outputs.qmd
> +    and contains the full Frictionless Data specification. This file
I wouldn't normally consider it necessary since we link to it at the top, but it might be useful if someone is using this as mostly a reference.

2024-08-14 16:34 UTC, lwjohnst86 commented on docs/design/outputs.qmd
> +    and contains the full Frictionless Data specification. This file
```suggestion
    and contains the full [Frictionless Data specification](https://datapackage.org/). This file
```

2024-08-14 16:34 UTC, lwjohnst86 commented on docs/design/outputs.qmd
> +    database. Each relational table within represents one data resource.
Not at all. For the web app, we'll definitely use Postgres. Or at least, that's still the idea. And yea, there's an issue to make that post 😛

2024-08-14 16:34 UTC, lwjohnst86 commented on docs/design/outputs.qmd
> +    is easy to export to other database formats. The file is only
I only included this explanation for you all to understand things. I won't remove this yet, only until I/we make the decision post on it.

The file is the SQLite database. Unfortunately, Data Package spec doesn't allow table links in the `path` argument.

2024-08-14 16:34 UTC, lwjohnst86 commented on docs/design/outputs.qmd
> +    data resource that is linked within the `datapackage.json` file.
Hmm, the explanation is right above in this paragraph. Could you expand on what is unclear from the text above?

2024-08-14 16:34 UTC, lwjohnst86 commented on docs/design/outputs.qmd
> +    tabular data).
Yup, forget about it for now 😛 Data Package allows for different types of data, like images, etc. But that's for later, not now!

2024-08-14 16:34 UTC, lwjohnst86 commented on docs/design/outputs.qmd
> +    way the data package specification describes and sets data
Do we need the link everywhere in the doc? I'll add it for now, just feel its a bit excess to keep linking to it.

2024-08-14 16:34 UTC, lwjohnst86 commented on docs/design/outputs.qmd
> +    way the data package specification describes and sets data
```suggestion
    way the [Frictionless Data Package](https://datapackage.org/) specification describes and sets data
```

2024-08-15 07:56 UTC, martonvago submitted a review, later dismissed

2024-08-15 09:04 UTC, K-Beicher reviewed
No comments that haven't already been made :-)

2024-08-15 11:30 UTC, signekb commented on docs/design/outputs.qmd
> +    data resource that is linked within the `datapackage.json` file.
Yesssss. (sorry, if this is totally besides the point, but sometimes I just need to keep asking whatever questions pop up to make sure I understand why we choose to do what we do 🌱 )  
So, the explanation above made me think about whether we need the database bc:
1) We could use the Parquet file for indexing and querying, right? 
2. And we'll probably use the Frictionless Standard (`frictionless-py`) for data integrity checks?

2024-08-15 11:32 UTC, signekb commented on docs/design/outputs.qmd
> +    `<id>` (likely a number or some unique combination of characters).
If we have decided on using a number, maybe the "or some unique combination of characters" should be removed? 
```suggestion
    `<id>` (a whole number).
```

2024-08-15 11:36 UTC, signekb reviewed
I have looked over the conversations and answered and unresolved the ones I still find relevant :)

2024-08-15 11:36 UTC, signekb commented on docs/design/outputs.qmd
> +    is easy to export to other database formats. The file is only
Makes sense 👍 
So the SQLite file *will* be described within the "datapackage.json` file? At least according to L135-136 ("The file is only described within the `datapackage.json` file [...]"?
I thought we would link to the Parquet in the properties file?

2024-08-15 13:03 UTC, lwjohnst86 commented on docs/design/outputs.qmd
> +    data resource that is linked within the `datapackage.json` file.
Hmmmm, I guess we could use duckdb to read in the Parquet files so that we can still make use of some SQL capabilities without needing to keep an extra file around... 🤔

2024-08-15 17:10 UTC, lwjohnst86 commented on docs/design/outputs.qmd
> +    is easy to export to other database formats. The file is only
Depending on the result of the discussions, this might not be relevant. But to answer the question, we'd have to describe the database some way so people reading the `datapackage.json` file can determine the reason and use for the database. But it would probably be described in a custom field.

2024-08-20 09:25 UTC, lwjohnst86 commented on docs/design/outputs.qmd
> +    data resource that is linked within the `datapackage.json` file.
I made an issue to discuss this #581 so I will resolve this and merge in what has been added.

2024-08-20 09:45 UTC, signekb approved these changes, later dismissed

2024-08-20 09:58 UTC, merged