docs: :memo: description of the app URLs and functionality
seedcase-project/seedcase-sprout pull request #555
Opened 2024-08-09 15:54 UTC by lwjohnst86

## Description

Based on all of our discussions and feedback on the other PRs, I've split the URL naming out into its own file since the content was getting out of scope for a simple naming scheme document.

2024-08-13 07:31 UTC, martonvago requested changes
Looks great and makes a lot of sense!!

2024-08-13 07:31 UTC, martonvago commented on docs/design/app-urls.qmd
> +    package's .
Is it intentional that you can add data to a specific resource both on this page as well as on the page for that specific resource?

2024-08-13 07:31 UTC, martonvago commented on docs/design/app-urls.qmd
> +    points of security and privacy concern and to reduce the amount of
```suggestion
    security and privacy concerns and to reduce the amount of
```

2024-08-13 07:31 UTC, martonvago commented on docs/design/app-urls.qmd
> +    package's resource. This is permanent, so the user will be asked to
```suggestion
    package's specific resource. This is permanent, so the user will be asked to
```

2024-08-13 11:53 UTC, martonvago approved these changes, later dismissed

2024-08-14 11:51 UTC, signekb requested changes
Again; super nice 🎉 
I only have some minor suggestions, mostly related to wording and phrasing.

2024-08-14 11:51 UTC, signekb commented on docs/design/app-urls.qmd
> +    1.
```suggestion
    all the packages, but `packages/1/` is the folder for the package 
    with the ID of 1.
```
Currently looks like this in my local repo (floating "1."):
![image](https://github.com/user-attachments/assets/7cf9b291-ceb9-4828-ba3b-bc6d2f35ea73)

2024-08-14 11:51 UTC, signekb commented on docs/design/app-urls.qmd
> +    action. The default action is `view`. Viewing a URL doesn't just
```suggestion
2.  Since the default action for viewing a list of items or
    details of a specific item are the same, unlike for the Python functions
    that include `list` and `view`, the URLs do not have a `list`
    action. The default action is `view`. Viewing a URL doesn't just
```

2024-08-14 11:51 UTC, signekb commented on docs/design/app-urls.qmd
> +    reasons, as well as being out of scope for Sprout.
```suggestion
    reasons, and it is also out of scope for Sprout.
```

2024-08-14 11:51 UTC, signekb commented on docs/design/app-urls.qmd
> +    documents.
This is not really something that is different between the naming scheme and the URLs (as this list is about). Remove?
```suggestion
```

2024-08-14 11:51 UTC, signekb commented on docs/design/app-urls.qmd
> +    list or table of packages. From here, a user can select a package to
```suggestion
    list or table of packages and some basic information about each of them. From here, a user can select a package to
```

2024-08-14 11:51 UTC, signekb commented on docs/design/app-urls.qmd
> +    Will prompt the user to add details about the package.
```suggestion
    properties) about the package. At the beginning, there is no resources inside a package.
    This URL will prompt the user to add details about the package.
```

2024-08-14 11:51 UTC, signekb commented on docs/design/app-urls.qmd
> +    package's properties.
Or edit a resource's properties?

2024-08-14 11:51 UTC, signekb commented on docs/design/app-urls.qmd
> +    the deletion.
```suggestion
:   Delete a specific package. This action is permanent, so the user will be asked to confirm
    the deletion.
```

2024-08-14 11:51 UTC, signekb commented on docs/design/app-urls.qmd
> +:   Creates a new resource for data and associated properties. The user
```suggestion
:   Create a new resource for data and associated properties. The user
```
Or add s's to the other sections

2024-08-14 11:51 UTC, signekb commented on docs/design/app-urls.qmd
> +    creation.
```suggestion
    basic properties. The user will then be prompted to fill in the remaining 
    properties and validate the extracted properties. When this is done, the 
    properties are completed and created. The user can continue to edit the 
    resource after creation.
```

2024-08-14 11:51 UTC, signekb commented on docs/design/app-urls.qmd
> +    properties will need to be updated first (via `edit`).
or the new data will need to be edited outside of Sprout to conform with the existing properties?

2024-08-14 11:51 UTC, signekb commented on docs/design/app-urls.qmd
> +    confirm the deletion.
```suggestion
:   Delete all associated data and properties of a specific resource. 
	This is permanent, so the user will be asked to confirm the deletion.
```

2024-08-14 16:09 UTC, lwjohnst86 commented on docs/design/app-urls.qmd
> +    package's properties.
```suggestion
    package's or resource's properties.
```

2024-08-14 16:09 UTC, lwjohnst86 commented on docs/design/app-urls.qmd
> +    properties will need to be updated first (via `edit`).
```suggestion
    properties will need to be updated first (via `edit`). Either that, or the
    new data will need to be edited manually before it can successfully be uploaded.
```

2024-08-15 07:49 UTC, martonvago requested changes

2024-08-15 07:49 UTC, martonvago commented on docs/design/app-urls.qmd
> +    properties) about the package. At the beginning, there is no resources inside a package.
```suggestion
    properties) about the package. At the beginning, there are no resources inside a package.
```

2024-08-15 12:11 UTC, martonvago approved these changes, later dismissed

2024-08-16 08:04 UTC, K-Beicher reviewed
Seems very sensible

2024-08-16 12:27 UTC, merged