docs: :memo: diagram for flow of create resource properties
seedcase-project/seedcase-sprout pull request #556
Opened 2024-08-12 19:22 UTC by lwjohnst86

## Description

These changes add a function flow for the create resource properties function.

## Reviewer Focus

This PR needs a in-depth review.

2024-08-12 19:48 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  pcp --> vrp
Thinking about this some more, this doesn't actually work in a Python code setting, but would work in the CLI/App setting.

2024-08-14 10:55 UTC, martonvago requested changes
Looks great, thanks!!
Sorry for going a bit overboard with the comments 😅

2024-08-14 10:55 UTC, martonvago commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  state "add_resource_properties()" as arp
What exactly does this function do? I don't think it adds the resource properties to the package because we have `write_resource_properties(json_object, path)` for that. Does it just add the path to the parquet file to `properties`? In that case I would move "Add `path`\nproperty" inside the box from the arrow.

2024-08-14 10:55 UTC, martonvago commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  vrp --> return
What does this arrow mean? Isn't "return `properties`" indicated by the other arrow (`arp --> return`)?

2024-08-14 10:55 UTC, martonvago commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  erp : - Output: JSON
Here and elsewhere JSON stands for `properties`, right? If so, writing that would make it easier to follow maybe.

2024-08-14 10:55 UTC, martonvago commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  state "path_root_is_package()" as papr
And at what point is the parquet file actually created, before this step?

2024-08-14 10:55 UTC, martonvago commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  condition --> vrp : If properties given
What if both `properties` and `data_path` are given? And if neither?

2024-08-14 16:59 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-properties.puml
We've already had experience with these types of diagrams (well, @K-Beicher and @signekb have mostly) and they are really shitty to create, update, and look so damn ugly. State is the best that I found that provides the right balance of flexibility and features. Also, I think at this level it is overkill for making a simple sketch of what the internals will be.

2024-08-14 16:59 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  state "path_root_is_package()" as papr
Yea, I struggled with naming this function. The path relative one works fine, though.

I'm not super happy with this solution that I made, since it makes a dependency that the datapackage file is two directories up (or down?).

The Parquet file would be created later.

2024-08-14 16:59 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  state "path_root_is_package()" as papr
```suggestion
  state "path_relative_resource_data()" as prrd
```

2024-08-14 16:59 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  papr : - Required arg: absolute path
Yea, exactly.

2024-08-14 16:59 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  papr : - Required arg: absolute path
```suggestion
  prrd : - Required arg: absolute path from input
```

2024-08-14 16:59 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  papr : - Output: relative path\n  (e.g. `resource/1/data.parquet`)
```suggestion
  prrd : - Output: relative path\n  (e.g. `resource/1/data.parquet`)
```

2024-08-14 16:59 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  vid --> papr
```suggestion
  vid --> prrd
```

2024-08-14 16:59 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  papr --> arp : Add `path`\nproperty
```suggestion
  prrd --> arp : Add `path`\nproperty
```

2024-08-14 16:59 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  vrp : - Checks against spec
Yup! More likely ☺️

2024-08-14 16:59 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  condition --> vrp : If properties given
An error then 😛

2024-08-14 16:59 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  state "add_resource_properties()" as arp
```suggestion
  state "edit_resource_properties_field()" as arp
```

2024-08-14 16:59 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  vif : - Required arg: path
Hmm, I see what you mean, but this function could be used in other places, so doesn't make sense to call it `data_path`.

2024-08-14 16:59 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  erp : - Output: JSON
Hmm, I understand the confusion, but properties isn't a data type that you can output in Python. Both path and JSON are.

2024-08-14 16:59 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  return --> output
```suggestion
  state "join" <<join>>
  state "return" <<exitPoint>>
  vrp --> join
  arp --> join
  join --> return
  return --> output
```

@martonvago how is this?

2024-08-14 16:59 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  crp : - Needs user input if data_path given
```suggestion
  crp : - Conditional args: data_path or properties object
  crp : - Either data_path or properties must be given, not both
```

2024-08-14 16:59 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  state "add_resource_properties()" as arp
It would be adding a field to the properties. Maybe edit would be a better word.

2024-08-14 16:59 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  pcp --> vrp
@martonvago love it! Yea, I think that makes more sense. Also means we will need to expose a few more functions, like extractors and validators, in the core functions.

2024-08-14 16:59 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  pcp --> vrp
```suggestion
```

2024-08-15 09:56 UTC, martonvago commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  state "path_root_is_package()" as papr
I see what you mean about the dependency, but I guess that’s just how we designed the folder structure, so it’s kinda okay? (And I guess technically we could locate the `datapackage.json` of a package without knowing where it is nested under the package’s root directory.)

Ah okay, I see, true, we can add the path to the parquet file to `properties` without that file actually existing.

2024-08-15 10:01 UTC, martonvago commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  state "add_resource_properties()" as arp
Ah, what field? So not the path to the parquet file? (Sorry 😅 )

2024-08-15 10:02 UTC, martonvago commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  erp : - Output: JSON
Yeah, okay, I think I initially read this more in a conceptual way, if that makes sense

2024-08-15 10:11 UTC, martonvago commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  erp : - Output: JSON
Also, sorry for unresolving, but another related JSON question that has been at the back of my mind: 
So a piece of information in JSON is technically a string, right? So in Python this would actually be deserialised into a dictionary or a list, right?

So when we work with these JSON inputs/outputs in Python, would we pass them around as a string and deserialise and serialise them every time we process them, or would we actually pass them around as a dictionary/list?

2024-08-15 10:16 UTC, martonvago commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  condition --> vrp : If properties given
And I guess this would not arise anyway if we followed something like the design sketched out in the comment above about confirming properties with the user.

2024-08-15 11:54 UTC, martonvago commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  return --> output
Wait, so maybe I misunderstood what the output of `edit_resource_properties_field()` is. Is it the final `properties` of the resource? Because, in that case, I would have a single arrow pointing to `return`: the one coming from `edit_resource_properties_field()`. Because the `properties` output by `verify_resource_properties()` has yet to go through `edit_resource_properties_field()`. But I may well be misunderstanding this.

Based on my understanding, I would also expect an arrow from `extract_resource_properties()` to `edit_resource_properties_field()`.

2024-08-15 11:55 UTC, martonvago commented on docs/design/images/core-python-functions/create-resource-properties.svg
Does this need to be updated?

2024-08-15 12:00 UTC, martonvago commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  erp : - Output: JSON
Yes, my feeling would also be to pass them around as dicts because they're obviously easier to read, manipulate etc. And yes we could serialise them back to a JSON string whenever we needed to using that library.

(I also have some vague memories that `frictionless-py` actually handles lots of this (de)serialisation anyway.)

2024-08-15 12:44 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  erp : - Output: JSON
Yes, we would use the json package to handle these things so that they are always JSON objects ☺️

2024-08-15 12:46 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  state "add_resource_properties()" as arp
Yes, that is the field. The function would make it easier to edit a single field within the spec without needing to provide the full spec each time we want to make an edit.

2024-08-15 12:58 UTC, lwjohnst86 commented
@martonvago I've updated the diagram to make the arrows clearer about where they are going. Does that help?

2024-08-15 13:52 UTC, martonvago commented
> @martonvago I've updated the diagram to make the arrows clearer about where they are going. Does that help?

Yes!!! To me that makes sense 100% now, thanks :D

2024-08-15 13:53 UTC, martonvago approved these changes, later dismissed

2024-08-15 14:06 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  erp : - Output: JSON
Technically it would be a Python dictionary I guess. But always being parsed/validated as JSON

2024-08-16 08:00 UTC, K-Beicher reviewed
Looks good!

2024-08-16 11:04 UTC, signekb requested changes

2024-08-16 11:04 UTC, signekb commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  state "edit_resource_properties_field()" as erpf
Should this not be `create_`?

2024-08-16 11:50 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-properties.puml
> +  state "edit_resource_properties_field()" as erpf
No, because the field already exists. So we're editing something that is already there, though probably blank.

2024-08-16 12:06 UTC, signekb approved these changes, later dismissed

2024-08-16 12:22 UTC, merged