docs: :construction: draft of a guide to creating a package
seedcase-project/seedcase-sprout pull request #557
Opened 2024-08-12 20:26 UTC by lwjohnst86

## Description

It helps me to have an example documentation that describes how to use Sprout to organize things. This is a WIP draft on how to create your first package using either Python code or the CLI.

## Reviewer Focus

Since this is still WIP, it is very rough, but would love feedback!

2024-08-14 14:33 UTC, signekb reviewed
Love it :)

2024-08-14 14:33 UTC, signekb commented on docs/guide/packages.qmd
> +The first thing you'll need to decide is where you want to store all
```suggestion
The first thing you'll need to decide is where you want to store
```

2024-08-14 14:33 UTC, signekb commented on docs/guide/packages.qmd
> +Afterwards, you would create the structure for your first data package
```suggestion
Afterwards, you will create the structure for your first data package
```

2024-08-14 14:33 UTC, signekb commented on docs/guide/packages.qmd
> +    contributors=["Jamie Jones", "Jimmy James"],
```suggestion
    contributors=[{
  "title": "Jamie Jones",
  "email": "jamie_jones@example.com",
  "roles": ["creator"]}, 
  {"title": "Jimmy James",
  "email": "jimmy_james@example.com",
  "roles": ["contact"]
  }] 
```
To follow something like Data Package show in their docs [here](https://datapackage.org/standard/data-package/#contributors)

2024-08-14 14:33 UTC, signekb commented on docs/guide/packages.qmd
> +# Save the package properties back to the file
```suggestion
# Save the package properties to the datapackage.json file
```

2024-08-14 14:33 UTC, signekb commented on docs/guide/packages.qmd
> +sprout package create --title "Diabetes and Hypertension Study" \
Do we want `contributors` to be a required field? So there's always someone's name (preferably the creator of the package) in `datapackage.json`?

2024-08-14 16:05 UTC, lwjohnst86 commented on docs/guide/packages.qmd
> +sprout package create --title "Diabetes and Hypertension Study" \
I think we can decide on that when we actually get the full spec and incorporate it into the functions. I think we should download the full spec, show the full spec, and allow users to edit as needed. At least for now, make the required data package fields required by us as well, and decide/discuss as we go along for other fields.

2024-08-15 08:16 UTC, signekb commented on docs/guide/packages.qmd
> +sprout package create --title "Diabetes and Hypertension Study" \
Sounds like a good plan 👍 
About required fields: A Data Package is required to have the [resources](https://datapackage.org/standard/data-package/#resources) property. How will that work when creating a package? Will we create the Data Package with an empty resources property?

2024-08-15 09:27 UTC, lwjohnst86 commented on docs/guide/packages.qmd
> +sprout package create --title "Diabetes and Hypertension Study" \
That's right!

2024-08-15 11:42 UTC, signekb submitted a review, later dismissed

2024-08-16 07:09 UTC, K-Beicher reviewed
Very useful!

2024-08-16 12:50 UTC, martonvago requested changes
Very clear and useful!!

2024-08-16 12:50 UTC, martonvago commented on docs/guide/packages.qmd
> +to structuring and sharing data. This guide will show you how to create
```suggestion
of structuring and sharing data. This guide will show you how to create
```

2024-08-20 17:59 UTC, lwjohnst86 commented
I've did some small fixes and its ready to be reviewed again, though you don't need to review it that much ☺️

2024-08-26 08:51 UTC, signekb reviewed
Very nice! 👍 I have some questions and suggestions.

2024-08-26 08:51 UTC, signekb commented on docs/guide/packages.qmd
> +Afterwards, you will create the structure for your first data package by
```suggestion
Afterwards, you can create the structure for your first data package by
```

2024-08-26 08:51 UTC, signekb commented on docs/guide/packages.qmd
> +
Add something to explain what just happened?
... will the `datapackage.json` be empty initially?
```suggestion

This creates the initial structure of your new package with the ID `1`. The output above shows that the folder of your Data Package `1` has been created. This folder consists of two files: `datapackage.json` and `README.md`. The `datapackage.json` file is empty initially, but it will contain the metadata, a.k.a. the `properties`, of your Data Package. `README.md` is a prettified, human-readable version of the content of the `datapackage.json`.
```

2024-08-26 08:51 UTC, signekb commented on docs/guide/packages.qmd
> +  properties=sp.properties_json(
I don't recall seeing the `properties_json()` function in the core functions? Shouldn't it be included there?

2024-08-26 08:51 UTC, signekb commented on docs/guide/packages.qmd
> +```
Argh, the suggestion is cut off bc of the use of ``` to do the code blocks. 
```suggestion
```
To save the package properties to the `datapackage.json` file, run:

```
sp.write_package_properties(
  json_object=package_properties,
  path=sp.path_package_properties(package_id=1)
)
```
```

2024-08-26 08:51 UTC, signekb commented on docs/guide/packages.qmd
> +You will now have a new data package in the location you specified:
```suggestion
You now have the basic starting point for adding data resources to your data package in the location you specified:
```

2024-08-26 08:51 UTC, signekb commented on docs/guide/packages.qmd
> +
Again: Might be nice with some context abotu what they have just created?
```suggestion

This creates the initial structure of your new package with the ID `1`. The output above shows that the folder of your Data Package `1` has been created. This folder consists of two files: `datapackage.json` and `README.md`. The `datapackage.json` file is empty initially, but it will contain the metadata, a.k.a. the `properties`, of your Data Package. `README.md` is a prettified, human-readable version of the content of the `datapackage.json`.

```

2024-08-26 13:35 UTC, lwjohnst86 commented on _quarto.yml
> +        - section: "Guide"
I thought of that too, but Quarto uses Guide (https://quarto.org/docs/guide/). I guess it's because it's the guide for using Sprout. But in our other cases, its individual guides to work together/contribute.

2024-08-26 13:35 UTC, lwjohnst86 commented on docs/guide/packages.qmd
> +because you want to create some data packages for research studies you
Hmm, good point. I've used the capitalization wrong here. I'll fix that later. It should be lower case unless referring (and linking) directly to the website and standard.

2024-08-26 13:35 UTC, lwjohnst86 commented on docs/guide/packages.qmd
> +  properties=sp.properties_json(
Good point. I'll add it to the helper functions like `pretty_json()`.

2024-08-26 13:35 UTC, lwjohnst86 commented on docs/guide/packages.qmd
> +```
If you ever want to do something like that, add an extra backtick to the `suggestion` block. So it is wrapped with something like:

`````
````suggestion
````
`````

2024-08-26 14:14 UTC, signekb approved these changes, later dismissed

2024-08-26 15:16 UTC, martonvago approved these changes, later dismissed

2024-08-27 08:28 UTC, lwjohnst86 commented on _quarto.yml
> +        - section: "Guide"
We can always revise it if we don't like it 😁

2024-08-28 07:39 UTC, K-Beicher approved these changes, later dismissed
Looks good.

2024-08-28 13:03 UTC, merged