feat: ✨ add verify_is_directory()
seedcase-project/seedcase-sprout pull request #578
Opened 2024-08-19 15:00 UTC by signekb

## Description

These changes are done to start the work of creating the `create_resource_structure().

Closes #562 

## Reviewer Focus

This PR needs an in-depth review. Focus on:

1. Do we want to use `pathlib` and not `os`? 
2. I have added a new file `verify_is_directory.py` since I wasn't sure how we want to structure helper functions like this one. Where should it be located?
3. Tests: 
    1. How do we want to name them?
    2. Am I missing a test case?

## Checklist

- [X] Added or updated tests
- [X] Tests passed locally
- [X] Linted and formatted code
- [ ] Build passed locally
- [X] Updated documentation (yes: docstrings)

2024-08-20 11:39 UTC, signekb commented on tests/core/test_verify_is_directory.py
> +import pytest
```suggestion
from pytest import raises
```

2024-08-20 11:39 UTC, signekb commented on tests/core/test_verify_is_directory.py
> +    with pytest.raises(
```suggestion
    with raises(
```

2024-08-20 13:57 UTC, lwjohnst86 requested changes
Great start! Just some small comments.

2024-08-20 13:57 UTC, lwjohnst86 commented on sprout/core/verify_is_directory.py
> +        NotADirectoryError: If the path is not an existing directory
```suggestion
    Raises:
        NotADirectoryError: When the directory in the path doesn't exist.
```

Just some small grammar/language change.

2024-08-20 13:57 UTC, lwjohnst86 commented on sprout/core/verify_is_directory.py
> +    """Verifies if the path is an existing directory.
```suggestion
    """Verifies that directory given by the path exists or not.
```

2024-08-20 13:57 UTC, lwjohnst86 commented on sprout/core/verify_is_directory.py
> +        path if it's a directory
```suggestion
        A path object if it is a directory.
```

2024-08-20 13:57 UTC, lwjohnst86 commented on tests/core/test_verify_is_directory.py
> +    """
```suggestion
    """Test that the verify_is_directory function raises a NotADirectoryError
    if the directory does not exist."""
```

2024-08-20 13:59 UTC, martonvago requested changes
Nice, I didn't know about `tmp_path` 😁

2024-08-20 13:59 UTC, martonvago commented on tests/core/test_verify_is_directory.py
Maybe include a test for when the path points to a file?

2024-08-20 14:04 UTC, martonvago commented on sprout/core/verify_is_directory.py
> +    """Verifies if the path is an existing directory.
But "Verifies if/whether...", right? If it includes an "or"

2024-08-20 14:08 UTC, signekb commented on tests/core/test_verify_is_directory.py
Ah, good idea. Will do 👍

2024-08-20 14:11 UTC, signekb commented on tests/core/test_verify_is_directory.py
> +        match=r"/non_existent_directory is not an existing directory",
```suggestion
        match=r"/non_existent_directory doesn't exist.",
```

2024-08-20 14:13 UTC, signekb commented on tests/core/test_verify_is_directory.py
> +        match=r"/non_existent_directory doesn't exist.",
```suggestion
        match=r"/non_existent_directory directory doesn't exist.",
```

2024-08-21 09:35 UTC, signekb commented
@lwjohnst86 Ah, I see what you mean. Thanks for the tip!

2024-08-21 10:25 UTC, lwjohnst86 requested changes

2024-08-21 10:25 UTC, lwjohnst86 commented on tests/core/test_verify_is_dir.py
> +        match=r"/non_existent_directory directory doesn't exist.",
Is this message required? It feels like a brittle way of running the tests since if we make a change to the function, we also need to make a change to the test here.

2024-08-21 11:07 UTC, signekb commented on tests/core/test_verify_is_dir.py
> +        match=r"/non_existent_directory directory doesn't exist.",
You're right, it's not actually needed. We could either remove the `match` line altogether or we could only look for the "/non_existent_directory" match, like so: 
```suggestion
        match=r"/non_existent_directory",
```

2024-08-21 12:06 UTC, signekb commented on tests/core/test_verify_is_dir.py
> +    """Test that the verify_is_dir function returns the directory if it exists."""
```suggestion
    """Test the path is returned if the directory exists."""
```

2024-08-21 12:06 UTC, signekb commented on tests/core/test_verify_is_dir.py
> +    if the directory does not exist."""
```suggestion
    """Test that NotADirectoryError is raised if the directory doesn't exist."""
```

2024-08-21 12:06 UTC, signekb commented on tests/core/test_verify_is_dir.py
> +    if the directory does not exist."""
```suggestion
    """Test that NotADirectoryError is raised when a path to a file is given as input."""
```

2024-08-22 07:38 UTC, signekb commented on tests/core/test_verify_is_dir.py
> +        match=r"/non_existent_directory directory doesn't exist.",
I have implemented the suggestion above and kept only the last part of the input path in `match` 👍

2024-08-22 09:14 UTC, lwjohnst86 approved these changes
Lovely! So I guess the match is partially needed, at least to pick up the folder name.

2024-08-22 14:54 UTC, merged