feat: ✨ add get_ids()
seedcase-project/seedcase-sprout pull request #582
Opened 2024-08-20 09:40 UTC by signekb

## Description

These changes are done for PURPOSE, because REASON.

Closes #563 

## Reviewer Focus

This PR needs an in-depth review. 

Focus on:
- Regexes: Are they correct? Clear? 

## Checklist

- [X] Added or updated tests
- [X] Tests passed locally
- [X] Linted and formatted code
- [ ] Build passed locally
- [X] Updated documentation (=docstrings)

2024-08-20 09:41 UTC, signekb commented on tests/core/test_get_ids.py
> +    assert sorted(get_ids(tmp_path)) == [1, 20]
I sort here to ensure the output is in the expected order

2024-08-20 09:42 UTC, signekb commented on sprout/core/get_ids.py
> +        raise NotADirectoryError(f"{path} is not an existing directory")
I have added this like in the `verify_is_directory()` function to ensure `path` is a directory. But maybe that's actually not necessary here?

2024-08-20 17:26 UTC, lwjohnst86 requested changes
Very nice! I made some changes directly in the code because there was a test case that the code you wrote didn't catch. So I refactored it to fix it. Let me know what you think!

2024-08-20 17:26 UTC, lwjohnst86 commented on sprout/core/get_ids.py
> +    directories = list(path.glob("*/"))
The previous code didn't actually get only folders with numbers in them. So I revised it so the first step is keeping only directories.

2024-08-20 17:26 UTC, lwjohnst86 commented on sprout/core/get_ids.py
> +        return int(directory_name)
I created this function because the previous code didn't catch some test cases I added (see below). I also didn't understand some of the code, like why `.group(0)` was needed.

2024-08-21 08:17 UTC, martonvago requested changes

2024-08-21 08:17 UTC, martonvago commented on sprout/core/get_ids.py
> +def get_number(path: Path) -> int:
```suggestion
def get_number(path: Path) -> int | None:
```
Do we need this?

2024-08-21 08:17 UTC, martonvago commented on sprout/core/get_ids.py
> +    """
Do we need `Returns:...`?

2024-08-21 08:17 UTC, martonvago commented on tests/core/test_get_ids.py
> +    """Test that the get_ids function returns the directory if it exists."""
Is this description about this function?

2024-08-21 08:17 UTC, martonvago commented on tests/core/test_get_ids.py
> +def test_get_only_dirs_with_numbers(tmp_path):
Could be merged with `test_only_numbers_output`?

2024-08-21 08:17 UTC, martonvago commented on tests/core/test_get_ids.py
We could have a test for when there's a file with a numeric name? And for extensionless files?

2024-08-21 09:09 UTC, lwjohnst86 commented on tests/core/test_get_ids.py
> +    """Test that the get_ids function returns the directory if it exists."""
Oops, it was copy pasted from an old test.

2024-08-21 09:11 UTC, lwjohnst86 requested changes

2024-08-21 09:11 UTC, lwjohnst86 commented on tests/core/test_get_ids.py
> +    """Test that the get_ids function returns the directory if it exists."""
```suggestion
    """Return an empty list when there are no IDs."""
```

2024-08-21 09:11 UTC, lwjohnst86 commented on sprout/core/get_ids.py
> +    """
```suggestion
      path: Directory to extract the number from.
    
    Returns:
    	An single integer for the ID.
    """
```

2024-08-22 09:16 UTC, lwjohnst86 approved these changes
Very nice :grin:

2024-08-22 15:03 UTC, merged