feat: :sparkles: add generate_next_id function
seedcase-project/seedcase-sprout pull request #585
Opened 2024-08-20 11:37 UTC by martonvago

## Description

This adds the `generate_next_id` function.

Closes #564 

## Reviewer Focus

This PR needs a quick review.

## Checklist

- [x] Added or updated tests
- [x] Tests passed locally
- [x] Linted and formatted code
- [x] Build passed locally
- [x] Updated documentation

2024-08-20 11:38 UTC, martonvago commented on sprout/core/generate_next_id.py
I'm not doing any checks on the argument here (because we're using type hinting and `mypy`), but let me know if I should.

2024-08-20 12:02 UTC, martonvago commented on tests/core/test_generate_next_id.py
Because of not explicitly checking for input type in the implementation, I'm also not testing for errors in the tests. I think it would be inconsistent to check e.g. that `generate_next_id([1, 2, "three"])` throws a `TypeError` (which it does because of `max(...)`), but not to check that it rejects `False` as an input (which it doesn't because it is falsey). But again, let me know if I should do it differently.

2024-08-20 12:18 UTC, signekb reviewed
Very nice!

2024-08-20 12:18 UTC, signekb commented on sprout/core/generate_next_id.py
> +def generate_next_id(existing_ids: list[int]) -> int:
To simplify - i.e., not use a new action - should we call this `create_next_id()` instead?

2024-08-20 12:18 UTC, signekb commented on sprout/core/generate_next_id.py
I think it makes sense to omit checks like that. 
These functions would not be called on their own, but always be called by the outer function, e.g., `create_resource_structure()`, right? 
But I'm not sure where we should put limit as to how much we should test for functions like this...

2024-08-20 13:16 UTC, martonvago commented on sprout/core/generate_next_id.py
> +def generate_next_id(existing_ids: list[int]) -> int:
Sure, done!

2024-08-20 14:06 UTC, lwjohnst86 requested changes
🎉 Very nice, only some small edits!

2024-08-20 14:06 UTC, lwjohnst86 commented on tests/core/test_create_next_id.py
> +    """
```suggestion
    """Given no existing IDs, it should return 1."""
```

2024-08-20 14:06 UTC, lwjohnst86 commented on tests/core/test_create_next_id.py
> +    assert create_next_id([1]) == 2
```suggestion
def test_create_next_id_creates_second_id_correctly():
    """Given one existing ID, it should return that ID + 1."""
    assert create_next_id([1]) == 2
```

2024-08-21 11:01 UTC, lwjohnst86 approved these changes

2024-08-21 11:44 UTC, signekb approved these changes

2024-08-22 14:56 UTC, merged