feat/create dir
seedcase-project/seedcase-sprout pull request #586
Opened 2024-08-20 11:50 UTC by K-Beicher

## Description

These changes are done for PURPOSE, because REASON.

Closes #566 

## Reviewer Focus

This PR needs an in-depth review. The first function I've made, I'm fairly sure I've done it correctly.

## Checklist

- [x] Added or updated tests
- [x] Tests passed locally
- [x] Linted and formatted code
- [ ] Build passed locally
- [x] Updated documentation (docstrings)

2024-08-20 14:11 UTC, lwjohnst86 requested changes
Very nice! Only very small edits for the docstrings 🎉

2024-08-20 14:11 UTC, lwjohnst86 commented on tests/core/test_create_dir.py
> +    """
```suggestion
    """Checks for an existing folder and returns the name
    if the folder already exists.
    """
```

Don't need the documentation for arguments in tests

2024-08-20 15:33 UTC, lwjohnst86 requested changes
Very nice! I made some small changes, mainly in allowing the function to create several directories at once rather than one at a time.

2024-08-20 15:33 UTC, lwjohnst86 commented on sprout/core/create_dirs.py
> +def create_dirs(path: list[Path]) -> list[Path]:
I converted this function to create multiple directories when given a list of paths. I pushed these changes rather than through the PR suggestions since I needed to test that it worked as I expected, plus because it involved several changes.

2024-08-21 08:25 UTC, K-Beicher commented
@seedcase-project/developers Just thinking about this function, and what it should do, if it encounters a directory that already exists.

1/ does it go back and informs the user that it is already there (and may already contain data)

2/ does it just confirm that the directory is created, and ignores the fact that it wasn't created now.

This becomes a bit more tricky if we are talking about more than one directory (as Luke's mod allows), what happens if one of several directories exists.

1/ goes back and informs about the one that is already there and then:
1a/ doesn't create the rest of them
1b/ creates the rest of the directories

2/ creates the new directories and confirms that all directories are now in place.

PS We need more tests if it is to run more than one directory at a time.

2024-08-21 09:21 UTC, martonvago commented on sprout/core/create_dirs.py
> +        return path
Is this different from doing `path.mkdir(parents=True, exist_ok=True)`? Because it will just skip existing directories (and not recreate them), right?

2024-08-21 09:42 UTC, K-Beicher commented on sprout/core/create_dirs.py
> +        return path
I wasn't actually sure about it skipping them, and in the meantime I've realised that we may want to talk about what we want to do if the directory is actually already there... Do we want to let the user know that the name is already potentially in use?

2024-08-21 10:23 UTC, lwjohnst86 commented
To answer the first question, this is an internal function so no user interaction is expected so we don't need to inform on anything.

My feeling is, if any directory already exists, it throws an error about creating it so no directories are created in the end. Which would mean we would need to run `verify_is_dir()` before actually creating the dirs.

2024-08-21 11:22 UTC, signekb requested changes

2024-08-21 11:22 UTC, signekb commented on sprout/core/create_dirs.py
> +    """Creates directories from a list of directories.
```suggestion
    """Creates directories from a list of paths.
```

2024-08-21 11:22 UTC, signekb commented on sprout/core/create_dirs.py
> +        NoDirectoryError: If the directory wasn't created
Should this be NotADirectoryError?
```suggestion
        NotADirectoryError: If the directory wasn't created
```

2024-08-21 11:22 UTC, signekb commented on sprout/core/create_dirs.py
> +        NoDirectoryError: If the directory wasn't created
```suggestion
        NotADirectoryError: If the directory wasn't created
```
?

2024-08-21 11:22 UTC, signekb commented on tests/core/test_create_dirs.py
Do we need tests for if the input is a not a directory? Like a file path, `tmp_path / "file.py" ?

2024-08-22 06:10 UTC, K-Beicher commented on sprout/core/create_dirs.py
> +        NoDirectoryError: If the directory wasn't created
I think it is short for 'no directory was created', so No is correct...?

2024-08-22 06:20 UTC, K-Beicher commented on tests/core/test_create_dirs.py
We definitely need more tests!

2024-08-22 08:22 UTC, signekb commented on sprout/core/create_dirs.py
> +        NoDirectoryError: If the directory wasn't created
I was thinking more in the sense that if we think about when this function would raise an error, it would be if the input `path` is not a directory, right? 

`NotADirectoryError` is also a built-in exception, see the docs [here](https://docs.python.org/3/library/exceptions.html#NotADirectoryError), whereas the `NoDirectoryError` is a custom exception. And it might be nicer to use the built-in exceptions when it makes sense for us to do so :)

2024-08-22 09:06 UTC, lwjohnst86 commented on tests/core/test_create_dirs.py
@signekb when making directories, the computer doesn't care about the name. So the "extension" would be added to the created directory: `package/file.py/`. Extensions are just arbitrary names, it just so happens that computers often use the ending of a file name to decide which program to use to open that particular file. But if you remove the, e.g., `.zip` file extension from a file, the file itself remains a zip file. With directories, at the computer level they are classified as directories, not as files, so the computer will always interpret them as directories regardless of the file name. This type of test would still pass and wouldn't add any useful information for us.

2024-08-22 11:43 UTC, signekb commented on tests/core/test_create_dirs.py
Ah, yes! I actually discovered that yesterday as well 😅 But thanks for elaborating!

2024-08-22 11:49 UTC, K-Beicher commented
@signekb I think I've got the error handling to work now.

2024-08-22 11:50 UTC, K-Beicher commented on tests/core/test_create_dirs.py
> +    """Checks for an existing directory and returns the name
@lwjohnst86 This fails when testing locally, do we need it?

2024-08-23 09:02 UTC, martonvago requested changes
Nice!! 😁 Just some comments

2024-08-23 11:39 UTC, K-Beicher commented on sprout/core/create_dirs.py
> +        raise NotADirectoryError(f"Failed to create directory: {path}")
You are right, I'm trying to catch the situation where the directory wasn't created even though the mkdir was executed. I'll see if I can rewrite to make that more clear.

2024-08-23 11:40 UTC, K-Beicher commented on sprout/core/create_dirs.py
> +def create_dirs(path: list[Path]) -> list[Path]:
This wasn't written by me, but by @lwjohnst86. I'm going to assume that the plural won't mess up the code and correct it.

2024-08-23 11:40 UTC, K-Beicher commented on sprout/core/create_dirs.py
> +        removes any directories already created.
I'll get that re-worded.

2024-08-23 11:41 UTC, K-Beicher commented on tests/core/test_create_dirs.py
> +    assert len(result) == len(new_dir)
Again, this bit was made by @lwjohnst86, I'll leave this one for him to resolve.

2024-08-23 11:42 UTC, K-Beicher commented on tests/core/test_create_dirs.py
> +    """Create a new directory and returns the path correctly."""
It is, I'll get it sorted.

2024-08-23 11:43 UTC, K-Beicher commented on tests/core/test_create_dirs.py
> +    assert len(result) == len(new_dirs)
again, I'll leave this one to @lwjohnst86.

2024-08-23 12:21 UTC, martonvago commented on sprout/core/create_dirs.py
> +        raise NotADirectoryError(f"Failed to create directory: {path}")
And do we want to catch the error here because we want to change what kind of error it is? Because `FileExistsError` already includes the path in the error message, so one option is to just let that bubble up to the caller without catching it here.

2024-08-23 12:24 UTC, K-Beicher commented on sprout/core/create_dirs.py
> +        raise NotADirectoryError(f"Failed to create directory: {path}")
Not entirely sure, sorry - over to @lwjohnst86 and @signekb

2024-08-23 14:20 UTC, lwjohnst86 requested changes
Nice discussions here! I've made some suggested changes that I think will clean up things and answer/address many of @martonvago comments.

2024-08-23 14:20 UTC, lwjohnst86 commented on sprout/core/create_dirs.py
> +            raise
```suggestion
		created_dirs = [create_dir(path) for path in paths]
```

Just to keep it cleaner 😁  and since we don't need to do the error anymore.

2024-08-23 14:20 UTC, lwjohnst86 commented on tests/core/test_create_dirs.py
> +    """Checks for an existing directory and returns the name
True. So we could rewrite this test then.

2024-08-23 14:20 UTC, lwjohnst86 commented on tests/core/test_create_dirs.py
> +    assert len(result) == len(temp_dirs)
```suggestion
		with pytest.raises(FileExistsError):
				create_dirs(temp_dirs)
```

2024-08-23 14:20 UTC, lwjohnst86 commented on tests/core/test_create_dirs.py
> +from sprout.core.create_dirs import create_dirs
```suggestion
import pytest
from sprout.core.create_dirs import create_dirs
```

2024-08-26 12:09 UTC, signekb commented on tests/core/test_create_dirs.py
> +    assert result == new_dirs
I just tested a bit locally what happens if this function gets an existing directory as input path: It raises `FileExistsError`. @lwjohnst86 is that the wanted behaviour? 

I have added a passing test here. 

```suggestion
    assert result == new_dirs

def test_raise_error_with_existing_dir(tmp_path):
    """Raise FileExistsError when the input path is an existent directory."""
    # Create a temporary directory
    new_dir = [tmp_path / "new_dir"]
    new_dir[0].mkdir()

    with raises(
        FileExistsError,
    ):
        create_dirs(new_dir)

```

2024-08-26 12:28 UTC, K-Beicher commented on sprout/core/create_dirs.py
> +    The path has already been verified as not existing.
That may be me not being entirely clear. As I understand conversations with @lwjohnst86 the idea is that a 'verify' function has been run and confirmed that there is no directory of that name (ie path), so it will need to be created. Thus there is no reason for throwing an error if the directory can't be created, which is what I was trying to say with this sentence.

2024-08-26 13:18 UTC, lwjohnst86 commented on tests/core/test_create_dirs.py
> +    assert result == new_dirs
I think that's fine. Since it is an internal function, we can assume we won't create things that already exist. But yea, this test is fine 👍🏻

2024-08-26 13:20 UTC, lwjohnst86 commented on sprout/core/create_dirs.py
> +    The path has already been verified as not existing.
@K-Beicher has it right 🦾 We will rarely use this function without running verify first. It doesn't need to be within this function since we'll often be using verify for other purposes. So we don't need to run it twice.

2024-08-26 13:23 UTC, lwjohnst86 submitted a review, later dismissed

2024-08-26 13:44 UTC, martonvago commented on tests/core/test_create_dirs.py
> +    new_dir = [tmp_path / "new_dir"]
For me I think it comes down to there being something semantically incorrect about calling a list object a `dir` because it creates false expectations about what methods I can call on it or what I can assert about it. The same for indexing into that list: `dir[0]` just doesn’t read as an object referring to a directory, it reads as some constituent part of a directory. But all this is very very parenthetical of course 😁

2024-08-26 14:00 UTC, martonvago requested changes
Just a missing import

2024-08-26 14:04 UTC, martonvago approved these changes

2024-08-26 14:16 UTC, signekb approved these changes

2024-08-27 08:16 UTC, merged