feat: ✨ add create_resource_raw_dir
seedcase-project/seedcase-sprout pull request #587
Opened 2024-08-20 12:02 UTC by signekb

## Description

These changes are done for PURPOSE, because REASON.

Closes #567 

## Reviewer Focus

This PR needs an in-depth review. Focus on: 

- Which other tests do we need here?

## Checklist

- [X] Added or updated tests
- [X] Tests passed locally
- [X] Linted and formatted code
- [ ] Build passed locally
- [X] Updated documentation (=docstrings)

2024-08-20 14:45 UTC, lwjohnst86 requested changes
Very nice! I made some small changes, so that we can make a more generic `create_dirs()` function to use throughout core.

2024-08-21 09:17 UTC, signekb reviewed
The changes you made, @lwjohnst86, make sense 👍 
I can't approve, since I created the PR - but if I could, I would ✅

2024-08-21 09:30 UTC, martonvago requested changes

2024-08-21 09:30 UTC, martonvago commented on sprout/core/create_resource_raw_path.py
> +        path: Directory to create the new resource directory in.
```suggestion
        path: Directory to create the new raw directory in.
```
Just because there's some ambiguity in "new resource directory" -- could be read as the directory for a specific resource and then its parent directory would be the resources folder.

2024-08-21 09:42 UTC, martonvago submitted a review, later dismissed

2024-08-22 09:18 UTC, lwjohnst86 approved these changes
🎉

2024-08-22 14:57 UTC, merged