docs: :memo: update create-resource-structure diagram
seedcase-project/seedcase-sprout pull request #589
Opened 2024-08-20 13:04 UTC by martonvago

## Description

This updates the `create-resource-structure` diagram to reflect the current sequence of inner functions.

Closes #

## Reviewer Focus

This PR needs a quick review.

## Checklist

- [x] Added or updated tests
- [x] Tests passed locally
- [x] Linted and formatted code
- [x] Build passed locally
- [x] Updated documentation

2024-08-20 14:32 UTC, lwjohnst86 reviewed
I made some small edits, let me know what you think!

2024-08-20 14:32 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-structure.puml
> +  crp --> crrp
I converted this into a function to create a path object, so that we can have a generic create dir function.

2024-08-20 14:32 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-resource-structure.puml
> +  cd : - Output: list of paths of created\n  directories
I converted this into a function that takes a list of paths to create and returns a list. I don't know if the creating directories is a functional/vectorised, otherwise, we will have to update the function when we make it.

2024-08-21 09:34 UTC, martonvago commented on docs/design/images/core-python-functions/create-resource-structure.puml
> +  cd : - Output: list of paths of created\n  directories
Nice, makes sense!

2024-08-21 11:30 UTC, signekb commented on docs/design/images/core-python-functions/create-resource-structure.puml
>    arg --> vid
I think `verify_is_directory` should be changed to `verify_is_dir` now :)

2024-08-22 09:07 UTC, lwjohnst86 submitted a review, later dismissed
Nice!

2024-08-22 11:54 UTC, signekb requested changes
Very nice! We have renamed another function in the meantime (sorry 😁 )

2024-08-22 11:54 UTC, signekb commented on docs/design/images/core-python-functions/create-resource-structure.puml
> +  state "create_resource_path()" as crp
```suggestion
  state "create_id_path()" as crp
```
Sorry for renaming another function 😅

2024-08-22 11:54 UTC, signekb commented on docs/design/images/core-python-functions/create-resource-structure.puml
> +  state "create_resource_path()" as crp
Maybe update `crp` to `cip` as well?

2024-08-22 11:54 UTC, signekb commented on docs/design/images/core-python-functions/create-resource-structure.puml
Just a thought: Do we need to return the `resources/<id>` path when we return `resources/<id>/raw`?

2024-08-22 11:54 UTC, signekb commented on docs/design/images/core-python-functions/create-resource-properties.puml
Shouldn't `extract_resource_properties()` be followed by `verify_resource_properties` before going to `edit_resource_properties_field`? 
Sorry, I know this isn't relevant to your change, but seeing the diagram again made me think about it :)

2024-08-23 07:40 UTC, martonvago commented on docs/design/images/core-python-functions/create-resource-properties.puml
I think that was the way it was at some point. I think it kinda made sense to change it because when you extract properties using Frictionless then they're guaranteed to be valid, right? Unless we want to do more involved verification than just checking if it's a valid Frictionless resource.

2024-08-23 07:43 UTC, martonvago commented on docs/design/images/core-python-functions/create-resource-structure.puml
I thiiiink I may have asked the same question [here](https://github.com/seedcase-project/seedcase-sprout/pull/549#discussion_r1716632166)

2024-08-23 07:51 UTC, martonvago commented on docs/design/images/core-python-functions/create-resource-structure.puml
> +  state "create_resource_path()" as crp
👍

2024-08-23 13:23 UTC, signekb commented on docs/design/images/core-python-functions/create-resource-properties.puml
Yessss, you're right! Also asked Luke about it. We'll leave it as is ⭐

2024-08-23 13:24 UTC, signekb approved these changes

2024-08-23 14:32 UTC, lwjohnst86 approved these changes
🎉

2024-08-23 14:33 UTC, merged