feat: :sparkles: add verify_format_supported function
seedcase-project/seedcase-sprout pull request #592
Opened 2024-08-22 07:15 UTC by martonvago

## Description

This adds the `verify_format_supported` function.

Closes #572 

## Reviewer Focus

This PR needs a quick review.

## Checklist

- [x] Added or updated tests
- [x] Tests passed locally
- [x] Linted and formatted code
- [x] Build passed locally
- [x] Updated documentation

2024-08-22 07:18 UTC, martonvago commented on sprout/core/verify_format_supported.py
> +                     "geojson", "topojson", "ods", "parq", "parquet"]
I’ve included the ones where the Frictionless [page](https://v4.framework.frictionlessdata.io/docs/references/plugins-reference) explicitly says that they have stable support for the format, plus parquet (which wasn’t mentioned on that page), but there are many others with varying levels of support ([code](https://github.com/frictionlessdata/frictionless-py/tree/main/frictionless/formats), [docs](https://github.com/frictionlessdata/frictionless-py/tree/main/docs/formats)).

2024-08-22 07:19 UTC, martonvago commented on sprout/core/verify_format_supported.py
> +                     "geojson", "topojson", "ods", "parq", "parquet"]
For now, I put them here as a list, but we may well move this somewhere else later or change it into an enum etc.

2024-08-22 07:21 UTC, martonvago commented on sprout/core/verify_format_supported.py
> +class UnsupportedFormatError(Exception):
Not sure if we want to have an errors/exceptions folder, so just leaving it here for now.
Also not sure if we have any preference about calling it an error vs an exception -- they seem to be used somewhat interchangeably in Python?

2024-08-22 07:25 UTC, martonvago commented on sprout/core/verify_format_supported.py
> +    return path
I couldn't find a Frictionless function that checked the format, so I'm doing it "by hand". In fact, it seems like Frictionless will process any file regardless of the extension, but obviously it can't extract the (table) schema from all files.

2024-08-23 08:18 UTC, signekb approved these changes
Very nice work 🎉

2024-08-23 08:18 UTC, signekb commented on sprout/core/verify_format_supported.py
> +        message = f"File format '{format}' is not supported."
Would it be helpful to add the formats we actually support in the message?

2024-08-23 08:18 UTC, signekb commented on sprout/core/verify_format_supported.py
> +class UnsupportedFormatError(Exception):
I'm not sure how many custom exceptions we'll need eventually, but maybe it's fine to keep it here for now? 

I think when we have created the helper functions for `create_package_structure()`, `create_package_properties()` as well as the one's were working on now (`create_resource_structure()` and `create_resource_properties()`), we'll have a better overview of what kind of folder structure we need. 
At that time, we could spend some time to refactor accordingly? :)

2024-08-23 08:27 UTC, signekb commented on sprout/core/verify_format_supported.py
Following the name of `verify_is_file()` and `verify_is_dir()`, could/should this function actually be named `verify_is_supported_format()`?

2024-08-23 08:34 UTC, signekb requested changes

2024-08-23 08:34 UTC, signekb commented on sprout/core/verify_format_supported.py
Following the name of `verify_is_file()` and `verify_is_dir()`, could/should this function actually be named `verify_is_supported_format()`?

2024-08-23 11:17 UTC, martonvago commented on sprout/core/verify_format_supported.py
Sure!

2024-08-23 14:29 UTC, lwjohnst86 approved these changes
Very nice!!!

2024-08-23 14:29 UTC, lwjohnst86 commented on sprout/core/verify_format_supported.py
> +def verify_format_supported(path: Path) -> Path:
```suggestion
def verify_is_format_supported(path: Path) -> Path:
```

2024-08-23 14:29 UTC, lwjohnst86 commented on tests/core/test_verify_format_supported.py
> +    verify_format_supported,
```suggestion
    verify_is_supported_format,
```

2024-08-23 14:29 UTC, lwjohnst86 commented on tests/core/test_verify_format_supported.py
> +from sprout.core.verify_format_supported import (
```suggestion
from sprout.core.verify_is_supported_format import (
```

You'll need to rename the files after though.

2024-08-23 14:30 UTC, merged