feat: :sparkles: add extract_resource_properties function
seedcase-project/seedcase-sprout pull request #594
Opened 2024-08-22 15:04 UTC by martonvago

## Description

This adds the `extract_resource_properties` function.

Closes #573 

## Reviewer Focus

This PR needs a quick review.

## Checklist

- [x] Added or updated tests
- [x] Tests passed locally
- [x] Linted and formatted code
- [x] Build passed locally
- [x] Updated documentation

2024-08-23 07:25 UTC, martonvago commented on sprout/core/extract_resource_properties.py
This will extract resource properties, including, if possible, a table schema with basic information on the fields/columns (name, data type). It looks like more detailed information (e.g. constraints, whether a string is an enum) have to be added by hand.

2024-08-23 07:31 UTC, martonvago commented on tests/core/test_extract_resource_properties.py
- Given that we're passing a file of the correct format to this function (and, in any case, all kinds of file formats are processed by `describe`), I couldn't make it throw an error in an obvious way, so I'm not testing for that.
- I'm also not sure if testing for all our supported formats here makes sense (for some we would need libraries to construct the data files), so for now I just added csv and json.
- Once we have more tests like these, it might make sense to commonise the data file creation logic.

2024-08-26 13:47 UTC, lwjohnst86 requested changes
This is a fantastic! Given that we'll need to expose this function (see #605), this function could be renamed to `extract_properties_from_file()` as per the internal diagram given in the linked PR.

2024-08-27 07:41 UTC, signekb commented on tests/core/test_extract_properties_from_file.py
> +    """Given a JSON file, it should extract resource properties without a schema."""
Oh, so frictionless-py can't  extract the schema from`json`?

2024-08-27 07:41 UTC, signekb approved these changes
Looks great 🎉 🎉

2024-08-27 08:02 UTC, martonvago commented on tests/core/test_extract_properties_from_file.py
> +    """Given a JSON file, it should extract resource properties without a schema."""
I think the schema might be for tabular data specifically and I guess you wouldn't give that kind of data as json? But I still have some reading to do about what frictionless-py can do with what formats 😅

2024-08-27 08:17 UTC, lwjohnst86 approved these changes
🎉

2024-08-27 08:18 UTC, merged

2024-08-27 10:53 UTC, signekb commented on tests/core/test_extract_properties_from_file.py
> +    """Given a JSON file, it should extract resource properties without a schema."""
Same! I think you're right :)