docs: :memo: add description for an extract function
seedcase-project/seedcase-sprout pull request #603
Opened 2024-08-23 18:18 UTC by lwjohnst86

## Description

These changes add a description for an extraction of properties function for data files. This function needs to be exposed to the user, especially since it needs to be exposed to be used properly for the web app. It also simplifies the `create_resource_properties()` function a lot!

## Reviewer Focus

This PR needs an in-depth review.

2024-08-26 11:51 UTC, martonvago requested changes
Makes lots of sense!

2024-08-26 11:51 UTC, martonvago commented on docs/design/python-functions.qmd
> +function. Usually, you use either this function or the
```suggestion
any remaining missing fields and then the `verify_resource_properties()`
function. Usually, you use either this function or the
```

2024-08-26 11:51 UTC, martonvago commented on docs/design/python-functions.qmd
> +resource; Outputs a JSON object, use `write_resource_properties()` to
```suggestion
`path_resource()` to help give the correct path. Outputs a JSON object,
use `write_resource_properties()` to
```

2024-08-26 14:07 UTC, martonvago approved these changes, later dismissed

2024-08-27 07:34 UTC, signekb reviewed
Nice! 
Just a few minor language things and a question for my own understanding :)

2024-08-27 07:34 UTC, signekb commented on docs/design/python-functions.qmd
> +points to the resource `id` folder the properties are for; use
```suggestion
points to the resource `id` folder; use
```

2024-08-27 07:34 UTC, signekb commented on docs/design/python-functions.qmd
> +use `write_resource_properties()` to
```suggestion
`path_resource()` to help give the correct path. Outputs a JSON object.
Use `write_resource_properties()` to
```

2024-08-27 07:34 UTC, signekb commented on docs/design/python-functions.qmd
> +`create_resource_properties()` function to create the resource
So, just for my own understanding: Would `create_resoure_properties()` be for when you don't have a data file to extract from?

2024-08-27 07:40 UTC, K-Beicher reviewed
Looks sensible to me.

2024-08-27 08:20 UTC, lwjohnst86 commented on docs/design/python-functions.qmd
> +`create_resource_properties()` function to create the resource
Yea, exactly. Like you know what data will eventually look like, but haven't got it yet and you want to prepare the resource.

2024-08-27 10:33 UTC, merged

2024-08-27 11:50 UTC, signekb commented on docs/design/python-functions.qmd
> +`create_resource_properties()` function to create the resource
Amazing. Thanks 👍