feat: ✨ add `create_resource_structure()`
seedcase-project/seedcase-sprout pull request #610
Opened 2024-08-27 09:34 UTC by signekb

## Description

These changes are done for PURPOSE, because REASON.

Closes #568 

Relates to #533 

## Reviewer Focus

This PR needs an in-depth review. 

Focus on CHANGES: 

1. How do we want to import internal functions to user-facing functions like `create_resource_structure()`? This also relates to general refactoring; right now all core functions are in the same folder which will become messy as we add new functions. Thoughts at this point? Do we want to keep as is for now and then wait for a refactoring session later on?

## Checklist

- [X] Added or updated tests
- [X] Tests passed locally
- [X] Linted and formatted code
- [X] Updated documentation (=docstrings)

2024-08-27 12:06 UTC, signekb commented
Hmmmm..... The tests don't fail locally

2024-08-28 08:32 UTC, martonvago approved these changes, later dismissed
Looking very nice ⭐ ⭐ 

Only thing I can think of is maybe adding a test for the case when there is already a resource and so the ID has to be > 1.

Personally, I’m happy to move the functions into folders later when we have a bit more of them. But yeah, maybe group them by functions related to packages, resources, verification? And then commonly used functions of course.

I’ve never really managed to develop an amazing understanding of how Python imports should be organised (consistently, I guess 😄), so maybe Luke?

2024-08-28 11:14 UTC, K-Beicher commented
Looks good, I'm a big fan of putting things away in folders, but I'm also of the opinion that sometimes it is best to wait a little, until you can see a pattern emerging and make folders based on that. So again - let's see what @lwjohnst86 has to say :-)

2024-08-28 11:41 UTC, martonvago requested changes, later dismissed

2024-08-28 11:41 UTC, martonvago commented on tests/core/test_create_resource_structure.py
> +def test_returns_resource_structure_when_no_resources_exists(tmp_path):
```suggestion
def test_returns_resource_structure_when_no_resources_exist(tmp_path):
```
Sorry 😅

2024-08-28 11:41 UTC, martonvago commented on tests/core/test_create_resource_structure.py
> +def test_returns_resource_structure_when_resources_exists(tmp_path):
```suggestion
def test_returns_resource_structure_when_resources_exist(tmp_path):
```

2024-08-28 12:09 UTC, lwjohnst86 requested changes, later dismissed
Fuck yeaaasss! Only have one comment 😁

2024-08-28 12:09 UTC, lwjohnst86 commented on sprout/core/create_resource_structure.py
> +
Only thing to add would be the documentation from the python functions doc. Eventually, all the docs there should be over with the actual functions. That way we can automatically build the website docs from these docs.

2024-08-28 12:11 UTC, lwjohnst86 commented
@signekb and I am also of the similar opinion as the others. I think keeping them all in the same folder works for now and explicit importing of needed functions 👍🏻

2024-08-28 12:43 UTC, signekb commented on tests/core/test_create_resource_structure.py
> +def test_returns_resource_structure_when_no_resources_exists(tmp_path):
Haha, no reason to say sorry, @martonvago ! Thanks for the catch 👍

2024-08-28 12:48 UTC, signekb commented on sprout/core/create_resource_structure.py
> +
Do you mean this section, @lwjohnst86 ? How should we keep links in these?  

> This is the first function to use to set up the structure for a data resource. It creates the paths for a new data resource in a specific (existing) package by creating the folder setup described in the [Outputs](https://sprout.seedcase-project.org/docs/design/outputs) section. Use the path_resources() function to provide the correct path location. It creates two paths: the resources/<id>/ path and the resources/<id>/raw/ path. The output is a list of these two path objects.

2024-08-28 13:26 UTC, lwjohnst86 commented on sprout/core/create_resource_structure.py
> +
Yea, exactly that one ☺️ And links... Hmm, I think a full URL will have to do for now. I think there's a way to do it internally but I'll need to read more about how that's done in the doc generator.

2024-08-28 13:47 UTC, martonvago approved these changes

2024-08-28 14:05 UTC, lwjohnst86 approved these changes

2024-08-28 14:05 UTC, merged