feat: :sparkles: add verify_resource_properties
seedcase-project/seedcase-sprout pull request #613
Opened 2024-08-27 17:07 UTC by martonvago

## Description

This adds `verify_resource_properties`.

Closes #574 

## Reviewer Focus

This PR needs an in-depth review.

## Checklist

- [x] Added or updated tests
- [x] Tests passed locally
- [x] Linted and formatted code
- [x] Build passed locally
- [x] Updated documentation

2024-08-27 17:08 UTC, martonvago commented on sprout/core/verify_resource_properties.py
> +        )
This is a bit verbose, but maybe that's helpful

2024-08-27 17:13 UTC, martonvago commented on sprout/core/verify_resource_properties.py
> +        errors = [
When there are multiple errors they are not actually guaranteed all to be listed in here unfortunately. This is because some errors throw an exception internally when Frictionless does the validation and that prevents other errors from being listed.

2024-08-27 17:15 UTC, martonvago commented on tests/core/test_verify_resource_properties.py
> +    assert "123 is not of type 'string' at property 'format'" in message
I saw this pattern on the `pytest` github and thought it was nice

2024-08-28 06:34 UTC, martonvago commented on sprout/core/verify_resource_properties.py
> +            for error in report.errors
When there are multiple errors they are not actually guaranteed all to be listed in here unfortunately. This is because some errors throw an exception internally when Frictionless does the validation and that prevents other errors from being listed.

2024-08-28 06:47 UTC, martonvago commented on sprout/core/verify_resource_properties.py
> +        )
This is a bit verbose, but maybe that's helpful?

2024-08-28 07:38 UTC, K-Beicher reviewed
I'm going to leave it to others to read through and comment, but it looks convincing to me, and it works on my local machine

2024-08-28 12:25 UTC, lwjohnst86 requested changes
Very very nice! ⭐ 🎉 Only one small comment 😁

2024-08-28 12:25 UTC, lwjohnst86 commented on sprout/core/verify_resource_properties.py
> +            for error in report.errors
Could you add a TODO note in the code about this? So we know to return to it.

2024-08-28 12:25 UTC, lwjohnst86 commented on sprout/core/verify_resource_properties.py
> +        )
Nothing wrong with verbose and descriptive error messages! 😁

2024-08-28 12:25 UTC, lwjohnst86 commented on tests/core/test_verify_resource_properties.py
> +    assert "123 is not of type 'string' at property 'format'" in message
Really nice! 🤩

2024-08-28 13:26 UTC, signekb submitted a review, later dismissed
Very nice 🌟

2024-08-28 14:12 UTC, lwjohnst86 approved these changes

2024-08-28 14:13 UTC, merged