feat: ✨ add `write_file()`
seedcase-project/seedcase-sprout pull request #631
Opened 2024-08-29 14:32 UTC by signekb

## Description

Closes #618 

## Reviewer Focus

This PR needs an in-depth review. Focus on CHANGES.

## Checklist

- [X] Added or updated tests
- [X] Tests passed locally
- [X] Linted and formatted code
- [X] Build passed locally
- [X] Updated documentation (=docstrings)

2024-08-30 07:59 UTC, martonvago requested changes
Niiiiice 😁

2024-08-30 07:59 UTC, martonvago commented on sprout/core/write_file.py
And then would we dump the `dict`s into the argument like `write_file(path, json.dumps(properties))`?

2024-08-30 07:59 UTC, martonvago commented on tests/core/test_write_file.py
> +    assert file_path.is_file() is True
```suggestion
    assert file_path.is_file()
```

2024-08-30 07:59 UTC, martonvago commented on sprout/core/write_file.py
> +    """Writes a file to the given path with the given content.
Maybe include here that the directory structure specified by the path has to exist (i.e. that this will fail if the parent dir doesn't exist)? Or otherwise add a test for that failure

2024-09-02 08:01 UTC, signekb commented on sprout/core/write_file.py
@lwjohnst86 would it be incorrect to call this function `create_file()` to avoid having one function with this action?

2024-09-02 08:05 UTC, signekb commented on sprout/core/write_file.py
That would be my guess, yes!

2024-09-02 11:05 UTC, lwjohnst86 commented on sprout/core/write_file.py
Yup, that makes sense 🦾

2024-09-02 11:06 UTC, lwjohnst86 commented on sprout/core/write_file.py
> +    """Writes a file to the given path with the given content.
Both! 😁

2024-09-02 11:09 UTC, lwjohnst86 requested changes

2024-09-02 11:09 UTC, lwjohnst86 commented on sprout/core/write_file.py
> +    """Writes a file to the given path with the given content.
```suggestion
def write_file(string: str, path: Path) -> Path:
    """Writes a file to the given path with the given content.
```

When writing, the path should always be after the string, so as to pipe the output into the function's first position (as is done in R's `|>` and in bash's `|`). I know Python doesn't really have a pipe (😢) but it's good to think in that framing.

2024-09-02 11:09 UTC, lwjohnst86 commented on sprout/core/write_file.py
> +        string: Content to be written to the file.
```suggestion
        string: Content to be written to the file.
        path: Path of the file to be created, including file name and extension.
```

Just to match the order.

2024-09-02 11:09 UTC, lwjohnst86 commented on tests/core/test_write_file.py
> +    assert write_file(file_path, file_content) == file_path
```suggestion
    assert write_file(file_content, file_path) == file_path
```

2024-09-02 11:09 UTC, lwjohnst86 commented on tests/core/test_write_file.py
> +    assert write_file(file_path, file_content) == file_path
```suggestion
    assert write_file(file_content, file_path) == file_path
```

2024-09-02 11:49 UTC, signekb commented on sprout/core/write_file.py
> +    """Writes a file to the given path with the given content.
Added 👍

2024-09-02 12:16 UTC, lwjohnst86 approved these changes
🎉

2024-09-02 12:17 UTC, merged