feat: :sparkles: add create_resource_properties
seedcase-project/seedcase-sprout pull request #633
Opened 2024-08-30 15:05 UTC by martonvago

## Description

This adds `create_resource_properties`.

Closes #577 

## Reviewer Focus

This PR needs an in-depth review.

## Checklist

- [x] Added or updated tests
- [x] Tests passed locally
- [x] Linted and formatted code
- [x] Build passed locally
- [x] Updated documentation

2024-08-30 15:08 UTC, martonvago commented on sprout/core/create_resource_properties.py
> +        resource properties
Alternatively, we could remap all errors coming from here into a `FailedToCreatePropertiesError`, but we may actually want to keep them separate to be able to handle them separately later.

2024-08-30 15:18 UTC, martonvago commented on sprout/core/create_resource_properties.py
> +    return edit_resource_properties_field(properties, "path", str(data_path))
Converting `data_path` to string because a `Path` can't be serialised to json automatically. If we keep doing similar conversions when using `edit_resource_properties_field`, we could consider moving the conversion in there (but we would need to ask what types we want to allow for values in `properties`).

2024-08-30 15:25 UTC, martonvago commented on sprout/core/create_resource_properties.py
> +    `create_resource_structure()`.
Was I supposed to copy this in from the function description?

2024-08-30 15:38 UTC, lwjohnst86 approved these changes
Super nice! Just some small comments

2024-08-30 15:38 UTC, lwjohnst86 commented on sprout/core/create_resource_properties.py
> +    `create_resource_structure()`.
You got it!!! 🌠

2024-08-30 15:38 UTC, lwjohnst86 commented on sprout/core/create_resource_properties.py
> +    the fields given in the `properties` argument to fill them and prepare
The description for the args here should be moved to the arg description section.

2024-08-30 15:38 UTC, lwjohnst86 commented on sprout/core/create_resource_properties.py
> +    return edit_resource_properties_field(properties, "path", str(data_path))
hmmm, interesting. Let's see how other conversions happen and modify as needed.

2024-08-30 15:38 UTC, lwjohnst86 commented on sprout/core/create_resource_properties.py
Now that #626 has been merged, can you uncomment this function from that list?

2024-08-30 15:39 UTC, lwjohnst86 requested changes
Ops, clicked approve by mistake.

2024-09-02 10:14 UTC, martonvago commented on sprout/core/__init__.py
> +from .create_resource_properties import create_resource_properties
Like this? With just `import *` the formatter was unhappy

2024-09-02 10:58 UTC, lwjohnst86 commented on sprout/core/__init__.py
> +from .create_resource_properties import create_resource_properties
You got it! Yea, the formatter doesn't like those `*`...

2024-09-02 11:05 UTC, lwjohnst86 requested changes

2024-09-02 11:05 UTC, lwjohnst86 commented on sprout/core/create_resource_properties.py
> +        that follows the Frictionless Data Package standard
```suggestion
        path: the path to the resource `id` folder; use `path_resource()`
        	to provide the correct path or use the output of `create_resource_structure()`
        properties: the properties of the resource; must be given as a
        	JSON object following the Data Package specification; use
        	`view_resource_properties_template()` to get a JSON object
        	that follows the Frictionless Data Package standard
```

As per the Google style guide.

2024-09-02 11:05 UTC, lwjohnst86 commented on sprout/core/create_resource_properties.py
> +        resource properties
I think keeping them separate for now makes sense.

2024-09-02 13:19 UTC, signekb requested changes
Nice 🎈 Only docstring things and a question for Luke.

2024-09-02 13:19 UTC, signekb commented on sprout/core/create_resource_properties.py
> +            `create_resource_structure()`
Just looked it up in Google's style guide and it seems that we should remember `.` in docstrings - see e.g., the examples under [Functions and Methods](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods) in their docs.
```suggestion
            `create_resource_structure()`.
```

2024-09-02 13:19 UTC, signekb commented on sprout/core/create_resource_properties.py
> +            that follows the Frictionless Data Package standard
```suggestion
            that follows the Frictionless Data Package standard.
```

2024-09-02 13:19 UTC, signekb commented on sprout/core/create_resource_properties.py
> +        NotADirectoryError: if path does not point to a directory
```suggestion
        NotADirectoryError: if path does not point to a directory.
```

2024-09-02 13:19 UTC, signekb commented on sprout/core/create_resource_properties.py
> +        resource properties
```suggestion
        resource properties.
```

2024-09-02 13:19 UTC, signekb commented on sprout/core/create_resource_properties.py
> +        the properties object, verified and updated
It also seems from [these examples](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods) that the Raises section should be after Returns.

2024-09-02 13:19 UTC, signekb commented on sprout/core/create_resource_properties.py
Ah, so this function doesn't write the resource properties to `datapackage.json`? Are we missing a `write` function for this in the Core functions, @lwjohnst86 ?

2024-09-02 13:55 UTC, martonvago commented on sprout/core/create_resource_properties.py
> +        the properties object, verified and updated
Hmmm, this was generated by the `njpwerner.autodocstring` extension, but that could be wrong

2024-09-02 14:46 UTC, lwjohnst86 commented on sprout/core/create_resource_properties.py
We aren't missing it, it's called [`write_resource_properties()`](https://sprout.seedcase-project.org/docs/design/python-functions#write_resource_propertiesproperties-path) ☺️

2024-09-03 08:00 UTC, signekb requested changes

2024-09-03 08:00 UTC, signekb commented on sprout/core/create_resource_properties.py
> +        resource properties.
Sorry for being hyper-focused on the docstring styling 😁 
```suggestion
            resource properties.
```

2024-09-03 08:17 UTC, lwjohnst86 approved these changes

2024-09-03 08:17 UTC, merged