docs: :building_construction: internal flow for `create_package_properties()`
seedcase-project/seedcase-sprout pull request #664
Opened 2024-09-03 08:23 UTC by lwjohnst86

## Description

These changes add the internal flow diagram.

Closes #627

## Reviewer Focus

This PR needs an in-depth review.

2024-09-03 10:17 UTC, signekb requested changes
Quite simple and straightforward 👌 
I do have some trouble grasping what will be in the properties file already (from `create_package_structure()` that uses `create_properties_template()` and what will be added here? Do you mind elaborating a bit on that?

2024-09-03 10:17 UTC, signekb commented on docs/design/images/core-python-functions/create-package-properties.puml
> +  state "join_properties()" as jp
Coudl/should this be `edit_*` or `update_*` instead?

2024-09-03 10:17 UTC, signekb commented on docs/design/images/core-python-functions/create-package-properties.puml
> +  jp : - Required args: current and new
```suggestion
  jp : - Required args: current_properties and new_properties
```

2024-09-03 11:09 UTC, martonvago reviewed
Thanks, makes sense!

My questions are pretty similar to Signe's: are the current contents of `datapackage.json` the contents of the template (with maybe some values filled in)? Or I guess it's possible that the user manually edited the file in the meantime. When combining the properties, will the new ones take precedence if there's a clash?

2024-09-04 09:29 UTC, lwjohnst86 commented
@signekb I'm not completely sure what might already be in the JSON file, that's something we'll have to discuss once we have something tangible to discuss around and modify. But I could think of some things that might already be in the file, like `id`, `$schema`, and `created`. And yes @martonvago right to both first questions. We can't necessarily assume the user has directly edited the file or not. And yes, we always assume the new is intended to overwrite the old/current.

2024-09-04 09:30 UTC, lwjohnst86 commented on docs/design/images/core-python-functions/create-package-properties.puml
> +  state "join_properties()" as jp
For sure! Update would work.

2024-09-04 14:42 UTC, martonvago commented
> @signekb I'm not completely sure what might already be in the JSON file, that's something we'll have to discuss once we have something tangible to discuss around and modify. But I could think of some things that might already be in the file, like `id`, `$schema`, and `created`. And yes @martonvago right to both first questions. We can't necessarily assume the user has directly edited the file or not. And yes, we always assume the new is intended to overwrite the old/current.

Okay, makes sense, thanks!

2024-09-05 07:46 UTC, martonvago commented on docs/design/implementation/images/core/create-package-properties.puml
> +  state "update_properties()" as up
This is somewhat related to `create_properties_template`, but what do we want to do with unfilled properties? I.e. optional properties left empty both in `current_properties` and `new_properties`. I guess we don't want to keep them around, so drop them?

2024-09-05 07:46 UTC, martonvago commented on docs/design/implementation/images/core/create-package-properties.puml
> +  up : - Required args: current_properties\n  and new_properties
I just thought of this, but what if the user really edited `current_properties` and now it is not valid -- should we validate the final `properties` to make sure?

2024-09-05 08:27 UTC, lwjohnst86 commented on docs/design/implementation/images/core/create-package-properties.puml
> +  state "verify_package_properties()" as vpp
Yea, I'm thinking we will want to require more from the user than Frictionless does.

2024-09-05 08:27 UTC, lwjohnst86 commented on docs/design/implementation/images/core/create-package-properties.puml
> +  state "update_properties()" as up
Hmm, good question. My instinct is to leave them in but have a default value of `""` or something similar. I personally like knowing what else is missing in a formal spec like this.

2024-09-05 08:27 UTC, lwjohnst86 commented on docs/design/implementation/images/core/create-package-properties.puml
> +  up : - Required args: current_properties\n  and new_properties
Within `read_properties()` there should ideally be something to verify that it is a valid property file.

2024-09-05 09:09 UTC, martonvago commented on docs/design/implementation/images/core/create-package-properties.puml
> +  state "verify_package_properties()" as vpp
Okay, makes sense! (Then I'd be inclined to add that logic in our `verify...` functions)

2024-09-05 09:11 UTC, martonvago commented on docs/design/implementation/images/core/create-package-properties.puml
> +  state "update_properties()" as up
Okay, if we're talking about a manageable set of properties (as we discussed today), then that works I think

2024-09-09 08:52 UTC, lwjohnst86 commented on docs/design/implementation/images/core/create-package-properties.puml
> +  state "verify_package_properties()" as vpp
Do you mean include combine this verify as well as the required properties one below into the one function? Or what do you mean by adding that logic?

2024-09-09 12:16 UTC, martonvago commented on docs/design/implementation/images/core/create-package-properties.puml
> +  state "verify_package_properties()" as vpp
I mean add an extra check within `verify_package_properties` that checks if all required properties are present. I think that would make sense because Frictionless already checks for its required properties there, so we would just be checking our own as well.

2024-09-09 13:22 UTC, signekb approved these changes, later dismissed
Makes sense to me 👍

2024-09-09 13:22 UTC, signekb commented on docs/design/implementation/images/core/create-package-properties.puml
> +  state "update_properties()" as up
@martonvago Hello, it's me again, trying to catch up ☺️  What do you mean by a "manageable set of properties"?

2024-09-09 13:39 UTC, martonvago commented on docs/design/implementation/images/core/create-package-properties.puml
> +  state "update_properties()" as up
Ah yeah, sorry, not obvious without context: looking at the [package schema](https://datapackage.org/profiles/2.0/datapackage.json), if we wanted to include absolutely all properties all the way down the hierarchy (so everything under package > resource > schema), that would be very many properties, most of which would go unused. So we talked about only including the ones we need from the top 2 levels (package, resource) -- which is more manageable.

2024-09-09 13:49 UTC, signekb commented on docs/design/implementation/images/core/create-package-properties.puml
> +  state "update_properties()" as up
Ah, thanks! That makes a lot more sense!

2024-09-09 14:59 UTC, merged