feat: create readme text
seedcase-project/seedcase-sprout pull request #669
Opened 2024-09-03 11:58 UTC by K-Beicher

first version of both function and test

## Description

These changes are done for PURPOSE, because REASON.

Closes #617 

## Reviewer Focus

This PR needs an in-depth review. 

I'm not sure I've picked the correct argument to pass in, or that we want the readme file to be structured this way. Also, there is only a test to make sure that it works.

## Checklist

- [x] Added or updated tests
- [x] Tests passed locally
- [x] Linted and formatted code
- [x] Build passed locally
- [x] Updated documentation (docstring)

2024-09-09 09:04 UTC, lwjohnst86 requested changes

2024-09-09 09:04 UTC, lwjohnst86 commented on sprout/core/create_readme_text.py
> +        f"{json.dumps(json_object, indent=4)}"
This is a good start, but will need a bit more customization since we don't want a direct copy paste of the machine-readable JSON in the human-readable README. So for instance, the README title could be something like:

```
properties = json.loads(json_object)
resources = # Python code to convert the resource details in the dict as 
	# a Markdown list.
...
	f"# {properties.name}: {properties.title}\n\n"
	f"{properties.description}\n\n"
	f"Within this data package contains:\n\n"
	f"{properties.resources}
...
```

2024-09-09 09:04 UTC, lwjohnst86 commented on sprout/core/create_readme_text.py
> +def create_readme_text(json_object: json) -> str:
I'm wondering if it is better to call this `properties` instead of `json_object` 🤔 Others thoughts?

2024-09-09 13:05 UTC, signekb commented on sprout/core/create_readme_text.py
> +def create_readme_text(json_object: json) -> str:
I agree! `properties` is aligned with what we call it elsewhere

2024-09-09 14:08 UTC, martonvago requested changes

2024-09-09 14:08 UTC, martonvago commented on sprout/core/create_readme_text.py
> +def create_readme_text(json_object: json) -> str:
Agreed, and it should be type `dict`. (The `json` there is the JSON library)

2024-09-09 14:08 UTC, martonvago commented on tests/core/test_create_readme_text.py
> +    json_object = json.loads(json_string)
So I think the input to this function is a regular Python dictionary object, so we could just pass `{"name": "My Package", "version": "1.0.0", "description": "Sample"}` directly.

2024-09-11 12:04 UTC, K-Beicher commented on sprout/core/create_readme_text.py
> +def create_readme_text(json_object: json) -> str:
@lwjohnst86 Do we have an example of what the json is likely to look like, I was struggling with visualising that before, and still is, although that could be the remnants of covid as well. I agree that properties is a good idea, and that it could be a dict type.

2024-09-11 17:39 UTC, lwjohnst86 requested changes

2024-09-11 17:39 UTC, lwjohnst86 commented on sprout/core/create_readme_text.py
> +def create_readme_text(json_object: json) -> str:
@K-Beicher yea, since we don't have that object yet, it's hard for all of us to visualize it. I think for now we can keep it pretty simple and not assume too much, since we'll probably have to make a lot of changes, especially to this function, along the way.

2024-09-11 17:39 UTC, lwjohnst86 commented on sprout/core/create_readme_text.py
> +def create_readme_text(json_object: json) -> str:
```suggestion
def create_readme_text(properties: dict) -> str:
```

2024-09-11 17:39 UTC, lwjohnst86 commented on sprout/core/create_readme_text.py
> +      json_object: A JSON object containing the package properties template
```suggestion
    """Create a string to use for the README file.

    Args:
      properties: An object containing the package and resource properties.
```

2024-09-11 17:39 UTC, lwjohnst86 commented on sprout/core/create_readme_text.py
> +      A string with the README text
```suggestion
      A string for the README text.
```

2024-09-11 17:39 UTC, lwjohnst86 commented on sprout/core/create_readme_text.py
> +        f"{json.dumps(json_object, indent=4)}"
@K-Beicher if you add something like the above for now, we can merge this in and update it as we go along ☺️

2024-09-17 06:37 UTC, K-Beicher commented on tests/core/test_create_readme_text.py
> +    json_object = json.loads(json_string)
Hi @martonvago How will this work with the new layout of the function?

2024-09-17 06:38 UTC, K-Beicher commented on sprout/core/create_readme_text.py
> +    # a Markdown list.
@lwjohnst86 it is of course now complaining about the resources being not defined here...

2024-09-17 06:40 UTC, K-Beicher commented on sprout/core/create_readme_text.py
> +    properties = json.loads(properties)
@lwjohnst86 in your first review you'd left the json_object in the (), I may have misunderstood, but we've since agreed that it should be renamed to properties...

2024-09-17 14:14 UTC, lwjohnst86 requested changes

2024-09-17 14:14 UTC, lwjohnst86 commented on tests/core/test_create_readme_text.py
> +    json_object = json.loads(json_string)
@K-Beicher we haven't changed anything related to the input, we still expect a `dict` object, so that doesn't change anything.

2024-09-17 14:14 UTC, lwjohnst86 commented on tests/core/test_create_readme_text.py
> +    )
This will need to be updated :relaxed:

2024-09-18 07:36 UTC, K-Beicher commented
@lwjohnst86 I've removed the test file so we can get the main script merged in.

2024-09-23 11:49 UTC, lwjohnst86 commented on sprout/core/create_readme_text.py
> +        f"{properties.resources}"
I wonder if it will be easier to create this text in a Markdown file with templating, like done with Django and the `jinja` used to create the template Property dataclasses... :thinking:

2024-09-24 06:06 UTC, K-Beicher commented on sprout/core/create_readme_text.py
> +        f"{properties.resources}"
I'll have a look at that.

2024-09-25 11:58 UTC, martonvago requested changes
Sorry to start on this again, I was just having a look at https://github.com/seedcase-project/seedcase-sprout/issues/619 and realised this needed some more changes.

2024-09-25 11:58 UTC, martonvago commented on sprout/core/create_readme_text.py
> +    properties = json.loads(properties)
```suggestion
```

Here we don't need to load `properties` from a string because it's already a `dict`.

2024-09-25 11:58 UTC, martonvago commented on sprout/core/create_readme_text.py
> +        f"{properties.resources}"
```suggestion
        f"{properties["name"]}: {properties["title"]}\n\n"
        f"Within this data package contains:\n\n"
        f"{properties["resources"]}"
```
Here we cannot access fields using a dot because `properties` is just a dictionary. If we passed `properties` as a `PackageProperties` we could use the dot notation. (Maybe we'll do that later, but I think for now everything else expects a `dict`.)

2024-10-03 12:37 UTC, lwjohnst86 commented on sprout/core/create_readme_text.py
> +        f"{properties["resources"]}"
```suggestion
        f"# {properties["name"]}: {properties["title"]}\n\n"
        f"properties["description"]\n\n"
        f"There are {len(properties["resources"])} resources in this package."
```

2024-10-03 12:38 UTC, merged