docs: 📝 add `create_properties_object()`
seedcase-project/seedcase-sprout pull request #686
Opened 2024-09-10 12:57 UTC by signekb

## Description

Replacing `create_package_properties()` used internally in `create_package_structure()`.

## Reviewer Focus

This PR needs a quick review.

Focus on CHANGES.

## Checklist

- [X] Updated documentation

2024-09-11 14:43 UTC, martonvago reviewed
Makes sense, just some questions/points that we don't necessarily have to answer for this PR:
- What is `create_properties_object` doing with the `path` argument?
- We'll have to think about whether we want to pass our properties around as dataclasses or as dictionaries (= json objects). My feeling is to go for dataclasses because then we benefit from their reliable structure and can put any package or resource-specific logic in those classes. But there may be arguments against this?
- I think it makes sense to include this step in the diagram as a conceptual step, but in terms of the actual code, this might just turn out to be a class instantiation (i.e. `package = Package(id=id)` or `package = asdict(Package(id=id))` if we want a dictionary)?

2024-09-11 16:39 UTC, lwjohnst86 requested changes
@martonvago good observations!

For the second point, I agree, I think data classes would be right way to go and I don't see any strong arguments against it.

For your third point, I think that isn't necessary given the text of `create_properties_object()`, but it could be made a bit clearer to say "properties dataclass is initialized internally" or something.

2024-09-12 14:57 UTC, signekb commented on docs/design/implementation/images/core/create-package-structure.puml
>    cd --> cppt
@lwjohnst86 I'm not sure what you mean here. Should I remove `create_properties_object()` from this diagram completely? And then we'll just initialise the dataclass with default values within `create_package_structure()`? Or do we want a function for that initialisation?

2024-09-12 15:29 UTC, lwjohnst86 requested changes
@signekb these suggestions hopefully make it clearer what I meant ☺️

2024-09-12 15:29 UTC, lwjohnst86 commented on docs/design/implementation/images/core/create-package-structure.puml
>    cppt : - Required arg: path
```suggestion
```

2024-09-12 15:29 UTC, lwjohnst86 commented on docs/design/implementation/images/core/create-package-structure.puml
```suggestion

```

2024-09-12 15:47 UTC, signekb commented
@lwjohnst86 Amazing, yes, that definitely made it clearer. Thanks! 
What about the outputs and inputs of JSON objects in this diagram? Should that be changed to the `Properties` class?

2024-09-16 09:46 UTC, lwjohnst86 commented
@signekb for now, we'll refer to outputs/inputs as JSON, but this might change once we finalize and implement the properties as dataclasses

2024-09-16 09:47 UTC, lwjohnst86 approved these changes

2024-09-16 09:51 UTC, merged