feat: ✨ add `create_root_path()`
seedcase-project/seedcase-sprout pull request #689
Opened 2024-09-11 12:11 UTC by signekb

## Description

Closes #681 

## Reviewer Focus

This PR needs an in-depth review.

Focus on CHANGES.

## Checklist

- [X] Added or updated tests
- [X] Tests passed locally
- [X] Linted and formatted code
- [X] Updated documentation (=docstrings)

2024-09-11 12:12 UTC, signekb commented on sprout/core/create_root_path.py
> +    root_path = user_data_path("sprout")
If we want it to be created if it doesn't exist, we can add the argument [`ensure_exists=True`](https://platformdirs.readthedocs.io/en/latest/api.html#platformdirs.api.PlatformDirsABC.ensure_exists)

2024-09-11 12:16 UTC, signekb commented on tests/core/test_create_root_path.py
> +from sprout.core.create_root_path import create_root_path
Am I missing some test cases? 
E.g., would we expect that it already exist at this point?  I.e., `.exists() is True`?

2024-09-11 12:19 UTC, signekb commented on sprout/core/create_root_path.py
> +    root_path = user_data_path("sprout")
This doesn't create the directory; just the path

2024-09-11 16:59 UTC, lwjohnst86 requested changes
Looks great! Only a very minor change.

2024-09-11 16:59 UTC, lwjohnst86 commented on tests/core/test_create_root_path.py
> +    """Returns root path o."""
```suggestion
    """Returns root path."""
```

?

2024-09-11 16:59 UTC, lwjohnst86 commented on tests/core/test_create_root_path.py
> +from sprout.core.create_root_path import create_root_path
I think this is fine for now ☺️ One of the main purposes of tests are also to just make sure it runs! 😛

2024-09-12 13:20 UTC, martonvago requested changes
Nice 👍 👍 !!

2024-09-12 13:20 UTC, martonvago commented on sprout/core/create_root_path.py
> +    return root_path
```suggestion
    return user_data_path("sprout")
```
Could just return this directly

2024-09-12 13:35 UTC, signekb commented on sprout/core/create_root_path.py
> +    return root_path
You're right! ⭐

2024-09-13 09:12 UTC, martonvago approved these changes

2024-09-13 14:29 UTC, lwjohnst86 approved these changes

2024-09-13 14:30 UTC, merged