docs: :memo: expand on usage guide for Properties class
seedcase-project/seedcase-sprout pull request #690
Opened 2024-09-11 19:02 UTC by lwjohnst86

## Description

This is a draft of how a `Properties()` class might be used in practice.

Also did some reformatting of the Markdown.

## Reviewer Focus

This PR needs a quick review.

2024-09-13 10:03 UTC, martonvago reviewed
Super useful!! Just some questions 😅

2024-09-13 11:34 UTC, lwjohnst86 commented on docs/guide/packages.qmd
> +first use the `create_package_properties()` function:
Do you have other names you could think of to differentiate these two?

2024-09-16 08:44 UTC, martonvago commented on docs/guide/packages.qmd
> +first use the `create_package_properties()` function:
Hmm, so we can’t really rename the class. As for the function, something like `update_package_properties`? Seeing that the function takes a `PackageProperties` object and merges it with existing package properties in `datapackage.json`. In theory this function should be able to update `datapackage.json` between versions anyway (there’s nothing in it that depends on `datapackage.json` just having been created).

2024-09-16 08:51 UTC, lwjohnst86 commented on docs/guide/packages.qmd
> +first use the `create_package_properties()` function:
Hmm, that's a good point! Ok, I'll update these to be update package properties and then make a new PR with renaming `create_` to `update_` :tada:

2024-09-16 13:28 UTC, signekb requested changes

2024-09-16 13:28 UTC, signekb commented on docs/guide/packages.qmd
> +`~/.sprout/packages/` on Linux (see
```suggestion
`~/sprout/packages/` on Linux (see
```
Right?

2024-09-16 13:28 UTC, signekb commented on docs/guide/packages.qmd
> +While you *could* manually fill in the details in the `datapackage.json`
```suggestion
While you *can* manually fill in the details in the `datapackage.json`
```

2024-09-16 13:28 UTC, signekb commented on docs/guide/packages.qmd
> +
```suggestion
Then, to update the current `datapackage.json` file with these properties, you can use the `update_package_properties()` function:

```

2024-09-16 13:28 UTC, signekb commented on docs/guide/packages.qmd
> +The `create_package_properties()` function will give an error if the
```suggestion
The `update_package_properties()` function will give an error if the
```
? ☺️

2024-09-16 13:28 UTC, signekb commented on docs/guide/packages.qmd
> +required fields are not filled in to create a valid data package.
```suggestion
required fields are not filled in to create a valid `datapackage.json` file.
```

2024-09-16 13:28 UTC, signekb commented on docs/guide/packages.qmd
> +documentation for the `Properties()` class or run
```suggestion
documentation for the `Properties` classes or run
```

2024-09-16 13:28 UTC, signekb commented on docs/guide/packages.qmd
> +fill in.
```suggestion
e.g., `print(sp.PackageProperties)` to get a list of all the fields you can
fill in for a package.
```

2024-09-16 15:10 UTC, lwjohnst86 commented on docs/guide/packages.qmd
> +::::: panel-tabset
I am not using anything new... So weird. Really need to have our own reformatter...

2024-09-17 07:11 UTC, K-Beicher reviewed
This makes sense to me.

2024-09-18 07:10 UTC, K-Beicher commented on docs/guide/packages.qmd
> +documentation for the `PackageProperties` classes or run
Do we know that the intended users of the document knows how to do this?

2024-09-23 08:39 UTC, lwjohnst86 commented on docs/guide/packages.qmd
> +documentation for the `PackageProperties` classes or run
The documentation link will be provided afterwards by a link to our docs, which (should theoretically) be able to be autogenerated and autolinked.

2024-09-23 08:39 UTC, merged