docs: :memo: revised section on properties to be only about the class
seedcase-project/seedcase-sprout pull request #691
Opened 2024-09-11 19:07 UTC by lwjohnst86

## Description

If we have this class, it will replace all these other functions. I haven't written much in them since they would basically be a 1-to-1 relationship with the spec itself.

## Reviewer Focus

This PR needs a quick review.

2024-09-12 13:35 UTC, lwjohnst86 commented on docs/design/implementation/python-functions.qmd
> +### `Properties(...)`
The problem is you can't nest dataclasses, at least not that I could see from the documentation. You can set a field in one dataclass as another dataclass, but the dataclass is created as a top level class, not a subclass of another dataclass. We could write our own code to do that, but it looks complicated and I don't see the value of that.

2024-09-12 13:41 UTC, signekb commented on docs/design/implementation/python-functions.qmd
> +### `Properties(...)`
Ah, that is actually also what I meant. Like 
```
class Package: 
	...
	resources: list[Resource] = field(default_factory=list)
	...

@dataclass
class Resource: 
	title: str 
	... 
```

I'm not sure I understand why we would need the `Properties` level still?

2024-09-12 14:45 UTC, signekb commented on docs/design/implementation/python-functions.qmd
> +### `Properties(...)`
So `Properties` would look something like this? ☺️ 
```
class Properties: 
	Package: Package
	Resource: Resource
	...
```

2024-09-12 16:10 UTC, lwjohnst86 commented
@martonvago and @signekb I've taken the feedback and split the properties into individual dataclasses as well as added some example usage, just so it is a bit clearer what they would do/be used for.

2024-09-13 12:50 UTC, martonvago requested changes
Sorry for the novel 😅

2024-09-13 12:50 UTC, martonvago commented on docs/design/implementation/python-functions.qmd
> +### `Properties(...)`
Sorry, just trying to catch up with this:
- You can nest dataclasses as far as I can see. I think you can define a class basically anywhere you want in Python.
- Nested classes are not subclasses of the outer class. If we wanted subclasses we would use inheritance. Inheritance would e.g. allow us to share logic between classes.
- I think the two contending ways of organising the classes are currently:
1. Separate classes:
```python
@dataclass
class SourceProperties:
    title: str = ""
    ...

# similar for ContributorProperties, LicenseProperties

@dataclass
class ResourceProperties:
    sources: list[SourceProperties] = field(default_factory=list)
    ...

@dataclass
class PackageProperties:
    resources: list[ResourceProperties] = field(default_factory=list)
    ...
```
I think this is fairly clear.

2. Nested classes:
```python
@dataclass
class Properties:

    @dataclass
    class Source:
        title: str = ""
        ...

    # similar for Contributor, License

    @dataclass
    class Resource:
        sources: list["Properties.Source"] = field(default_factory=list)
        ...

    @dataclass
    class Package:
        resources: list["Properties.Resource"] = field(default_factory=list)
        ...
```
Here, the nesting is purely organisational, as `Properties` does not really correspond to anything by itself, does not represent a "whole" that consists of "parts" -- which is usually what class nesting expresses in other languages, I think. I initially felt a bit uneasy about whether this was a semantically correct use of class nesting, but now I think it's fine to do if it helps us ([relevant, but not decisive discussion](https://stackoverflow.com/questions/3576596/is-it-a-good-idea-to-using-class-as-a-namespace-in-python)).

2024-09-16 08:27 UTC, signekb requested changes

2024-09-16 08:27 UTC, signekb commented on docs/design/implementation/python-functions.qmd
> +LicenseProperties(...)
```suggestion
LicenseProperties(name=None, path=None, title=None)
```

2024-09-16 08:27 UTC, signekb commented on docs/design/implementation/python-functions.qmd
> +TableSchemaProperties(...)
```suggestion
TableSchemaProperties(fields=[], missingValues=[], primaryKey=[], foreignKeys=[])
```
Or something like this? ☺️

2024-09-16 10:29 UTC, martonvago approved these changes, later dismissed

2024-09-16 10:31 UTC, merged