[don't merge] use datamodel-codegen to generate classes based on spec
seedcase-project/seedcase-sprout pull request #692
Opened 2024-09-12 12:21 UTC by martonvago

## Description

This is to show what it would look like if we used [datamodel-code-generator](https://github.com/koxudaxi/datamodel-code-generator) to extract class definitions from the [spec](https://datapackage.org/profiles/2.0/datapackage.json). I'm sure the output can be customised a bit more and where it puts the file would need to be decided etc., but I wanted to get some feedback on this rough draft to see if this is something we should work more on.

We can also have a script post-process the output if we think it's useful, but there are some things we want to rearrange.

## Reviewer Focus

This PR needs an in-depth review.

Focus on the output generated by the library -- would this make our life easier?

## Checklist

- [ ] Added or updated tests
- [ ] Tests passed locally
- [ ] Linted and formatted code
- [ ] Build passed locally
- [ ] Updated documentation

2024-09-12 12:40 UTC, martonvago commented on properties.py
These are the class definitions extracted from the JSON schema. 
As you can see, there are some questionable things, e.g.:
- The file is ridiculously long because the entire data package schema was processed, including the table schema and the different types of table fields. Plus, many objects in the schema can have a range of different types (with different sets of properties), which are represented as different classes here.
- Not all class attributes are documented and some explanations could be improved a bit / given more context. The docstrings come after the class attributes -- this seems to follow an older convention and it wasn't obvious to me if there's a newer one.
- There are many more or less duplicate definitions, such as `License`, `License1`, `License2`, `License3`.

2024-09-12 13:33 UTC, signekb commented on properties.py
I definitely see the potential in something like this! 

But it might depend on how much/how complex post processing it would need. For example:
- how do we want to structure the classes/dataclasses - which seems a bit up in the air right now
- how all-in do we want to go on having classes for the spec. Like do we actually want classes for different constraints for different kinds of fields (`Constraints` seems to be constraints for strings, while `Constraints10` are constraints for "geopoints")? (EDIT: I guess if we don't want to keep them, we can just remove a lot of them and it might still be useful to extract the documentation we need)
- how much work will it take to get the docstrings above the class attributes. It's very weird to me that they're below 🤔

2024-09-12 13:38 UTC, lwjohnst86 reviewed
Really like this idea!

2024-09-12 13:38 UTC, lwjohnst86 commented on properties.py
Super nice! Is it possible to only select specific fields to extract and convert? For instance, only the package properties (excluding schema and resource properties)? And for the schema and resource, we run the codegen again on only those properties? Because yea, this is too big.

2024-09-12 13:40 UTC, lwjohnst86 commented on properties.py
@signekb I agree about the point with docstrings below, but it does seem that is the way to write them 🤔 I think I prefer the use of Attributes in the docstrings for these documentation, but we haven't gotten to the doc generation yet, so that isn't relevant yet.

2024-09-13 07:43 UTC, signekb commented on properties.py
@lwjohnst86 When you say "attributes in the docstrings", do you mean something like the last part of this from [Example Google Style Python Docstring](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html): 

![image](https://github.com/user-attachments/assets/2698b75f-4a30-420d-84ce-c992acc8b165)

Bc I like that more too ☺️ I also think that will make the descriptions available when you do e.g., `help(Resource)` or hover over the class in VSCode.

2024-09-13 08:59 UTC, martonvago commented
@lwjohnst86 As for processing only specific fields, I think not directly with this tool, but we could pre-process the schema in a way similar to how we wanted to do it initially. So download the schema, drop the `resources` field on the package, and generate classes based on this modified schema. We can have a Python script for this and still call it from the justfile. (And we still have the option to post-process the dataclasses if we want.)

Just two (somewhat related) questions: 
1. What happens with the `resources` field? I think yesterday we said we wanted to have it on `PackageProperties` just not populate it with resources by default. But then the definition for `PackageProperties` would look like:
```python
@dataclass
class PackageProperties:
    ...
    resources: list[ResourceProperties] = field(default_factory=list)
```
Here, we're still referencing a `ResourceProperties` class in the type hint. Would we just add this in after the script has run?

2. We can run codegen on the resource schema and the table schema separately, but wouldn't we end up with the same very large number of dataclasses, just in different files? Because if we drop the table `schema` field from the resource schema, but then run the script on the table schema as well, then we end up processing the entire resource schema. Same for the package schema and the `resources` field.

2024-09-13 09:06 UTC, martonvago commented on properties.py
I also think that looks nicer! It looks like it's possible to give codegen a custom template to follow when constructing class definitions, so maybe it could even create them like this 🤞

2024-09-16 11:54 UTC, lwjohnst86 commented
@martonvago it sounds like some preprocessing will be needed on the JSON before giving it to the codegen CLI. Would that make sense?

2024-09-18 15:07 UTC, martonvago commented on sprout/core/codegen/dataclass.jinja2
> +    {{ description | wordwrap(80) | indent(4) }}
`wordwrap(80)` and `68` below are just what worked for getting the docstrings below the max line length. It's possible that if we play around with them a bit more we can get these numbers a bit higher.

2024-09-18 15:12 UTC, martonvago commented on sprout/core/codegen/generate_dataclasses.py
> +        "--special-field-name-prefix", "ignore",
This marks the `$schema` properties as to-ignore in the template. I'm ignoring them because they are not necessary for our classes and if we wanted to add them they would more properly be class attributes and not instance attributes.

2024-09-18 15:14 UTC, martonvago commented on sprout/core/codegen/generate_dataclasses.py
> +        "--custom-file-header", "# ruff: noqa",
Adding this because we don't care very much about linting the generated file if we have to make edits to it anyway before using it.

2024-09-18 15:15 UTC, martonvago commented on sprout/core/codegen/generated_properties.py
There's an argument for not committing this at all, but for review purposes it's here now.

2024-09-18 15:17 UTC, martonvago commented on sprout/core/codegen/generate_dataclasses.py
> +        "--force-optional",
This helps a lot with reducing the number of classes at the expense of losing the required - optional split coming from the spec.

2024-09-18 15:23 UTC, martonvago commented on sprout/core/fetch_json_from_url.py
Adding this back in. Sorry for renaming to `fetch` from `scrape`. For me `scrape` means not just downloading some data as it was meant to be downloaded (what we are doing here) but also extracting specific bits from it (e.g. scraping usernames from a forum post).

2024-09-18 15:25 UTC, martonvago commented on sprout/core/write_json.py
Adding this back in.

2024-09-20 10:23 UTC, martonvago commented on sprout/core/properties.py
> +        - id (str | None): The unique identifier of this resource.
I added this

2024-09-20 10:25 UTC, martonvago commented on sprout/core/properties.py
> +    path: str | None = None
I disabled multipath resources by not allowing a list here

2024-09-20 10:28 UTC, martonvago commented on sprout/core/properties.py
> -    homepage: str | None = None
I deleted this because it is not listed on the website, only in the JSON schema, and there it is described as a Data Package property (which it is).

2024-09-20 10:30 UTC, martonvago commented on sprout/core/properties.py
> +    unique_keys: list[list[str]] | None = None
Simplified this type because `list[None]` is meaningless as `unique_keys` and was probably added because we're forcing optional types.

2024-09-23 08:30 UTC, lwjohnst86 requested changes
Super nice!!! Just some suggestions :tada:

2024-09-23 08:30 UTC, lwjohnst86 commented on justfile
> +  poetry run python sprout/core/codegen/generate_dataclasses.py
Hmm, good question. We can leave it here for now.

2024-09-23 08:30 UTC, lwjohnst86 commented on sprout/core/codegen/custom_formatters.py
I think naming the folder `autogenerate_properties/` or `generate_properties/` or somthing compared to `codegen` would be clearer on its intent.

2024-09-23 08:30 UTC, lwjohnst86 commented on sprout/core/codegen/generate_dataclasses.py
> +from sprout.core.fetch_json_from_url import fetch_json_from_url
Since we already have the verb `get_` that implies the same thing as `fetch_`, let's use `get_` instead.

2024-09-23 08:30 UTC, lwjohnst86 commented on sprout/core/codegen/generate_dataclasses.py
> +        "--custom-file-header", "# ruff: noqa",
```suggestion
        "--custom-file-header", "# ruff: noqa\n# NOTE: This content was autogenerated, no need to edit it.",
```

Just to have a disclaimer somewhere about where the file came from.

2024-09-23 08:30 UTC, lwjohnst86 commented on sprout/core/codegen/generated_properties.py
> +class TableDialectProperties:
I'm not sure how much of this we'll need, but this is a great starting point!!

2024-09-23 08:30 UTC, lwjohnst86 commented on sprout/core/fetch_json_from_url.py
> +def fetch_json_from_url(url: str) -> dict:
As mentioned above, let's use `get_` instead.

2024-09-23 08:30 UTC, lwjohnst86 commented on sprout/core/properties.py
> +from dataclasses import dataclass, field
```suggestion
# NOTE: This content is modified from the auto-generated `codegen/generated_properties.py`
# file. Update the auto-generated properties file to add more dataclasses and move
# into this file.
from dataclasses import dataclass, field
```

codegen will need to be changed to something else, as per the comment above.

2024-09-23 08:30 UTC, lwjohnst86 commented on sprout/core/properties.py
> +    """A contributor to this descriptor.
We'll eventually want to update this documentation a bit more as we use it and see what we might be missing, but this is a great starting point!!!

2024-09-23 08:30 UTC, lwjohnst86 commented on tests/core/test_write_json.py
> +}"""
Woah, is this linted?? ugly with the indentation!! Any way to get it flush with everything else?

2024-09-23 09:34 UTC, martonvago commented on tests/core/test_write_json.py
> +}"""
This is because it's testing the indentation as well, so we can't indent inside of `"""..."""`. I think the other option was 
```python
expected_contents = (
    '{\n'
    '  "outer": "value",\n'
    '  "inner": {\n'
    '    "prop1": 123,\n'
    '    "prop2": [\n'
    '      1,\n'
    '      2,\n'
    '      null\n'
    '    ],\n'
    '    "prop3": true\n'
    '  }\n'
    '}'
)
```

Would this be better?

2024-09-23 09:35 UTC, martonvago commented on sprout/core/properties.py
> +    """A contributor to this descriptor.
https://github.com/seedcase-project/seedcase-sprout/pull/718 improves this a tiny bit

2024-09-23 10:03 UTC, lwjohnst86 commented on tests/core/test_write_json.py
> +}"""
Yeaaayyyy :star_struck:

2024-09-23 10:03 UTC, lwjohnst86 commented
@martonvago I also forgot to say to include the dataclasses in the `__init__.py` file :relaxed:

2024-09-23 11:37 UTC, lwjohnst86 approved these changes
Amazing!!

2024-09-23 11:41 UTC, merged