docs: :pencil2: correct function names after changes
seedcase-project/seedcase-sprout pull request #697
Opened 2024-09-12 15:51 UTC by lwjohnst86

## Description

Closes #652, since I've removed it in favour of having a `list_files()` function instead. Also closes #655, since maybe we don't use the database. Or at least, it's feeling like it won't be necessary at this point.

## Reviewer Focus

This PR needs an in-depth review.

2024-09-12 15:53 UTC, lwjohnst86 commented on docs/design/implementation/python-functions.qmd
> +### `path_*()` diagram
I considered whether this could be a class, but ended up deciding it doesn't make sense and would actually lead to more characters needing to type (e.g. `Path().package(1).resource(1)` vs `path_resources(1, 1)`).

2024-09-16 08:21 UTC, signekb reviewed
Nice! Just a comment on considering adding "files" to `path_resources_raw()` for clarity.

2024-09-16 08:21 UTC, signekb commented on docs/design/implementation/python-functions.qmd
> +and `path_resources_raw()` with `list_files()` for the `raw_files`
I actually think it's clearer to call this `path_resources_raw_files()`, so maybe we should change it to that? ☺️

2024-09-16 08:21 UTC, signekb commented on docs/design/implementation/python-functions.qmd
> +print(path_resources(1, 2))
```suggestion
print(path_resource(1, 2))
```

2024-09-16 08:21 UTC, signekb commented on docs/design/implementation/python-functions.qmd
> +print(path_resources(1, 2))
The name of these two functions are super close, which isn't ideal, but I guess that's just how it has to be ☺️ 
At least, I can't seem to find a better alternative

2024-09-16 08:21 UTC, signekb commented on docs/design/implementation/python-functions.qmd
> +<!-- TODO: Not sure if we will keep this database thing -->
```suggestion
<!-- TODO: Not sure if we will keep the database -->
```

2024-09-16 08:58 UTC, lwjohnst86 commented on docs/design/implementation/python-functions.qmd
> +print(path_resources(1, 2))
@signekb yea I agree. Should be easy to notice when typing that one doesn't take the resource ID arg. But yea, not super ideal.

2024-09-16 10:25 UTC, martonvago requested changes
Looks great, thanks 😁

2024-09-16 10:25 UTC, martonvago commented on docs/design/implementation/python-functions.qmd
> +#### Example usage
I think this might not be in the callout section now

2024-09-16 10:25 UTC, martonvago commented on docs/design/implementation/python-functions.qmd
> +print(path_resources_data(4, 2))
```suggestion
print(path_resource_data(4, 2))
```
Sorry if I'm misunderstanding these

2024-09-16 10:28 UTC, lwjohnst86 commented on docs/design/implementation/python-functions.qmd
> +print(path_resources_data(4, 2))
Just fixed those before seeing your comment :relaxed:

2024-09-16 10:28 UTC, merged