feat: ✨ add `path_sprout_root()`
seedcase-project/seedcase-sprout pull request #705
Opened 2024-09-16 14:12 UTC by signekb

## Description

These changes are for PURPOSE, because REASON.

Closes #683 

## Reviewer Focus

This PR needs an in-depth review.

Focus on CHANGES.

## Checklist

- [X] Added or updated tests
- [X] Tests passed locally
- [X] Linted and formatted code
- [X] Build passed locally
- [X] Updated documentation (= added docstrings)

2024-09-16 14:13 UTC, signekb commented on tests/core/test_path_sprout_root.py
These tests are basically the same as for `get_root_envvar()`

2024-09-16 15:07 UTC, lwjohnst86 approved these changes
Easy peasy :stuck_out_tongue: nice!

2024-09-16 15:08 UTC, lwjohnst86 requested changes

2024-09-16 15:08 UTC, lwjohnst86 commented on sprout/core/path_sprout_root.py
Oh, forgot to say, uncomment the line in the `__init__.py` file.

2024-09-17 11:23 UTC, lwjohnst86 approved these changes
:tada:

2024-09-17 11:23 UTC, merged