Improve docstrings in properties classes
seedcase-project/seedcase-sprout pull request #718
Opened 2024-09-20 10:48 UTC by martonvago

## Description

This improves the docstrings in the properties classes. Some missing descriptions are added and some errors are corrected. I've also read over the [website](https://datapackage.org/standard/data-package/) that contains more descriptive documentation than the JSON schema and moved our docs to that version if I thought it was nicer (pretty arbitrarily).

## Reviewer Focus

This PR needs a medium-depth review.

## Checklist

- [x] Added or updated tests
- [x] Tests passed locally
- [x] Linted and formatted code
- [x] Build passed locally
- [x] Updated documentation

2024-09-23 10:19 UTC, lwjohnst86 approved these changes, later dismissed
Very nice!! No comments, looks great! There are some fields that I am not sure the use for (yet) but as we go along we will modify :relaxed:

2024-09-24 13:01 UTC, signekb reviewed
I have probably overlooked a few details in this PR, but overall it looks great to me! I just have a few comments on how Google docstrings should be formatted :)

2024-09-24 14:17 UTC, lwjohnst86 commented
@martonvago, woah, what happened to the PR? It now has the `codegen` files in it. It was only the docs before... :thinking:

2024-09-24 14:20 UTC, lwjohnst86 requested changes

2024-09-24 14:20 UTC, lwjohnst86 commented on sprout/core/codegen/dataclass.jinja2
> +        - {{ (field.name ~ " (" ~ field.type_hint ~ "): " ~ (field.docstring or "")) | wordwrap(68) | indent(8) }}
@martonvago could you make a new PR with the changes @signekb is suggesting here? This file got mangled up into this PR and I don't know how...

2024-09-24 14:22 UTC, lwjohnst86 commented on sprout/core/properties.py
> +    r"""Table Dialect describes how tabular data is stored in a file.
This was fixed previously, I don't know what happened.

2024-09-24 14:24 UTC, lwjohnst86 commented on sprout/core/properties.py
> +    A simple format to describe and package a single data resource such as an
Not capitalized. I'll fix the title to match it.

2024-09-24 14:56 UTC, lwjohnst86 commented
@martonvago and @signekb I fixed this PR, something went wonky. While I fixed it, I addressed some of @signekb comments. But look it over again just in case :relaxed:

2024-09-24 14:57 UTC, lwjohnst86 commented on sprout/core/properties.py
> +    r"""Table dialect describes how tabular data is stored in a file.
@signekb see the comment above that explains this `r` here.

2024-09-24 14:57 UTC, lwjohnst86 approved these changes, later dismissed

2024-09-25 06:59 UTC, signekb approved these changes, later dismissed
Looks great 👍

2024-09-25 09:28 UTC, martonvago commented on sprout/core/codegen/dataclass.jinja2
> +        - {{ (field.name ~ " (" ~ field.type_hint ~ "): " ~ (field.docstring or "")) | wordwrap(68) | indent(8) }}
I'll have a look at this, not sure how easy it will be to do the extra indentation on every line but the first one 🤞

2024-09-25 09:29 UTC, martonvago commented on sprout/core/properties.py
> +        inherits, if the contributor is a person.
Yeah, might be a bit tricky with the template (because it's auto-wrapping the lines), but I'll try

2024-09-25 09:32 UTC, martonvago commented
Looks good to me! I'll have a look at changing the template separately

2024-09-25 10:18 UTC, lwjohnst86 approved these changes

2024-09-30 09:56 UTC, merged