feat: ✨ add `path_*()` functions with utils
seedcase-project/seedcase-sprout pull request #730
Opened 2024-09-24 12:36 UTC by signekb

## Description
  
I decided to have a script for path functions related to packages and one related to resources. I found that it became too long - for my taste at least - with the docstrings otherwise.   
  
To add existing ID's to the raised errors, I have added two helper functions and put them in a `path_helper_functions` file.   
  
To test these functions, I have created some helper functions to create the folder structure of packages and resources.

Closes #714  

## Reviewer Focus
  

This PR needs an in-depth review.  
  
Focus on:

- CHANGES
- naming of files

## Checklist

- [X] Added or updated tests
- [X] Tests passed locally
- [X] Linted and formatted code
- [X] Build passed locally
- [X] Updated documentation (= docstrings)

2024-09-25 07:38 UTC, signekb commented on tests/core/directory_structure_setup.py
> +    # TODO: Use `create_package_structure()` function here when it's implemented.
```suggestion
    # TODO: Use `create_package_structure()` function here when has been implemented.
```

2024-09-26 09:28 UTC, martonvago requested changes
Really nice!! Just some comments 😊

2024-09-26 09:28 UTC, martonvago commented on tests/core/test_path_package_functions.py
> +    monkeypatch.setenv("SPROUT_ROOT", SPROUT_ROOT)
```suggestion
    monkeypatch.setenv("SPROUT_ROOT", str(tmp_path))
```
If you convert the path to string in here then you can return it as a `Path` and then you don't have to reconvert it to `Path` in the tests. Same in other test file.

2024-09-26 16:38 UTC, signekb commented on sprout/core/path_error_context.py
> +        ids_path: Path to find existing ID's.
I think you can do either? At least e.g., Merriam-Webster uses both ID's and IDs as plurals of ID 🤷  I'll change it.

2024-09-26 16:40 UTC, signekb commented on sprout/core/path_package_functions.py
That makes a lot of sense, actually! 😅

2024-09-26 17:55 UTC, signekb commented on tests/core/test_path_package_functions.py
> +    monkeypatch.setenv("SPROUT_ROOT", SPROUT_ROOT)
Omg, ofc! Thanks 😁

2024-09-26 17:58 UTC, signekb commented on sprout/core/path_package_functions.py
I have implemented this now, in a way that made sense to me. I didn't have the time to add separate tests for when the package doesn't exist and the package exist but the file is missing :)

2024-09-30 10:36 UTC, lwjohnst86 submitted a review, later dismissed
@martonvago and @signekb I refactored the verify function into two, because the original one was confusing to me and had too many arguments for the purpose I interpreted it had. Makes the code a bit cleaner.

2024-09-30 10:36 UTC, lwjohnst86 commented on sprout/core/path_package_functions.py
> +from sprout.core.verify_is_file import verify_is_file
Paths for files need to `verify_is_file()`.

2024-09-30 10:36 UTC, lwjohnst86 commented on sprout/core/verify_is_package_dir.py
I split the original verify function into two rather than one, and simplified them a lot. The original confused me.

2024-10-01 14:19 UTC, martonvago requested changes
Looks great! Just a tiny comment.

Only other thing I can think of is that `FileNotFoundError`s are not being tested, but we can add those tests later too.

2024-10-02 20:01 UTC, lwjohnst86 submitted a review, later dismissed
@martonvago since the `verify_is_file()` already has a unit test for it, I'm not too worried that we don't test that the files exist or not for these tests.

2024-10-02 20:02 UTC, merged