feat: :sparkles: add create_default_package_properties
seedcase-project/seedcase-sprout pull request #731
Opened 2024-09-24 13:49 UTC by martonvago

## Description

This adds a function for creating package properties as a dictionary with some default values. I renamed this function from `create_properties_object` to `create_default_package_properties` because it seemed more descriptive.

Closes #615 

## Reviewer Focus

This PR needs an in-depth review.

Focus on CHANGES.

## Checklist

- [x] Added or updated tests
- [x] Tests passed locally
- [x] Linted and formatted code
- [x] Build passed locally
- [x] Updated documentation

2024-09-24 13:52 UTC, martonvago commented on docs/design/implementation/images/core/create-package-structure.svg
Oh I should have tried autogenerating this 🤦

2024-09-24 13:53 UTC, martonvago commented on pyproject.toml
> +time-machine = "^2.15.0"
Using this for managing dates/times in tests because `freezegun` was not behaving very nicely with non-UTC timezones

2024-09-24 13:56 UTC, martonvago commented on sprout/core/create_default_package_properties.py
> +        id: The id of the package.
The issue says this should have a `Path` as argument, but it only needs the `id`, right? At least I wasn't sure what to do with the path.

2024-09-24 13:57 UTC, martonvago commented on sprout/core/create_default_package_properties.py
> +    )
Happy to have more / other defaults

2024-09-24 14:00 UTC, martonvago commented on sprout/core/create_default_package_properties.py
> +    return asdict(package_properties)
Returning a `dict` here that can be passed directly to `write_json` later. Alternatively, we can return a `PackageProperties`, but then I'm not sure if we need this function at all.

2024-09-24 14:03 UTC, martonvago commented on sprout/core/properties.py
> +        - id (int | None): The unique identifier of this resource.
Changing this because we are passing `int`s as ids right now. Not super sure which way is better, but we can always change it later.

2024-09-24 14:11 UTC, lwjohnst86 requested changes
Could you split this PR into 3? One for the changes to the docs, another for the typos and the last for the feature?

2024-09-24 14:16 UTC, martonvago commented
@lwjohnst86 Sure, but what typos?

2024-09-24 15:12 UTC, lwjohnst86 requested changes
Lovely :grin: just some comments and changes requested :relaxed:

2024-09-24 15:12 UTC, lwjohnst86 commented on sprout/core/create_default_package_properties.py
> +        id=id,
Instead of using the package ID, generate a GUID/UUID, as described in https://datapackage.org/standard/data-package/#id

2024-09-24 15:12 UTC, lwjohnst86 commented on sprout/core/create_default_package_properties.py
> +def create_default_package_properties(id: int) -> dict:
```suggestion
def create_default_package_properties() -> dict:
```

See comment below.

2024-09-24 15:12 UTC, lwjohnst86 commented on sprout/core/create_default_package_properties.py
> +    )
Yup! :grin:

2024-09-24 15:12 UTC, lwjohnst86 commented on sprout/core/create_default_package_properties.py
> +        id: The id of the package.
```suggestion
```

2024-09-24 15:12 UTC, lwjohnst86 commented on sprout/core/create_default_package_properties.py
> +        id: The id of the package.
I think the issue is outdated, the current diagram doesn't include any input.

2024-09-24 15:12 UTC, lwjohnst86 commented on sprout/core/create_default_package_properties.py
> +        description=f"This is a description of Package {id}.",
```suggestion
```

We won't add this just yet, that will be later.

2024-09-24 15:12 UTC, lwjohnst86 commented on sprout/core/create_default_package_properties.py
> +    return asdict(package_properties)
This is a discussion we'll eventually have to have, but I think the JSON/dict output is the most flexible and requires the least from us in terms of extra work (I think so anyway, but we'll see)

2024-09-24 15:12 UTC, lwjohnst86 commented on sprout/core/utils.py
I'm not sure I like this file, particularly the name `utils`, see:

- https://www.reddit.com/r/Python/comments/g1dxfn/stop_naming_your_python_modules_utils/
- https://breadcrumbscollector.tech/where-to-put-all-your-utils-in-python-projects/
- https://dave.cheney.net/2019/01/08/avoid-package-names-like-base-util-or-common
- https://breadcrumbscollector.tech/stop-naming-your-python-modules-utils/

For now, the content inside will just stay inside until we refactor that. But in the meantime, could you move the timestamp function into it's own file?

2024-09-25 07:30 UTC, martonvago commented on sprout/core/create_default_package_properties.py
> +        id: The id of the package.
Ohhh, that explains the diagram!! Thanks!

2024-09-30 10:40 UTC, lwjohnst86 approved these changes
Super neat, nice!!

2024-09-30 10:40 UTC, merged