Add `verify_package_properties`
seedcase-project/seedcase-sprout pull request #744
Opened 2024-10-01 12:25 UTC by martonvago

## Description

This adds `verify_package_properties` and a helper function to check that package properties are valid according to the frictionless spec and that all required fields are present and not empty.

I've also generalised `InvalidResourcePropertiesError` to `InvalidPropertiesError` because each individual error says whether it's a package or a resource error anyway.

Closes #712 

## Reviewer Focus

This PR needs an in-depth review.

Focus on whether this is the error-behaviour we want.

## Checklist

- [x] Added or updated tests
- [x] Tests passed locally
- [x] Linted and formatted code
- [x] Build passed locally
- [x] Updated documentation

2024-10-01 12:26 UTC, martonvago commented on sprout/core/invalid_properties_error.py
This was just moved out of `verify_resource_properties.py` into a separate file and renamed a bit.

2024-10-01 12:29 UTC, martonvago commented on sprout/core/verify_package_properties.py
> +    report = verify_required_package_properties(report, properties)
I was very tempted to do it this way (i.e. add our stuff to the frictionless report), but let me know if we should just throw a separate error instead.

2024-10-01 12:30 UTC, martonvago commented on sprout/core/verify_required_package_properties.py
> +}
I just picked some, so feel free to change

2024-10-01 12:43 UTC, martonvago commented on sprout/core/verify_required_package_properties.py
> +        if properties.get(field) in ["", None]:
- I think this is okay for what we have now, but it would need to be updated if we had required fields that weren't type string.
- I've included `None` because I wanted missing fields to be flagged explicitly as missing when given e.g. an empty object.
- There are cases when this means that we generate 2 different types of errors for one field. E.g. if `name=""`, this fails the required-property check as well as the name-format check.

2024-10-02 07:42 UTC, K-Beicher commented on sprout/core/verify_required_package_properties.py
> +}
Is created date or person?

2024-10-02 09:14 UTC, martonvago commented on sprout/core/verify_required_package_properties.py
> +}
A date

2024-10-03 12:58 UTC, martonvago commented
I think I'll end up changing this to make it play nicer with the contents of `datapackage.json`.

2024-10-03 14:33 UTC, martonvago commented on sprout/core/verify_package_properties.py
> +        if properties.get(field) in ["", None]
- I think this is okay for what we have now, but it would need to be updated if we had required fields that weren't type string.
- I've included `None` because I wanted missing fields to be flagged explicitly as missing when given e.g. an empty object.

2024-10-03 14:34 UTC, martonvago commented on sprout/core/invalid_properties_error.py
This was just moved out of `verify_resource_properties.py` into a separate file and renamed a bit.

2024-10-03 14:37 UTC, martonvago commented on sprout/core/verify_package_properties.py
> +    }
Not sure how we feel about this

2024-10-03 14:41 UTC, martonvago commented on sprout/core/verify_package_properties.py
> +REQUIRED_PACKAGE_PROPERTIES = {
We could consider adding`resources` here, because frictionless flags this as required anyway, and it would be more consistent if "we" (i.e. `verify_package_properties_complete`) flagged it too. (An empty list, so our default value, satisfies this btw)

2024-10-04 14:00 UTC, lwjohnst86 reviewed
I'm going to come back to this later, but already started writing some comments

2024-10-11 11:17 UTC, martonvago commented
I refactored this a bit to make the verification functions more general, so that we can use them for resources as well.

2024-10-11 11:29 UTC, martonvago commented on sprout/core/verify_properties_complete.py
> +        # N.B. that an empty list is an acceptable value for a required field.
I think this makes sense?

2024-10-11 11:30 UTC, martonvago commented on sprout/core/verify_properties_well_formed.py
> +    }
Not sure how we feel about this

2024-10-14 10:54 UTC, martonvago commented on sprout/core/verify_properties_well_formed.py
> +        raise NotPropertiesError(errors, properties)
This does 2 things:

1. It includes some errors which are only written to a `task` and not to the main `report`.
2. It filters for errors that we care about (so, e.g., `PackageError` or `ResourceError`). This is useful because if we include empty values in our properties objects (whether `None` or a different empty default value), these values will fail frictionless validation at some point. We don't actually care about these failures because we don't expect those fields to be filled in at this point. But I'm very very open to better ideas for this.

2024-10-14 10:56 UTC, signekb commented
@martonvago should this PR be a draft, if you're still working on it? :)

2024-10-14 11:02 UTC, martonvago commented
I didn't really plan on adding more stuff to it, but as I was working on #757, it became clear that some things needed to be changed -- and this seemed like a sensible place for it. That said, I'm hoping it's all done now!

2024-10-14 11:11 UTC, signekb commented
Makes sense! All good! 
I have merged #767 now and the tests don't fail anymore. Yay!

2024-10-14 13:56 UTC, signekb requested changes
Nice work! ⭐  I have some suggestions which are mostly minor things :)

2024-10-14 13:56 UTC, signekb commented on sprout/core/verify_properties_complete.py
> +        if properties.get(field) in ["", None]
Just checking: Can a field still be `None` with #769 ?

2024-10-14 13:56 UTC, signekb commented on sprout/core/verify_properties_well_formed.py
> +        The properties, if well formed.
```suggestion
        The properties, if well-formed.
```
? :)

2024-10-14 13:56 UTC, signekb commented on sprout/core/verify_properties_well_formed.py
> +        NotPropertiesError: If the properties are not well formed.
```suggestion
        NotPropertiesError: If the properties are not well-formed.
```
? :)

2024-10-14 13:56 UTC, signekb commented on sprout/core/verify_properties_well_formed.py
> +def verify_properties_well_formed(properties: dict, error_type: str) -> dict:
```suggestion
def verify_properties_are_well_formed(properties: dict, error_type: str) -> dict:
```
? :)

2024-10-14 13:56 UTC, signekb commented on sprout/core/verify_properties_well_formed.py
> +    non_empty_properties = {
I think that I need to be reminded why only the non-empty properties are validated below?

2024-10-14 13:56 UTC, signekb commented on tests/core/test_verify_package_properties.py
> +    properties["name"] = "an invalid name"
```suggestion
    properties["name"] = "an invalid name with spaces"
```
To make it explicit why it's invalid? :)

2024-10-14 13:56 UTC, signekb commented on tests/core/test_verify_properties_complete.py
> +def test_checks_for_required_fields(required_fields):
```suggestion
def test_accepts_required_fields(required_fields):
```

2024-10-14 13:56 UTC, signekb commented on tests/core/test_verify_properties_well_formed.py
> +error_type = errors.PackageError.type
Would it be a bit clearer if this variable was called `package_error` and then used in the tests like this: `error_type=package_error`?
Or is it bc you'll add tests for resource properties in another PR as well and will parametrise these tests?

2024-10-14 13:56 UTC, signekb commented on tests/core/test_verify_properties_well_formed.py
> +def test_rejects_properties_not_conform_to_spec(package_properties):
```suggestion
def test_rejects_properties_not_conforming_to_spec(package_properties):
```

2024-10-14 13:56 UTC, signekb commented on tests/core/test_verify_properties_well_formed.py
> +    package_properties["name"] = "an invalid name"
```suggestion
    package_properties["name"] = "an invalid name with spaces"
```

2024-10-14 13:56 UTC, signekb commented on tests/core/test_verify_properties_well_formed.py
> +    """Should throw only if errors of the specified type are detected."""
```suggestion
    """Should throw only if PackageErrors are detected."""
```
To be specific about what the error type is. Unless you'll include resource errors here later?

2024-10-14 13:56 UTC, signekb commented on tests/core/test_verify_properties_well_formed.py
> +    bad_resource = ResourceProperties(name="a bad name").asdict
```suggestion
    bad_resource = ResourceProperties(name="a bad name with spaces").asdict
```

2024-10-15 07:27 UTC, martonvago commented on sprout/core/not_properties_error.py
> +        # are not guaranteed to include all errors.
There's some discussion of this [here](https://github.com/seedcase-project/seedcase-sprout/pull/613#discussion_r1734074414), but let me know if it doesn't make sense

2024-10-15 07:34 UTC, martonvago commented on sprout/core/verify_properties_complete.py
> +        if properties.get(field) in ["", None]
Only if you construct a dict by hand (not through one of our properties objects) or if you pass it the empty object.

2024-10-15 07:52 UTC, martonvago commented on sprout/core/verify_properties_well_formed.py
> +        The properties, if well formed.
I didn't hyphenate this because it's predicative, not attributive ("the actor is well known" vs "a well-known actor"), but it could be argued that "well-formed" is actually so common that it should always be used with a hyphen... I don't mind either way 😊

2024-10-15 08:15 UTC, signekb commented on sprout/core/not_properties_error.py
> +        # are not guaranteed to include all errors.
Ah, thanks!

2024-10-15 08:23 UTC, martonvago commented on tests/core/test_verify_properties_well_formed.py
> +error_type = errors.PackageError.type
Yeah, I was thinking the latter, but I can also rename it. (Turns out it can't be parametrised as nicely as I thought)

2024-10-15 08:36 UTC, signekb commented on sprout/core/verify_properties_well_formed.py
> +    non_empty_properties = {
Ah, thanks! 👍

2024-10-15 13:02 UTC, lwjohnst86 submitted a review, later dismissed
:tada: Great!

2024-10-15 13:03 UTC, merged