feat: ✨ add `create_package_structure`
seedcase-project/seedcase-sprout pull request #754
Opened 2024-10-07 09:33 UTC by martonvago

## Description

This adds the `create_package_structure` function.

Closes #619 

## Reviewer Focus

This PR needs an in-depth review.

## Checklist

- [x] Added or updated tests
- [x] Tests passed locally
- [x] Linted and formatted code
- [x] Build passed locally
- [x] Updated documentation

2024-10-08 09:53 UTC, lwjohnst86 approved these changes, later dismissed
Awe, fills me with warm fuzzies seeing this come together!!! :star_struck:

2024-10-08 10:10 UTC, K-Beicher reviewed
I really like how short they get now that we have all the underlying functions sorted out.

2024-10-09 10:17 UTC, signekb requested changes
Oh, it's super nice to see it all come together like this 🤩 
I have some very minor suggestions - otherwise this looks great to me!

2024-10-09 10:17 UTC, signekb commented on sprout/core/create_package_structure.py
> +    readme = create_readme_text(properties)
This is nitpicking, but I think the order of these would be nicer if they were: 
```suggestion
    properties = create_default_package_properties()
    properties_path = create_properties_path(package_path)
    readme = create_readme_text(properties)
    readme_path = create_readme_path(package_path)
```
So they are "grouped" in the sense that first `properties` are handled, then the README. It also matches the order that they are used in the return statement :)

2024-10-09 10:17 UTC, signekb commented on tests/core/test_create_package_structure.py
> +def test_throws_if_directory_does_not_exist(tmp_path):
```suggestion
def test_throws_error_if_directory_does_not_exist(tmp_path):
```
? :)

2024-10-09 10:17 UTC, signekb commented on tests/core/test_create_package_structure.py
> +def test_throws_if_path_points_to_file(tmp_path):
```suggestion
def test_throws_error_if_path_points_to_file(tmp_path):
```

2024-10-09 10:17 UTC, signekb commented on sprout/core/create_package_structure.py
> +        A list of paths to the created files.
```suggestion
        A list of paths to the two created files: The datapackage.json and the README.md.
```
I think it would be nice to be more specific here :)

2024-10-09 14:34 UTC, martonvago commented on sprout/core/create_package_structure.py
> +    readme = create_readme_text(properties)
Sure, absolutely no preference :)

2024-10-14 10:18 UTC, signekb approved these changes

2024-10-14 14:44 UTC, merged