docs: :memo: installation guide on Sprout with pip
seedcase-project/seedcase-sprout pull request #765
Opened 2024-10-09 12:31 UTC by K-Beicher

## Description

These changes are for instructing the user on how to install Sprout.

Closes #728, closes #729

## Reviewer Focus

This PR needs a standard review.

Focus on whether or not anything is missing, or if there are items included that doesn't need to be there..

## Checklist

- [x] Spell-check
- [x] Formatted Markdown (I think)
- [x] Renders locally

2024-10-14 13:16 UTC, signekb requested changes
Very nice! 
I have some ideas on how this could be structured a bit differently, which I mostly suggested in a big chunk. Hope that's ok ☺️

2024-10-14 13:16 UTC, signekb commented on docs/guide/installation.qmd
> +command line.
This might be a bit controversial, but I'm not sure that we need this? :)
```suggestion
```

2024-10-14 13:16 UTC, signekb commented on docs/guide/installation.qmd
> +## Installing Sprout using pip
```suggestion
## Install Sprout using pip
```

2024-10-14 13:16 UTC, signekb commented on docs/guide/installation.qmd
> +{{< include /docs/includes/_wip.qmd >}}
```suggestion
```
This file has been deleted and the message is included directly in `_quarto.yml` instead 👍

2024-10-14 13:16 UTC, signekb commented on docs/guide/installation.qmd
> +
We could add a collapsed callout block here for people who aren't comfortable with the terminal :)

```suggestion

::: {.callout-tip title="Not too comfortable using the terminal? Look here!" collapse="true"}
If you're not comfortable using the terminal, fear not! Below you'll find a thorough
step-by-step guide to help you along.

<!-- TODO: Add instructions for people not comfortable with the terminal -->
:::
```

2024-10-14 13:16 UTC, signekb commented on docs/guide/installation.qmd
> +higher, pip, and pipenv.
I don't think we need `pipenv`? :)

2024-10-14 13:16 UTC, signekb commented on docs/guide/installation.qmd
> +:::
Taking inspiration from Tensorflow and poetry's installation guides, I have made an alternative version of how this could look: 

This if ofc just a suggestion ☺️ 

````suggestion
### 1. **Python** and **pip**

Sprout requires Python and pip to be installed on your system:

::: {.callout-note title="Software requirements"}
-   [Python](https://www.python.org/downloads/) 3.6–3.12
-   [pip](https://pip.pypa.io/en/stable/installation/) version 19.0 or
    higher
    <!--TODO: Do we have a specific pip version we require? This version
    was taken from TensorFlow's installation guide. They do vary their
    version requirements based on OS, not sure if we should too?-->
:::

Check your Python and pip version by running the following commands in
your terminal:

``` bash
python3 --version
python3 -m pip --version
```

If you don't get a Python version between 3.6 and 3.12 (or at all), go
to the [Python website](https://www.python.org/downloads/) to download
and install Python.

If you don't have pip installed, you can install it by following the
instructions on the [pip
website](https://pip.pypa.io/en/stable/installation/).

### 2. **Install Sprout**

To install Sprout, make sure that pip is up to date by running the
following command in your terminal:

``` bash
pip install --upgrade pip
```

Then, install Sprout directly from the [GitHub
repository](https://github.com/seedcase-project/seedcase-sprout) by
running the following command:

``` bash
pip install seedcase_sprout@git+https://github.com/seedcase-project/seedcase-sprout
```

### 3. **Check the installation**

To check that Sprout has been installed correctly, run the following
command in your terminal:

``` bash
python3 -c "import sprout.core as sp; print(sp.PackageProperties())"
```

If a `PackageProperties` object is returned, Sprout has been installed
successfully. 

Get started with your first data package by following the guide on 
[Creating and managing data packages](https://sprout.seedcase-project.org/docs/guide/packages).
```

2024-10-15 06:59 UTC, K-Beicher commented on docs/guide/installation.qmd
> +command line.
Depends on what you think your audience is, if it is me a year back, then I would have appreciated the info.

2024-10-15 07:01 UTC, K-Beicher commented on docs/guide/installation.qmd
> +higher, pip, and pipenv.
@lwjohnst86 I think you were the one to mention pipenv, but now that I think about it, I believe Signe is right..

2024-10-15 08:23 UTC, signekb commented on docs/guide/installation.qmd
> +command line.
I see what you mean. The reasons why I removed this was that I thought it was a bit repetitive (the requirements are listed below) and I didn't want to scare people away who do not feel comfortable using the terminal :) 

I added the "are you not comfortable with the command line?" block as a place to put a more thorough step-by-step guide for how to install Sprout using the terminal, but this might be overkill? I thought about the things you said the other day about when you're new to the terminal, you might not think about which directory you're in before installing, for example :)

If we get to a stage with a non-terminal installation, I think it should have its own section 🌱

2024-10-15 08:27 UTC, K-Beicher commented on docs/guide/installation.qmd
> +command line.
Ah - that was how you wanted to use the block, no, that makes perfect sense. The only caveat would be that the guide for terminal novices would be rather long, do we want it on a separate page?

2024-10-15 14:28 UTC, signekb requested changes

2024-10-15 15:21 UTC, lwjohnst86 requested changes
Nice!! I have some other changes that I will do directly in the text. But here's a start :grin:

2024-10-15 15:21 UTC, lwjohnst86 commented on docs/guide/installation.qmd
> +python3 -c "import sprout.core as sp; print(sp.PackageProperties())"
```suggestion
pip show seedcase_sprout
```

This shows information about the package, if it is installed.

2024-10-15 15:21 UTC, lwjohnst86 commented on docs/guide/installation.qmd
> +[Creating and managing data packages](https://sprout.seedcase-project.org/docs/guide/packages).
```suggestion
[Creating and managing data packages](/docs/guide/packages.qmd).
```

2024-10-15 15:21 UTC, lwjohnst86 commented on docs/guide/installation.qmd
> +### 2. **Install Sprout**
```suggestion
### Install Sprout
```

2024-10-15 17:49 UTC, lwjohnst86 approved these changes, later dismissed
I revised the text a bit, but mostly rearranged the content. Otherwise, nice!

2024-10-15 17:49 UTC, lwjohnst86 commented on docs/guide/installation.qmd
> +\>=3.6 be installed on your system, which includes pip. Run this command
There isn't a need to separately install pip, it comes with Python.

2024-10-15 17:49 UTC, lwjohnst86 commented on docs/guide/installation.qmd
> +### Creating a virtual environment
We needed the section on creating a virtual environment, since it isn't recommended to install via pip into the global environment.

2024-10-15 17:49 UTC, lwjohnst86 commented on docs/guide/installation.qmd
> +pip show seedcase_sprout
This is a better way to test if it installed, plus it shows the version and other details.

2024-10-15 17:49 UTC, lwjohnst86 commented on docs/guide/installation.qmd
> +## Use anywhere on the computer or in the Terminal
This section will include instructions using pipx.

2024-10-16 08:30 UTC, K-Beicher reviewed
Just the one typo

2024-10-16 08:30 UTC, K-Beicher commented on docs/guide/installation.qmd
> +negatively effect other Python packages. Rather, you install a package
affect

2024-10-16 08:47 UTC, martonvago requested changes
Super nice 🎉 !! Just saw a typo 😊

2024-10-16 08:47 UTC, martonvago commented on docs/guide/installation.qmd
> +to use the Terminal. If you unfamiliar with the terminal, start with our
```suggestion
to use the Terminal. If you are unfamiliar with the terminal, start with our
```

2024-10-16 15:05 UTC, lwjohnst86 commented on docs/guide/installation.qmd
> +negatively effect other Python packages. Rather, you install a package
```suggestion
negatively affect other Python packages. Rather, you install a package
```

2024-10-16 15:05 UTC, lwjohnst86 approved these changes

2024-10-16 15:05 UTC, merged