feat: :sparkles: add `write_resource_properties`
seedcase-project/seedcase-sprout pull request #784
Opened 2024-10-15 14:18 UTC by martonvago

## Description

This adds `write_resource_properties`.

Closes #757 

This PR needs an in-depth review.

## Checklist

- [x] Added or updated tests
- [x] Tests passed locally
- [x] Linted and formatted code
- [x] Build passed locally
- [x] Updated documentation

2024-10-15 14:22 UTC, martonvago commented on sprout/core/write_resource_properties.py
> +def find_resource(package_properties: dict, resource_id: int) -> dict | None:
I left these helpers here for now, but we can move them to separate files if we end up using them somewhere else as well.

2024-10-22 11:16 UTC, signekb requested changes
Very nice ⭐ I have commented on some minor things.

2024-10-22 11:16 UTC, signekb commented on tests/core/test_write_resource_properties.py
> +def test_throws_error_if_resource_properties_incorrect(package_properties_path):
```suggestion
def test_throws_error_if_resource_properties_are_incorrect(package_properties_path):
```
? :)

2024-10-22 11:16 UTC, signekb commented on tests/core/test_write_resource_properties.py
> +def test_throws_error_if_package_properties_incorrect(tmp_path, resource_properties_1):
```suggestion
def test_throws_error_if_package_properties_are_incorrect(tmp_path, resource_properties_1):
```

2024-10-22 11:16 UTC, signekb commented on tests/core/test_write_resource_properties.py
> +def test_throws_error_if_data_path_malformed(
Why a test on the path attribute specifically? :)

2024-10-22 14:33 UTC, martonvago commented on sprout/core/write_resource_properties.py
> +    verify_package_properties(package_properties)
That's a good point!
I think the reason I thought it could make sense to check resource properties was that if their data `path` field is somehow broken then we can't read their ID and compare it with the ID of the incoming resource properties.

2024-10-22 14:45 UTC, martonvago commented on sprout/core/write_resource_properties.py
> +        NotPropertiesError: If the resource or package properties are not correct.
My only problem with this is that we also check whether all our required properties are present on the objects, which is a stricter check than the data package spec alone. And for resources we also check that their data path is well formed.

2024-10-22 14:46 UTC, martonvago commented on sprout/core/write_resource_properties.py
> +    resource_id = get_resource_id(resource_properties)
Don't mind either way!

2024-10-22 14:52 UTC, martonvago commented on tests/core/test_write_resource_properties.py
> +def test_throws_error_if_data_path_malformed(
Because if the resource properties object doesn't have an ID in its data path, we cannot compare the IDs of existing resources to this ID.

2024-10-23 08:49 UTC, signekb commented on sprout/core/write_resource_properties.py
> +        NotPropertiesError: If the resource or package properties are not correct.
True. I just wanted to make it more explicit what "not correct" means.

2024-10-23 08:51 UTC, signekb commented on sprout/core/write_resource_properties.py
> +    verify_package_properties(package_properties)
Ah, also a very good point! Could we make a check specifically for the `path` field, since this field is especially important?

2024-10-23 09:05 UTC, martonvago commented on sprout/core/write_resource_properties.py
> +    verify_package_properties(package_properties)
Oh yeah, I think I added a `verify_data_path` function at some point, so we could just use that -- I'll add it in!

2024-10-23 09:36 UTC, martonvago commented on sprout/core/write_resource_properties.py
> +    verify_package_properties(package_properties)
Actually, I'll make a new PR for that to keep this simpler (because I'm moving `verify_data_path` into its own file.

2024-10-23 09:44 UTC, martonvago commented on sprout/core/write_resource_properties.py
> +        NotPropertiesError: If the resource or package properties are not correct.
Okay, I added this + the incomplete bit 👍

2024-10-23 10:08 UTC, signekb commented on sprout/core/write_resource_properties.py
> +    verify_package_properties(package_properties)
Sounds good 🎉

2024-10-23 10:09 UTC, signekb submitted a review, later dismissed

2024-10-23 19:32 UTC, lwjohnst86 reviewed
Very nice :grin: I only have one comment.

2024-10-23 19:32 UTC, lwjohnst86 commented on sprout/core/write_resource_properties.py
> +        current_resource.update(resource_properties)
This might have a similar issue as #808. Will this need to be updated?

2024-10-24 08:41 UTC, martonvago commented on sprout/core/write_resource_properties.py
> +        current_resource.update(resource_properties)
Yeah, I think we have to decide how exactly we want these updates to behave!

2024-10-28 14:30 UTC, merged