feat: :sparkles: add `edit_package_properties`
seedcase-project/seedcase-sprout pull request #790
Opened 2024-10-16 08:12 UTC by martonvago

## Description

This adds the `edit_package_properties` function.

Closes #715 

This PR needs an in-depth review.

## Checklist

- [x] Added or updated tests
- [x] Tests passed locally
- [x] Linted and formatted code
- [x] Build passed locally
- [x] Updated documentation

2024-10-16 19:24 UTC, lwjohnst86 approved these changes, later dismissed
Very nicely done!! :stars: I only moved the docs over into the docstring, otherwise, amazing!

2024-10-16 19:24 UTC, lwjohnst86 commented on docs/design/implementation/python-functions.qmd
> -Because there already exists an empty `datapackage.json` file, we use
I moved this text over into the function docstring.

2024-10-22 12:25 UTC, signekb requested changes
Once again: Super nice 🌟 
I have added some suggestions and comments.

2024-10-22 12:25 UTC, signekb commented on tests/core/test_edit_package_properties.py
> +def test_throws_error_if_current_package_properties_malformed(tmp_path, properties):
```suggestion
def test_throws_error_if_current_package_properties_are_malformed(tmp_path, properties):
```
? 🤷‍♀️

2024-10-22 12:25 UTC, signekb commented on tests/core/test_edit_package_properties.py
> +def test_throws_error_if_new_package_properties_incorrect(properties_path):
```suggestion
def test_throws_error_if_new_package_properties_are_incorrect(properties_path):
```
? 🤷‍♀️

2024-10-22 12:25 UTC, signekb commented on tests/core/test_edit_package_properties.py
> +    """Should throw NotPropertiesError if the new package properties are incorrect."""
Just noticing the difference in wording here with "incorrect" vs "malformed" on e.g., L58 above. Do you mean something different with these two words or do you use them as synonyms? If the latter, maybe use the same word? :)

2024-10-22 15:19 UTC, martonvago commented on sprout/core/edit_package_properties.py
> +def edit_package_properties(path: Path, properties: dict) -> dict:
Hmm, that takes the `package_id` as argument, right? Which we don't really know in advance.
(Also, I think that function is called `path_package_properties` now, I'll change that in the docstring.)

2024-10-22 15:25 UTC, martonvago commented on tests/core/test_edit_package_properties.py
> +def test_throws_error_if_current_package_properties_malformed(tmp_path, properties):
Don't mind either way, but I do have a tendency to drop the "to be" in function names.

2024-10-22 15:37 UTC, martonvago commented on tests/core/test_edit_package_properties.py
> +    """Should throw NotPropertiesError if the new package properties are incorrect."""
I'm trying to use "malformed" as the opposite of "well-formed" (so something that violates `verify_properties_are_well_formed`) and "incorrect" as something that violates `verify_package_properties`. So I guess this makes "incorrect" a broader term. Properties that are malformed or incomplete are also incorrect, but properties that are incorrect are not necessarily both malformed and incomplete. But I make no claims of having been super consistent on this.

2024-10-23 03:02 UTC, lwjohnst86 approved these changes

2024-10-23 03:02 UTC, merged