feat: ✨ verify data path before extracting ID
seedcase-project/seedcase-sprout pull request #807
Opened 2024-10-23 15:06 UTC by martonvago

## Description

This PR makes sure that every time we extract the ID from the data path of a resource, we verify that it is well formed ([discussion](https://github.com/seedcase-project/seedcase-sprout/pull/784#discussion_r1801271054)). 

Related to #784

This PR needs an in-depth review.

## Checklist

- [x] Added or updated tests
- [x] Tests passed locally
- [x] Linted and formatted code
- [x] Build passed locally
- [x] Updated documentation

2024-10-23 15:07 UTC, martonvago commented on sprout/core/verify_data_path.py
I moved this to its own file

2024-10-23 15:07 UTC, martonvago commented on sprout/core/verify_data_path.py
> +    data_path = Path(properties.get("path", ""))
Changed this to handle the case where `path` is missing

2024-10-24 13:15 UTC, signekb requested changes
Seems fine to me 👍 I have added some minor suggestions

2024-10-24 13:15 UTC, signekb commented on tests/core/test_write_resource_properties.py
> +    )
```suggestion
    package_properties = PackageProperties(
        name="my-package",
        id="123-abc-123",
        title="My Package",
        description="This is my package.",
        version="2.0.0",
        created="2024-05-14T05:00:01+00:00",
        resources=[str(Path("no", "id"))],
    )
```
Why not just add the malformed path directly?

2024-10-28 08:18 UTC, martonvago commented on sprout/core/verify_data_path.py
> +        error = ResourceError(
This is a class from `frictionless`, so it comes as is :)

2024-10-28 14:28 UTC, lwjohnst86 approved these changes
:grin: :tada: :clinking_glasses:

2024-10-28 14:29 UTC, merged