fix: Avoid overwriting non-edited properties in `edit_package_properties()`
seedcase-project/seedcase-sprout pull request #808
Opened 2024-10-23 15:44 UTC by signekb

## Description

**I have been on quite a digging adventure today 🕳️ , so please let me know if this is complete nonsense 😅  - but I *do* think that I'm on to something.** 

**As always: I'm very open to other ways of solving this** ☺️ 

While creating the guide for creating resources, I realised that there was an error in the packages guide. This error revealed that `edit_package_properties()` overwrites all properties `datapackage.json` - leaving the required properties `id`, `created`, and `version` empty: 

## Excerpt from the package guide
### The step right before the error (notice the empty values for `id`, `created`, and `version`)
![image](https://github.com/user-attachments/assets/ef277e47-cca2-4896-af2a-21250f410ef9)

 ### The step creating the error:
![image](https://github.com/user-attachments/assets/3f385448-1192-458d-93e6-1fa71dacff8f)

## Error log: 
![image](https://github.com/user-attachments/assets/c6aebf78-2aff-4abb-a10f-ce8683f19324)

## Proposed solution

1. [test: 🧪 update fixtures to reveal bug](https://github.com/seedcase-project/seedcase-sprout/commit/f0be0a071e1f0eecff3a229e08ac40f6bb055d0e) First I updated the fixtures to reveal the bug. I made sure that the "initial" properties file is valid by using `create_package_structure()` and adding the required values in the `properties_path` fixture. Then, I only included one value in the `properties` fixture to reveal that with the current `edit_package_properties()`, the entire file is overwritten. We now see that the tests fail bc we are missing required values
2.[test: 🧪 update test with correct expected properties](https://github.com/seedcase-project/seedcase-sprout/commit/61115d5cc2e2956abc837dd4fdb2e7d94f4dc15e) I then updated the test with the correct expected values (the old properties with **only** the new property edited 
3. [fix: 🐛 update to remove default package properties before editing](https://github.com/seedcase-project/seedcase-sprout/commit/b1c5be50f55d4ee79c0bd1b0283676083f0cbf76) I made a fix for this that made sense to me: Remove any default values in the properties dict before updating / "merging" the current with the new properties. **I am very open to other ways to solve this** 
4. [feat: ✅ update to throw ValueError given empty properties](https://github.com/seedcase-project/seedcase-sprout/commit/ab0c3c24869d777f63de517dbbbe680f6eed2651) Lastly, I found that it might make more sense if an empty properties file raises a ValueError. So I made a check in `verify_properties_are_well_formed.py` for if `properties` is empty. This required some changed in the errors thrown in other tests.

This PR needs an in-depth review.

## Checklist

- [X] Added or updated tests
- [X] Tests passed locally
- [X] Linted and formatted code
- [X] Build passed locally

2024-10-23 19:25 UTC, lwjohnst86 requested changes
Nice sleuthing! :detective: I have only one question.

2024-10-23 19:25 UTC, lwjohnst86 commented on sprout/core/edit_package_properties.py
> +    return verify_package_properties(current_properties | properties)
I'm a bit confused about what the `|` does here, could you explain that? Reading about `|`, it seems like it compares bits between objects. What does it do here?

2024-10-23 19:25 UTC, lwjohnst86 commented on sprout/core/edit_package_properties.py
> -    current_properties.update(properties)
Nice catch on this bug!

2024-10-24 08:22 UTC, signekb commented on sprout/core/edit_package_properties.py
> +    return verify_package_properties(current_properties | properties)
They describe it in [this post](https://ridwanray.medium.com/the-pipe-symbol-in-python-133239503fec).
As of my understanding both `|` and `.update()` "merges" or "unites" dictionaries and if a key is in both the dictionaries, the value from the second dictionary is used. The main difference is that the `|` returns a new dictionary while `.update()`edits the first dictionary and returns `None`.

So I could accomplish the same by writing this instead: 

```suggestion
	current_properties.update(properties)
    return verify_package_properties(current_properties)
``` 

So, the bug was not because of `.update()`, but rather because the `properties` dict included default values that was overwritten. With a `properties` dict with default values, the `|` would also overwrite the values in `current_properties`

2024-10-24 09:33 UTC, martonvago commented
I’m just thinking that if the above is a problem, an alternative way of structuring things to avoid it would be the following (just a quick sketch):
```python
@dataclass
class MyProperties():
    name: str | None = None
    id: str  | None = None
    title: str | None = None
    encoding: str | None = None
    keywords: list[str] | None = None

    @classmethod
    def default(cls: Type["MyProperties"]) -> "MyProperties":
        return cls(
            name="", 
            id="", 
            title="", 
            encoding="utf-8",
            keywords=[]
        )
    
    @property
    def asdict(self) -> dict:
        return {
            key: value for key, value in asdict(self).items() if value is not None
        }
```
Here, we’d be completely separating the creation of a default properties object. This would allow us to return to using `None` for unset values in the constructor. Then, we could tweak the `asdict` property/method to include only fields with a non-None value in the dictionary representation of the object. These dictionaries would be “safe” to use in our operations because they don’t contain any surprises.
But I’ll have a think if there are other options.

2024-10-24 11:30 UTC, signekb commented
Ahhh, I like that solution, @martonvago !

2024-10-29 15:02 UTC, martonvago requested changes
🦹 What a heroic effort!! 🦹‍♂️  Only minor comments

2024-10-30 08:31 UTC, signekb commented on sprout/core/properties.py
> +    @abstractmethod
Oh,  I added abstractmethods as a way of trying to ensure that all subclasses define that method. Correct me if I'm wrong? 
Could we add both?

2024-10-30 08:34 UTC, signekb commented on sprout/core/properties.py
> +        """Abstract method that needs to be implemented by subclasses."""
```suggestion
        """Creates an instance with default values."""
```

2024-10-30 08:35 UTC, signekb commented on sprout/core/properties.py
> +    def default(cls: "type[ContributorProperties]") -> "ContributorProperties":
Oooo, much nicer!

2024-10-30 08:37 UTC, signekb commented on sprout/core/properties.py
> +    def default(cls: "type[PackageProperties]") -> "PackageProperties":
I think that's a good idea! Let's see what @lwjohnst86 thinks

2024-10-30 08:38 UTC, martonvago commented on sprout/core/properties.py
> +    @abstractmethod
Yeah, I'm suggesting to add both! (At least to me our suggestions look the same 😅 )

2024-10-30 08:39 UTC, signekb commented on tests/core/test_create_resource_properties.py
> -from sprout.core.not_properties_error import NotPropertiesError
Nopes! Thanks for the catch

2024-10-30 08:39 UTC, signekb commented on tests/core/test_create_resource_properties.py
>  from sprout.core.create_resource_properties import create_resource_properties
```suggestion
from sprout.core.create_resource_properties import create_resource_properties
from sprout.core.not_properties_error import NotPropertiesError
```

2024-10-30 08:44 UTC, signekb commented on sprout/core/properties.py
> +    def as_pruned_dict(self) -> dict:
Yeahh, `as_pruned_dict` is a bit long 😅 
I'm also fine with any of the ones you suggest, except `to_dict()` bc I think it's important to be explicit about that it's not just transforming the object to a dict but actually removing `None` values

2024-10-30 08:46 UTC, signekb commented on sprout/core/properties.py
> +    @abstractmethod
Omg 😅  Good morning, Signe!

2024-10-30 11:16 UTC, signekb commented on tests/core/test_edit_package_properties.py
I actually think that I'll remove it here and make the changes needed in other places in `core` in stacked PRs

2024-10-30 12:09 UTC, signekb commented on sprout/core/properties.py
> +        return cls(fields=[], reference=None)
Alternatively, we could omit all None fields in the `default` method. Then, they would be None anyways?

2024-10-30 12:10 UTC, signekb commented on sprout/core/properties.py
> +        return cls(fields=[], reference=None)
And I agree: As we start using more of the Properties subclasses, it will be clearer what we'll need in regards to default values

2024-10-30 12:14 UTC, signekb commented on tests/core/test_properties.py
> +    ],
I decided to just use one of the subclasses (`ResourceProperties()`) bc it's simpler than adding a TestProperties class and creating a fixture for it, if we don't use it in any other tests anyways 🌸

2024-10-30 13:46 UTC, lwjohnst86 reviewed
Lovely! Only one comment.

2024-10-30 13:46 UTC, lwjohnst86 commented on sprout/core/properties.py
> +    def as_pruned_dict(self) -> dict:
Great options! I don't love how `prune` feels in the mouth when saying it :stuck_out_tongue: And I just think of prunes (the food) haha going with the R package purrr's vocabulary, it would be the verb compact (which does the same as what we are trying to do). So I prefer `compact_dict()` or `to_compact_dict()` (or `as_`). I have no preference on whether `as` or `to` are used, or if we drop them.

2024-10-30 14:56 UTC, martonvago commented on sprout/core/properties.py
> +        return cls(fields=[], reference=None)
Ah yeah, good point about omitting the `None` fields!

2024-10-30 15:29 UTC, martonvago requested changes

2024-10-30 15:29 UTC, martonvago commented on sprout/core/properties.py
> +    def default(cls: Type[Self]) -> Self:
```suggestion
    def default(cls: "type[Self]") -> Self:
```
This would be an alternative. Just because `Type` seems to be [deprecated](https://docs.python.org/3/library/typing.html#typing.Type)? But I'm not sure how much we care about that to be honest.

2024-10-30 15:29 UTC, martonvago commented on tests/core/test_properties.py
>  def test_as_pruned_dict_preserves_only_non_none_values(properties, expected_dict):
I guess you could also just test one child class here, but this is certainly not doing any harm :)

2024-10-30 15:29 UTC, martonvago commented on sprout/core/properties.py
> +    def as_pruned_dict(self) -> dict:
Okay, then I'll put in a vote for `compact_dict` because it is a property anyway, so making it less action-y seems fine.

2024-10-30 15:29 UTC, martonvago commented on sprout/core/properties.py
> +    def default(cls: "type[PackageProperties]") -> "PackageProperties":
Just bumping this again because I think including these default values here is kinda the entire idea behind having these `default` functions.

2024-10-30 19:08 UTC, signekb commented on sprout/core/properties.py
> +    def as_pruned_dict(self) -> dict:
Hah, I had a feeling that you wouldn't like pruned, @lwjohnst86 ! I know it from ML / decision trees. 

`compact_dict` it is!

2024-10-30 20:29 UTC, signekb commented on sprout/core/properties.py
> +    def as_pruned_dict(self) -> dict:
```suggestion
    def compact_dict(self) -> dict:
```

2024-10-30 20:37 UTC, signekb commented on sprout/core/properties.py
> +        return cls(fields=[], reference=None)
I'll remove them! It feels redundant to define them as None twice (even though it might be more explicit to keep them)

2024-10-31 07:48 UTC, signekb commented on sprout/core/properties.py
> +        """Abstract method that needs to be implemented by subclasses."""
```suggestion
        """Creates an instance with default values."""
```

2024-10-31 10:16 UTC, martonvago requested changes
Looking great now!! Just a single small comment

2024-10-31 12:17 UTC, martonvago submitted a review, later dismissed
Yay!!! 🎉

2024-10-31 13:40 UTC, lwjohnst86 commented
Hmm, the tests are still failing. You still on that @signekb or need help?

2024-11-03 15:25 UTC, lwjohnst86 submitted a review, later dismissed
Once #833 has been fixed and merged, this is good to go!

2024-11-03 17:31 UTC, merged