fix: 🩹 update `edit_package_properties()` based on the changes to the `Properties` classes
seedcase-project/seedcase-sprout pull request #833
Opened 2024-11-01 15:50 UTC by signekb

## Description

NB this is a stacked PR merging to #808 

This PR changes the behaviour of `edit_package_properties()` based on the changes to the `Properties` classes in #808 

This work was done in collaboration with @martonvago 🌷

## Checklist

- [X] Added or updated tests
- [X] Tests passed locally
- [X] Linted and formatted code
- [X] Build passed locally

2024-11-01 16:32 UTC, martonvago approved these changes
👍👍👍

2024-11-03 15:20 UTC, lwjohnst86 requested changes
Nice :relaxed: only one suggestion

2024-11-03 15:20 UTC, lwjohnst86 commented on tests/core/test_edit_package_properties.py
> +    ) == current_properties | new_properties
```suggestion
    assert edit_package_properties(
        properties_path, new_properties
    ) == current_properties | new_properties
```

Was this assert missing?

2024-11-03 17:30 UTC, lwjohnst86 approved these changes

2024-11-03 17:30 UTC, merged