docs: :memo: describe split between `lib` and `core`
seedcase-project/seedcase-sprout pull request #872
Opened 2024-11-13 15:33 UTC by lwjohnst86

## Description

As I was writing the guide on creating data resources and late night swirling thoughts, combined with potential users who would code in Python, I thought that there should actually be Python code that mimicks what the CLI will do... meaning code that has a lot more assumptions and opinions tied to it. Based on discussions we've had over the months, I see a lot of value in having a highly flexible `core`, that would allow us to easily integrate e.g. plugins/extensions, not be tied to the specific folder and file structure we prescribe, and allow others to customize things a lot more to their needs. But there is also a lot of value in having some code that is very opinionated and simple. For instance, not needing to pass around `path_*()` for all functions and just assume "properties will always be the root of the package", etc.

Closes #850

This PR needs an in-depth review.

2024-11-13 17:01 UTC, lwjohnst86 commented on docs/design/architecture/modular-design.qmd
> +    `lib` and stored in `seedcase_sprout/lib/`. This module abstracts
Not sure what the right name for this is, but `lib` sounded right. Open to ideas.

2024-11-14 10:55 UTC, signekb commented on docs/design/architecture/modular-design.qmd
> +`import seedcase_sprout.core` statement. Only external-facing functions
```suggestion
`import seedcase_sprout.core as sp` statement. Only external-facing functions
```
To include that we use (and hopefully others will start using) shorthand?

2024-11-14 10:55 UTC, signekb commented on docs/design/architecture/modular-design.qmd
> +    `lib` and stored in `seedcase_sprout/lib/`. This module abstracts
Just so make sure I understand: You want to create `lib` that includes all the assumptions about e.g., `paths` that you wanted to avoid in `core`? Will `lib` then depend on the functionality build in `core` to avoid having the functionality duplicated?

2024-11-14 10:56 UTC, signekb commented on docs/design/architecture/modular-design.qmd
> +    `lib` and stored in `seedcase_sprout/lib/`. This module abstracts
I'm thinking: Do we *need* core to be without assumptions? Couldn't `lib` (i.e., an opinionated package more closely related to the CLI) just be `core`?

2024-11-14 10:58 UTC, lwjohnst86 commented on docs/design/architecture/modular-design.qmd
> +    away and simplified many of the steps and functions available in
```suggestion
    away and simplifies many of the steps and functions available in
```

2024-11-14 10:58 UTC, lwjohnst86 commented on docs/design/architecture/modular-design.qmd
> +-   A higher-level, opinionated Python implementation of `core`, named
```suggestion
-   A higher-level, opinionated Python abstraction of `core`, named
```

2024-11-14 10:58 UTC, lwjohnst86 commented on docs/design/architecture/modular-design.qmd
> +    `lib` and stored in `seedcase_sprout/lib/`. This module abstracts
You got it!

2024-11-14 11:05 UTC, signekb commented on docs/design/architecture/modular-design.qmd
> +    `lib` and stored in `seedcase_sprout/lib/`. This module abstracts
@lwjohnst86 what do you think about my comment above?

2024-11-14 13:04 UTC, martonvago reviewed
If you think there will be enough stuff in `core` and `lib` separately then I don’t mind! 
- What would be another example of `lib`-specific functionality? Other than the paths / IDs, I mean. I think you mentioned something about how flexible the data upload/adding process could be.
- If the higher-level components (`cli`, `app`) depend directly on `core` and not on `lib`, will we not end up reimplementing some of the functionality of `lib` in these? I’m just thinking that for the same reasons that it would be nice to have these simplifications now, it will be nice to have them in the higher-level components too?

2024-11-14 15:09 UTC, lwjohnst86 commented
@signekb and @martonvago here are some examples of why we can't simply have `lib` be used in `cli`/`app` and why only `core` would make the experience of coding in Python as an user (not developer) not enjoyable.

Let's take a simple example of making an edit to the description field of the package properties. In `core`, the steps to take currently are (might not be precisely what we have, but it's the idea):

``` python
current_properties = read_properties(path_properties(package_id=1))
updated_properties = edit_package_properties(
	current_properties,
	PackageProperties(description="Blah blah")
)
update_readme(updated_properties, path_readme(1))
write_package_properties(updated_properties, path_package_properties(package_id=1))
```

It would be nicer if it could be something like:

``` python
update_package_properties(
	package_id=1,
	properties=PackageProperties(description=...)
)
```

And internally it will read the current properties, update the README, write back to the properties. 

But this code above can't be used in `cli`, because an assumption of Python code is *no interaction from the user*, while `cli` code often has interaction from the user (e.g. "do you want to delete this field? (y/n)"). Instead, internally, `cli` would use the distinct steps from `core`. For instance, if a user does:

``` bash
sprout update package properties --package_id 1 --description "blah blah"
```

1. Read properties
2. Check that all required fields are included in the properties, if no, ask user to include some text for those fields.
3. Update the README with the new properties.
4. Write back to the package properties.
5. Output some basic info back to the user about what was done.

There will be even more checks and code for the `app`, on top of sending output back to the user's screen as they type stuff. None of that would be possible if we used `lib` rather than `core`.

This gets even more complicated with adding resources, e.g. we want to add more raw data files using a plugin for that data format/machine. In `core`, it might be (some functions are not described in design because I realize as writing the `write_resource_parquet()` and the creating resource guide that we are missing several steps and actions):

``` python
write_resource_data_to_raw(
	path_resource_raw(package_id=1, resource_id=1),
	# Path to raw data file on users computer.
)

data = read_raw_files(path_resource_raw_files(1, 1))
cleaned = custom_plugin_for_data_from_specific_machine(data)

resource_properties = read_resource_properties(path_properties(1))
checked = check_data(cleaned, resource_properties)

write_resource_parquet(checked, path_resource_data(1, 1))

updated_properties = update_resource_properties(
	path_properties(1),
	ResourceProperties(
		schema=TableSchemaProperties(
			fields=list[FieldProperties(
				bytes=file_bytes(path_resource_data(1, 1))
			)
		)
	)
)

write_resource_properties(
	updated_properties,
	path_properties(1)
)

update_readme(read_properties(path_properties(1)), path_readme(1))
```

And this is just off the top of my head. That's not a fun coding experience for an non-developer Python user. It would be nicer if it was:

``` python
add_resource_data(
	package_id=1,
	resource_id=1,
	data_path=path....,
	plugin=custom_plugin_action
)
```

Is this clear enough to describe the issue? :face_with_spiral_eyes:

2024-11-18 11:49 UTC, martonvago commented
Thanks for the detailed explanation!

I think having `lib` on top of `core` is very well justified! If the user flows in `cli` will be different from the flows in `lib` because there will be more interactivity, then I can see how `cli` couldn't directly use `lib`. 

As for `app`, it's harder for me to say without knowing how the backend and frontend will interact / how integrated they will be, especially now that maybe we won't use Django. If the backend implementation will have lots of extra bits (like we would have had with Django), then I can see how it couldn't rely on `lib`. If, on the other hand, the backend logic is largely the same, then I can imagine hooking a frontend onto functions like `update_package_properties` in `lib`, provided that they throw helpful errors.

2024-11-18 11:55 UTC, martonvago submitted a review, later dismissed

2024-11-18 12:11 UTC, signekb commented
@lwjohnst86 Yes, thanks for elaborating! 
I think that I just needed some time to get some of these new pieces to fit together, and to me, it actually makes sense to introduce `lib` now as well. Especially in terms of the interactivity we want in the CLI and the app and with having a smoother experience when using the Python package.
I definitely don't have an overview of how everything will look down the line - but this seems to be an appropriate step 👍  
And not as much of a switch of direction as I initially thought 😅

2024-11-18 12:33 UTC, signekb requested changes
Just have some additional questions/suggestions :)

2024-11-18 12:33 UTC, signekb commented on docs/design/architecture/modular-design.qmd
> +would be exposed to the user and to other programs.
In terms of external-facing functions, will this be mostly/only `lib` functions then? Or where do we draw the internal/external line?

2024-11-18 12:33 UTC, signekb commented on docs/design/architecture/modular-design.qmd
> +their own needs. This modular and flexible "lower level" design allows
How do we imagine developers and potentially users would want to configure/customise to their own needs? Would that be in the form of extensions?

2024-11-18 12:33 UTC, signekb commented on docs/design/architecture/modular-design.qmd
> +    created and managed.
```suggestion
    created, structured, and managed.
```
I'm thinking in terms of folder structure here

2024-11-18 12:33 UTC, signekb commented on docs/design/architecture/modular-design.qmd
> +-   For our CLI, it is placed in the module `seedcase_sprout/cli/`. Each
```suggestion
-   The CLI is placed in the module `seedcase_sprout/cli/`. Each
```

2024-11-18 12:33 UTC, signekb commented on docs/design/architecture/modular-design.qmd
> +    Python code into a CLI program.
```suggestion
    Python code into a CLI.
```

2024-11-18 12:33 UTC, signekb commented on docs/design/architecture/modular-design.qmd
> +-   The web API is in `seedcase_sprout/api/`. Each endpoint imports the
This might be my confusion/ignorance, but couldn't we just remove this `api` split for now?

2024-11-18 16:01 UTC, lwjohnst86 commented on docs/design/architecture/modular-design.qmd
> +their own needs. This modular and flexible "lower level" design allows
Yea, extensions, not using the path structure we've decided on, adding extra processing steps that might not be suitable for a full extension/plugin, or if they just want to use specific functions within sprout without using our full workflow/process. A bit like how we'd like individual/finer-grained functionality from frictionless, but it isn't possible to do.

2024-11-18 16:01 UTC, lwjohnst86 commented on docs/design/architecture/modular-design.qmd
> +-   The web API is in `seedcase_sprout/api/`. Each endpoint imports the
That's fair! We can always add it back later.

2024-11-18 16:01 UTC, lwjohnst86 commented on docs/design/architecture/modular-design.qmd
> +    same or slightly modified code.
```suggestion

```

2024-11-18 16:03 UTC, merged