docs: :building_construction: design of the check functions
seedcase-project/seedcase-sprout pull request #874
Opened 2024-11-13 18:36 UTC by lwjohnst86

## Description

This PR starts adding the design/potential functions of the various check functionality.

Closes #834 and closes #849

This PR needs an in-depth review.

2024-12-03 12:38 UTC, signekb commented on docs/design/implementation/core.qmd
> +### Properties checked against the data
Ignore this for now.

2024-12-03 12:54 UTC, signekb commented on docs/design/implementation/core.qmd
> +    - `check_properties_against_recommendations()`: Check if the
```suggestion
    - `check_properties_against_standard_recommendations()`: Check if the
```

2024-12-03 12:58 UTC, signekb commented on docs/design/implementation/core.qmd
> +- `check_properties()`: This is a wrapper function that runs all the
```suggestion
- `check_properties(actual, expected)`: This is a wrapper function that runs all the
```
actual dict: "our" schema
expected dict: schema to compare against

Edits to the json schema ("spec"/standard) will be done outside of this function. E.g., removing resource MinItems.

2024-12-03 13:02 UTC, signekb commented on docs/design/implementation/core.qmd
> +
Have a local version of the schema within the `check` package

2025-03-24 12:31 UTC, lwjohnst86 commented
In prep for tomorrows meeting, I've (finally) put the checks into the functions doc. I really should have done this sooner, it was a major oversight on my side :grimacing:

2025-03-24 14:37 UTC, martonvago requested changes
Makes sense! :grin:

2025-03-24 14:37 UTC, martonvago commented on docs/design/interface/functions.qmd
> +wrappers around the `check_datapackage` "sub-packakge" (that we will
```suggestion
wrappers around the `check_datapackage` "sub-package" (that we will
```

2025-03-24 14:37 UTC, martonvago commented on docs/design/interface/functions.qmd
> +eventually split into it's own package).
```suggestion
eventually split into its own package).
```

2025-03-24 14:37 UTC, martonvago commented on docs/design/interface/functions.qmd
> +more details. The *only* checks the package properties.
```suggestion
more details. This *only* checks the package properties.
```
?

2025-03-24 14:37 UTC, martonvago commented on docs/design/interface/functions.qmd
> +the `fields.name` properties, the columns' data types against the
```suggestion
the `field.name` properties, the columns' data types against the
```
Because `fields` is a list, so it has no attributes. `field.name` can be read as the `name` attribute of each `field` in `fields`, but feel free to rephrase if it's not clear enough. (Same for the others.)

2025-03-31 08:44 UTC, merged