docs: :memo: update requirements doc
seedcase-project/seedcase-sprout pull request #876
Opened 2024-11-13 19:23 UTC by lwjohnst86

## Description

This PR updates the requirements doc to reflect where we are now at with our design. Mostly just revises the language around Data Resource.

This PR needs an in-depth review.

2024-11-14 08:19 UTC, martonvago requested changes
Makes sense!

2024-11-14 08:19 UTC, martonvago commented on docs/design/architecture/requirements.qmd
> +-   Store, organize, and manage multiple, distinct data sources per user
```suggestion
-   Store, organize, and manage multiple distinct data sources per user
```
?

2024-11-18 13:31 UTC, K-Beicher submitted a review, later dismissed
Looks good

2024-11-18 15:58 UTC, signekb requested changes
Very nice 👍 Just some minor suggestions

2024-11-18 15:58 UTC, signekb commented on docs/design/architecture/requirements.qmd
> +Things Sprout must do:
```suggestion
Sprout must:
```
To fit with 
"run on [...]" , "integrate GDPR [...] ", "be able to [...]" etc., maybe?

2024-11-18 15:58 UTC, signekb commented on docs/design/architecture/requirements.qmd
> +-   Use remotely on servers and locally on computers: The location where
```suggestion
-   Run remotely on servers and locally on computers: The location where
```

2024-11-18 15:58 UTC, signekb commented on docs/design/architecture/requirements.qmd
> +    or group of users (as in a server setting): Researchers rarely
```suggestion
    or group of users (for example in a server setting): Researchers rarely
```
? At least the "as" confused me a bit here :)

2024-11-18 15:58 UTC, signekb commented on docs/design/architecture/requirements.qmd
> +    collect and work on one data source over their careers or at any
```suggestion
    collect and work on one data source at any
```

2024-11-18 15:58 UTC, signekb commented on docs/design/architecture/requirements.qmd
> +    given time. So Sprout must be able to handle multiple distinct data
```suggestion
    given time. So, Sprout must be able to handle multiple distinct data
```

2024-11-18 15:58 UTC, signekb commented on docs/design/architecture/requirements.qmd
> +-   Upload or update data: Data input into Sprout could happen in
Why "or" and not "and"?
```suggestion
-   Upload and update data: Data input into Sprout could happen in
```

2024-11-18 15:58 UTC, signekb commented on docs/design/architecture/requirements.qmd
> +-   Upload or update data: Data input into Sprout could happen in
```suggestion
-   Upload or update data: Data can be added to Sprout could happen in
```
To avoid "input into"

2024-11-18 15:58 UTC, signekb commented on docs/design/architecture/requirements.qmd
> +    are not static and can change over time. Sprout needs to be able to
```suggestion
    are not static and can change over time. Sprout must
```

2024-11-18 15:58 UTC, signekb commented on docs/design/architecture/requirements.qmd
> +    versions of the data. This also is necessary for legal compliance
```suggestion
    versions of the data. This is also necessary for legal compliance
```

2024-11-18 15:58 UTC, signekb commented on docs/design/architecture/requirements.qmd
> +Things Sprout will not do:
```suggestion
 Sprout will not:
```

2024-11-18 15:58 UTC, signekb commented on docs/design/architecture/requirements.qmd
> +    relation to running checks on the quality of the data.
```suggestion
-   Run any analytic computing or data science work: While some
    data processing and analysis will occur, it is only in
    relation to running checks on the quality of the data and metadata.
```

2024-11-18 16:09 UTC, merged