build: :wrench: add GitHub workflow to keep track of Data Package versions
seedcase-project/seedcase-sprout pull request #881
Opened 2024-11-15 13:25 UTC by martonvago

## Description

This adds a GitHub workflow for checking for updates in the Data Package standard. If there is an update, an issue is raised.

Closes #862 

This PR needs an in-depth review.

## Checklist

- [x] Added or updated tests
- [x] Updated documentation
- [x] Ran `just run-all`

2024-11-15 13:50 UTC, martonvago commented on .github/workflows/check-data-package-version.yml
> +          GH_TOKEN: ${{ secrets.ADD_TO_BOARD }}
It looks like in order for the creation of this issue to be picked up by other workflows (like the one that adds it to the project), the token needs to  include the `project` scope. I think our `ADD_TO_BOARD` token has this, but I can't actually look at it, so this is just a guess. Alternatively, we can add it to the project as part of `gh issue create`, but it will also need the `project` scope for that. We can also use the API endpoint for adding the issue and then `GITHUB_TOKEN` seems to be enough.

2024-11-15 13:58 UTC, martonvago commented
We can test this by e.g. setting the current version to `v1.0` and triggering it manually.

2024-11-21 18:17 UTC, lwjohnst86 requested changes
Very nice!! Just some comments :grin:

2024-11-21 18:17 UTC, lwjohnst86 commented on .github/workflows/check-data-package-version.yml
> +          latest_version=$(curl -s https://api.github.com/repos/$DP_REPO/releases/latest | jq -r .tag_name)
```suggestion
          latest_version=$(curl -s https://api.github.com/repos/$DP_REPO/releases/latest | jq -r .tag_name)
          latest_version=$(gh release list -R $DP_REPO --limit 1 --json name -q ".[].name"
```

Just a slightly clearer, slightly shorter version :stuck_out_tongue: mainly so I can use gh cli in more places :stuck_out_tongue: So this takes the top list of releases (latest) and gives back it's name.

2024-11-21 18:17 UTC, lwjohnst86 commented on .github/workflows/check-data-package-version.yml
> +            - Update the current version of \`$DP_REPO\` in the '$GH_WORKFLOW' GitHub workflow."
```suggestion

            - [ ] Replace the old JSON schema of the Data Package standard with the new one downloaded from the website.
            - [ ] Update the current version of \`$DP_REPO\` in the '$GH_WORKFLOW' GitHub workflow."
```

Just so they are checklists.

2024-11-21 18:17 UTC, lwjohnst86 commented on .github/workflows/check-data-package-version.yml
> +    - cron: 0 0 * * 0
This probably doesn't need to be ran that often, maybe even once a month or every 2 months.

2024-11-22 09:30 UTC, martonvago commented on .github/workflows/check-data-package-version.yml
> +          GH_TOKEN: ${{ secrets.ADD_TO_BOARD }}
Okay! We just need to remember to add it :smile: I don't think I can see the settings

2024-11-22 09:31 UTC, martonvago commented on .github/workflows/check-data-package-version.yml
> +          latest_version=$(curl -s https://api.github.com/repos/$DP_REPO/releases/latest | jq -r .tag_name)
Okay! I did it with `view` and `tagName`, but otherwise the same

2024-11-25 08:42 UTC, lwjohnst86 approved these changes

2024-11-25 08:44 UTC, lwjohnst86 commented
I don't know how the synching will work, I *think* that this file won't be affected, but it might get deleted, with the way I've set the synching up. If it does, we'll move this action over into the `.github` repo I think.

2024-12-03 13:33 UTC, signekb approved these changes

2024-12-03 14:02 UTC, merged