fix: :bug: compact form of nested properties
seedcase-project/seedcase-sprout pull request #887
Opened 2024-11-20 09:37 UTC by martonvago

## Description

This fixes a problem where `compact_dict` was not removing `None` values from nested objects.

This PR needs a quick review.

## Checklist

- [x] Added or updated tests
- [x] Updated documentation
- [x] Ran `just run-all`

2024-11-20 09:44 UTC, martonvago commented on seedcase_sprout/core/properties.py
> +        )
This is basically moving the `None`-check inside `asdict`. `asdict` walks the entire data structure, turning all elements into dictionaries recursively. The problem was that we were only filtering `None` values on the outermost layer, leaving nested `None` values in place. Turns out we can pass a custom function to `asdict` for it to use as it processes the data structure. If we add the `None`-check here, it will be applied everywhere recursively.

2024-11-21 09:02 UTC, signekb requested changes
Ah! Nice catch! Thanks 🎉 
I have made one suggestion to make it a bit cleaner. But, if you like the way you implemented it more, I will not object ☺️

2024-11-21 09:02 UTC, signekb commented on seedcase_sprout/core/properties.py
> +        )
Would this be a bit cleaner, so we avoid the `tuple[1]`? 
```suggestion
        return asdict(
            obj=self,
            dict_factory=lambda tuples: {
                key: value for key, value in tuples if value is not None
            },
        )
```

2024-11-21 17:22 UTC, lwjohnst86 approved these changes
:clinking_glasses:

2024-11-21 17:23 UTC, merged