feat: :sparkles: check properties against standard
seedcase-project/seedcase-sprout pull request #905
Opened 2024-12-04 14:19 UTC by martonvago

## Description

This PR adds general-purpose (so not Sprout-specific) checks.

- `check_resource_properties`: checks a single resource properties object against the Data Resource standard
- `check_package_properties`: checks only package properties against the Data Package standard; the internal structure of resource properties is ignored; no resources and empty resources (`[]`) are allowed; `resources` of the wrong type are not allowed
- `check_properties`: checks if a full set of properties (package AND resource) matches the Data Package standard; the internal structure of resource properties is checked; no resources and empty resources are not allowed

For all 3, there's an argument for turning on recommendations.
I added some straightforward recommendations, but I will put the rest in an issue.

I also think this could do with some more tests eventually!

Closes #834, closes #864 

This PR needs an in-depth review. Focus on if this is the behaviour and interface we want.

## Checklist

- [x] Added or updated tests
- [x] Updated documentation
- [x] Ran `just run-all`

2024-12-05 13:33 UTC, martonvago commented on data-package-schema.json
We could put this somewhere else too

2024-12-05 13:35 UTC, martonvago commented on seedcase_sprout/core/checks/check_package_properties.py
> +    properties is ignored.Structural, type and format constraints are all checked.
```suggestion
    properties is ignored. Structural, type and format constraints are all checked.
```

2024-12-05 13:36 UTC, martonvago commented on seedcase_sprout/core/checks/check_package_properties.py
> +    schema = read_json(DATA_PACKAGE_SCHEMA_PATH)
I'm loading the schema here because I don't see how we could use another schema in this context

2024-12-05 13:39 UTC, martonvago commented on seedcase_sprout/core/checks/check_package_properties.py
> +    del schema["properties"]["resources"]["items"]
This removes the requirements that `resources` has to be present and not empty, but leaves the type check (if `resources` is present)

2024-12-05 13:47 UTC, martonvago commented on seedcase_sprout/core/checks/check_properties.py
The other way of writing this was to combine `check_package_properties` and `check_resource_properties`, but then (1) the error tree is defective (it cannot recreate the json path from the package to the nested resources automatically) and (2) it allows no or empty `resources`, which I wasn't sure was what we wanted for this

2024-12-05 13:49 UTC, martonvago commented on seedcase_sprout/core/checks/config.py
Is this the right name for this?

2024-12-05 13:53 UTC, martonvago commented on tests/core/test_check_properties.py
There's a lot of overlap between these tests and the tests for the other check functions

2024-12-12 13:08 UTC, lwjohnst86 requested changes
Super nice!! I only have one comment

2024-12-13 12:17 UTC, signekb requested changes
Super nice ⭐ 🌟 
Just have some suggestions and some questions for my understanding.

2024-12-13 12:18 UTC, signekb commented on tests/core/test_check_properties.py
Maybe that's ok?

2024-12-13 14:18 UTC, signekb commented on seedcase_sprout/core/checks/config.py
> +    r"[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$"
(@lwjohnst86 says no 😓 😅 )

2024-12-13 17:28 UTC, martonvago commented on seedcase_sprout/core/checks/add_resource_recommendations.py
> +    return schema
I think yes? I only didn't because it wasn't obvious to me from that website what the list of allowed values would be. But I didn't really look into this.

2024-12-13 17:28 UTC, martonvago commented on seedcase_sprout/core/checks/add_resource_recommendations.py
> +    return schema
Yeah, I think it's possible to add conditional requirements. Like, if `type` is set to `"table"`, then `schema` is `required`. But I would need to look up how exactly to do it. Maybe we could have a separate issue for additional recommendations? They're pretty independent of each other, so anyone could pick them up :))

2024-12-13 17:28 UTC, martonvago commented on seedcase_sprout/core/checks/check_object_against_json_schema.py
> +    Draft7Validator.check_schema(schema)
Yes, it's not checked without this. I thought I would check it here because I'm messing with it when I add recommendations.

2024-12-13 17:28 UTC, martonvago commented on seedcase_sprout/core/checks/check_package_properties.py
> +    schema = read_json(DATA_PACKAGE_SCHEMA_PATH)
This was in relation to a discussion we had about having the `schema` as an argument to the function, as opposed to reading it from file inside the function. And I'm just saying that I don't think it makes sense to do that because we will always want to read in this schema.

2024-12-13 17:28 UTC, martonvago commented on seedcase_sprout/core/checks/config.py
> +    r"[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$"
Yeah haha! Welllll it's tested a little bit when the recommendations are turned on, but only using simple versions

2024-12-13 17:28 UTC, martonvago commented on seedcase_sprout/core/checks/schemas/data-package-schema.json
These are all valid questions and I will play an @lwjohnst86 card

2024-12-13 18:51 UTC, lwjohnst86 submitted a review, later dismissed
I haven't had a super long look into the tests, but they look mostly like typical boilerplate tests. Otherwise, I approve, aside from Signe's suggetions/edits.

2024-12-13 18:51 UTC, lwjohnst86 commented on seedcase_sprout/core/checks/add_package_recommendations.py
> +    return schema
I think that's fair. If the spec doesn't say anything about it, let's stick with not doing anything until we encounter a situation that might need it. Otherwise, we might be overthinking future needs.

2024-12-13 18:51 UTC, lwjohnst86 commented on seedcase_sprout/core/checks/add_resource_recommendations.py
> +    return schema
Yea, I'm not sure how relevant this might be for us. So maybe not check for now. Agreed with what @martonvago wrote.

2024-12-13 18:51 UTC, lwjohnst86 commented on seedcase_sprout/core/checks/add_resource_recommendations.py
> +    return schema
Good idea with making the separate issues for these and deal with them as they come up. :+1:

2024-12-13 18:51 UTC, lwjohnst86 commented on seedcase_sprout/core/checks/check_package_properties.py
> +    schema = read_json(DATA_PACKAGE_SCHEMA_PATH)
I think for now that makes sense.

2024-12-13 18:51 UTC, lwjohnst86 commented on seedcase_sprout/core/checks/config.py
I'm not sure I love it, but it's easy to change and I don't think it matter enough right now :stuck_out_tongue:

2024-12-13 18:51 UTC, lwjohnst86 commented on seedcase_sprout/core/checks/schemas/data-package-schema.json
Nice thoughts @signekb! Yea, that could be the case, to use different versions. I suggested this folder so it is separate from the code, that's all.

2024-12-14 12:53 UTC, signekb commented on seedcase_sprout/core/checks/add_package_recommendations.py
> +    schema["required"].extend(["name", "id", "licenses"])
Great!

2024-12-14 12:59 UTC, signekb commented on seedcase_sprout/core/checks/schemas/data-package-schema.json
@lwjohnst86  Ok, so include the version name in the schema json file? Or?

2024-12-16 08:59 UTC, signekb commented on seedcase_sprout/core/checks/add_resource_recommendations.py
> +    return schema
Maybe add a comment on this, so it's explicit why we don't include this recommendation

2024-12-16 08:59 UTC, signekb commented on seedcase_sprout/core/checks/add_resource_recommendations.py
> +    return schema
I've made an issue here: https://github.com/seedcase-project/seedcase-sprout/issues/912

2024-12-16 09:22 UTC, martonvago commented on seedcase_sprout/core/checks/add_package_recommendations.py
> +    """
I added a reference to this in the individual check functions (trying not to go into too much detail)

2024-12-16 09:25 UTC, martonvago commented on seedcase_sprout/core/checks/add_resource_recommendations.py
> +    return schema
I think strictly speaking there are other ones we don't include (yet), so it's all a bit of a work in progress

2024-12-16 09:31 UTC, martonvago commented on tests/core/test_check_object_against_json_schema.py
Sorry, didn't see this last time! I didn't include one for the actual schema in this particular test file because in the test files for the other 3 check functions the actual schema is tested pretty thoroughly and for the same test cases. And there it goes through this function anyway each time.

2024-12-16 12:29 UTC, signekb reviewed
Nice 👍  Just one question.

2024-12-16 12:29 UTC, signekb commented on seedcase_sprout/core/checks/check_package_properties.py
> +    in the `$schema` attribute of `properties`, including the default value.
Does is actually *overwrite* values in the `$schema` attribute? Not e.g., *ignore*?

2024-12-16 16:32 UTC, martonvago commented on seedcase_sprout/core/checks/check_package_properties.py
> +    in the `$schema` attribute of `properties`, including the default value.
I think "override" is okay to use here? Instead of reading the `$schema` attribute (or its default value) in the schema or in the properties object, we just use the schema we load from file (and add recommendations to). But it's also true that these `$schema` attributes are ignored.

2024-12-16 16:34 UTC, lwjohnst86 commented on seedcase_sprout/core/checks/schemas/data-package-schema.json
Fine not to include :relaxed:

2024-12-16 16:34 UTC, lwjohnst86 approved these changes

2024-12-16 16:35 UTC, merged