:sparkles: Add custom `CheckError` for check functions
seedcase-project/seedcase-sprout pull request #924
Opened 2024-12-19 17:56 UTC by martonvago

## Description

This PR adds a custom `CheckError` to represent violations of individual rules / validators. This error corresponds roughly to `jsonschema`'s `ValidationError`, but it is simpler and includes a bit more information for errors violating required-checks.

Some more detail on why this is nice: [here](https://github.com/seedcase-project/seedcase-sprout/issues/921).
But the main benefits are:
  - Users of the `check` package will not need to depend on `jsonschema` directly.
  - It will be a LOT easier to process errors downstream (so in Sprout).
  - We have more control over what to include in the errors and how to display them.

Closes #921 

This PR needs an in-depth review.
Focus on whether this is a reasonable way of structuring and displaying errors.

## Checklist

- [x] Added or updated tests
- [x] Updated documentation
- [x] Ran `just run-all`

2024-12-19 17:57 UTC, martonvago commented on seedcase_sprout/core/checks/__init__.py
This is a WIP

2024-12-19 17:58 UTC, martonvago commented on seedcase_sprout/core/checks/check_error.py
> +@total_ordering
This makes it so that `CheckError`s can be compared

2024-12-19 18:00 UTC, martonvago commented on seedcase_sprout/core/checks/check_error.py
> +                the error occurred.
E.g. `$.resources[2].name`

2024-12-19 18:02 UTC, martonvago commented on seedcase_sprout/core/checks/check_error.py
> +                the error occurred.
For now I put it as a string, but we can change it to something easier to manipulate later if we need to.

2024-12-19 18:04 UTC, martonvago commented on seedcase_sprout/core/checks/check_error.py
> +        )
So order the errors alphabetically, first by `json_path`, then breaking ties by `validator`, then by `message`

2024-12-19 18:15 UTC, martonvago commented on seedcase_sprout/core/checks/get_full_json_path_from_error.py
By default `jsonschema` doesn't add the field name to the path for errors triggered by missing required fields. I think for us / Sprout this would be useful, so I'm adding the field name in our `CheckError`s.

2025-01-08 21:18 UTC, lwjohnst86 requested changes
It's a bit of a big PR, so will review more of this again tomorrow :relaxed:

2025-01-08 21:18 UTC, lwjohnst86 commented on seedcase_sprout/core/checks/to_check_errors.py
> +    The list of errors is
```suggestion
    The list of errors is:
    
```

2025-01-08 21:18 UTC, lwjohnst86 commented on seedcase_sprout/core/checks/unwrap_errors.py
> +            unwrapped.extend(unwrap_errors(error.context))
There's something about this that I feel is off, but I can't pinpoint it. I'll come back to it another time. I think it's the nested use of the same function plus the for loop in general. :thinking:

2025-01-08 21:18 UTC, lwjohnst86 commented on seedcase_sprout/core/checks/check_error.py
> +        """Checks if this error is less than an object.
I'm a bit confused, what does "less than an object" mean?

2025-01-10 10:47 UTC, martonvago commented on seedcase_sprout/core/checks/__init__.py
> +__all__ = [check_properties, check_package_properties, check_resource_properties]
You're right, they do!!

2025-01-10 11:07 UTC, martonvago commented on seedcase_sprout/core/checks/check_error.py
> +    def __eq__(self, other: object) -> bool:
It's the root of the class hierarchy, so everything is an `object`. And here I want to be able to compare everything with a `CheckError`.

2025-01-10 11:14 UTC, martonvago commented on seedcase_sprout/core/checks/check_error.py
> +        """Checks if this error is less than an object.
As in: when I compare a `CheckError` with any other object (like `check_error < 123`), I want `__lt__` to decide whether the error counts as less than that object. Here `__lt__` says that if the other object is not a `CheckError` then it cannot do the comparison. But if the other object is a `CheckError` it can meaningfully compare them and decide which one should come first when they are sorted.

2025-01-10 11:24 UTC, martonvago commented on seedcase_sprout/core/checks/check_error.py
> +        """Returns a hash for this error.
It's like a companion piece to `__eq__`. Some built-in Python functions (e.g. `set`) rely on computing a hash (a unique integer) for the items they operate on. So if I want to be able to do e.g. `set([error1, error2, error1])`, I need `CheckError` to be hashable.

2025-01-10 11:35 UTC, martonvago commented on seedcase_sprout/core/checks/unwrap_errors.py
> +            unwrapped.extend(unwrap_errors(error.context))
It'll probably help that the structure of `ValidationError`s is like:
```json
{
    "some_field": "some value",
    "context": [
        {
            "some_field": "some value",
            "context": [
                {"some_field": "some value", "context": [...]},
                {"some_field": "some value", "context": [...]},
            ],
        },
        {"some_field": "some value", "context": []},
    ],
}
```
So each error can have a `context` property that lists more errors, where, again, each of those may have a `context` with yet more errors. Here we want to traverse this structure to the end and put all nested errors into one flat list.

2025-01-10 11:37 UTC, martonvago commented on seedcase_sprout/core/checks/__init__.py
> +__all__ = [check_properties, check_package_properties, check_resource_properties]
```suggestion
__all__ = ["check_properties", "check_package_properties", "check_resource_properties"]
```

2025-01-13 14:46 UTC, signekb reviewed
Sorry for the long wait. 
Great work! 🌟 I only have some minor comments/suggestions/questions.

2025-01-13 14:46 UTC, signekb commented on tests/core/checks/test_to_check_errors.py
> +    """Should ignore errors from validators in the COMPLEX_VALIDATORS set."""
Maybe write this in the function docstring and why it ignores these errrors? :)

2025-01-13 14:46 UTC, signekb commented on tests/core/checks/test_unwrap_errors.py
> +def test_unwraps_deeply_nested_errors():
Is there any reason why `unwrap_errors` doesn't deduplicate the errors as well?

2025-01-13 16:07 UTC, martonvago commented on tests/core/checks/test_to_check_errors.py
> +    """Should ignore errors from validators in the COMPLEX_VALIDATORS set."""
It says "filtered for summary-type errors"?

2025-01-15 11:36 UTC, signekb approved these changes
Nice work 👍 👍

2025-01-20 08:27 UTC, lwjohnst86 approved these changes
Very nice! A bit big of a PR, but I'm done reviewing it :grin: I think it would help a lot to have this moved over into it's own package though!! Conceptually makes a lot of sense, but we'll do that maybe next iteration or two.

2025-01-20 08:27 UTC, merged